<?php
/**
 * Migration: Create slider_slides table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateSliderSlidesTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `slider_slides` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `slider_id` int(10) unsigned NOT NULL,
                  `image_url` varchar(255) NOT NULL,
                  `title` varchar(255) DEFAULT NULL,
                  `description` text DEFAULT NULL,
                  `link_url` varchar(255) DEFAULT NULL,
                  `sort_order` int(11) NOT NULL DEFAULT 0,
                  `is_active` tinyint(1) NOT NULL DEFAULT 1,
                  `created_at` timestamp NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `idx_slider_slides_slider_id` (`slider_id`),
                  KEY `idx_slider_slides_order` (`sort_order`),
                  KEY `idx_slider_slides_active` (`is_active`),
                  CONSTRAINT `fk_slider_slides_slider_id` FOREIGN KEY (`slider_id`) REFERENCES `sliders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table slider_slides created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `slider_slides`");
        echo "✓ Table slider_slides dropped\n";
    }
}
