<?php
/**
 * Migration: Create gallery_settings table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateGallerySettingsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `gallery_settings` (
                  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) unsigned DEFAULT NULL COMMENT 'NULL = configuración global',
                  `setting_key` varchar(100) NOT NULL,
                  `setting_value` text DEFAULT NULL,
                  `setting_type` enum('string','int','bool','json','array') DEFAULT 'string',
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_setting_tenant` (`setting_key`,`tenant_id`),
                  KEY `idx_tenant_id` (`tenant_id`)
                ) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table gallery_settings created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `gallery_settings`");
        echo "✓ Table gallery_settings dropped\n";
    }
}
