<?php
/**
 * Migration: Create custom_form_submissions table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateCustomFormSubmissionsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `custom_form_submissions` (
                  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                  `form_id` int(11) unsigned NOT NULL,
                  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Datos del envío en JSON' CHECK (json_valid(`data`)),
                  `ip_address` varchar(45) DEFAULT NULL,
                  `user_agent` varchar(500) DEFAULT NULL,
                  `referrer_url` varchar(500) DEFAULT NULL,
                  `page_url` varchar(500) DEFAULT NULL COMMENT 'URL donde se envió el formulario',
                  `user_id` int(11) unsigned DEFAULT NULL COMMENT 'Usuario autenticado si aplica',
                  `email_sent` tinyint(1) DEFAULT 0,
                  `email_sent_at` datetime DEFAULT NULL,
                  `confirmation_sent` tinyint(1) DEFAULT 0,
                  `is_read` tinyint(1) DEFAULT 0,
                  `is_starred` tinyint(1) DEFAULT 0,
                  `is_spam` tinyint(1) DEFAULT 0,
                  `notes` text DEFAULT NULL COMMENT 'Notas internas',
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `idx_form_id` (`form_id`),
                  KEY `idx_created_at` (`created_at`),
                  KEY `idx_is_read` (`is_read`),
                  KEY `idx_is_starred` (`is_starred`),
                  KEY `idx_is_spam` (`is_spam`),
                  CONSTRAINT `fk_submissions_form` FOREIGN KEY (`form_id`) REFERENCES `custom_forms` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table custom_form_submissions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `custom_form_submissions`");
        echo "✓ Table custom_form_submissions dropped\n";
    }
}
