<?php
/**
 * Migration: Create modules table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateModulesTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `modules` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `slug` varchar(100) DEFAULT NULL,
                  `name` varchar(100) DEFAULT NULL,
                  `description` text DEFAULT NULL,
                  `version` varchar(20) DEFAULT NULL,
                  `author` varchar(100) DEFAULT NULL,
                  `active` tinyint(1) DEFAULT 1,
                  `public` tinyint(1) DEFAULT 0,
                  `created_at` datetime DEFAULT current_timestamp(),
                  `slug_prefix` varchar(50) DEFAULT NULL,
                  `has_slugs` tinyint(1) DEFAULT 0,
                  `cms_enabled` tinyint(1) DEFAULT 1,
                  `tenant_enabled_default` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Si está habilitado por defecto para nuevos tenants',
                  `installed_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Fecha de instalación',
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `slug` (`slug`)
                ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table modules created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `modules`");
        echo "✓ Table modules dropped\n";
    }
}
