<?php
/**
 * Migration: Create ai_usage_logs table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateAiUsageLogsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `ai_usage_logs` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `provider_id` int(11) DEFAULT NULL,
                  `prompt` text DEFAULT NULL,
                  `tokens_used` int(11) DEFAULT NULL,
                  `status` varchar(50) DEFAULT NULL,
                  `user_id` int(11) DEFAULT NULL,
                  `user_type` varchar(20) DEFAULT NULL,
                  `module` varchar(50) DEFAULT NULL,
                  `action` varchar(50) DEFAULT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `provider_id` (`provider_id`),
                  CONSTRAINT `ai_usage_logs_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `ai_providers` (`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table ai_usage_logs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `ai_usage_logs`");
        echo "✓ Table ai_usage_logs dropped\n";
    }
}
