<?php
/**
 * Migration: Create admins table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateAdminsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admins` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL,
                  `email` varchar(255) NOT NULL,
                  `password` varchar(255) NOT NULL,
                  `name` varchar(255) DEFAULT NULL,
                  `avatar` varchar(255) DEFAULT NULL,
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  `two_factor_enabled` tinyint(1) DEFAULT 0,
                  `two_factor_secret` varchar(64) DEFAULT NULL,
                  `two_factor_recovery_codes` text DEFAULT NULL,
                  `two_factor_enabled_at` datetime DEFAULT NULL,
                  `two_factor_last_used_at` datetime DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `email` (`email`),
                  KEY `idx_email_tenant` (`email`,`tenant_id`),
                  KEY `idx_admins_tenant` (`tenant_id`),
                  KEY `idx_admins_email` (`email`),
                  KEY `idx_admins_2fa` (`two_factor_enabled`),
                  CONSTRAINT `fk_admins_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table admins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `admins`");
        echo "✓ Table admins dropped\n";
    }
}
