<?php
/**
 * Migration: Create users table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateUsersTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `users` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL,
                  `name` varchar(100) NOT NULL,
                  `email` varchar(150) NOT NULL,
                  `avatar` varchar(255) DEFAULT NULL,
                  `password` varchar(255) NOT NULL,
                  `registered_ip` varchar(45) DEFAULT NULL,
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  `two_factor_enabled` tinyint(1) DEFAULT 0,
                  `two_factor_secret` varchar(64) DEFAULT NULL,
                  `two_factor_recovery_codes` text DEFAULT NULL,
                  `two_factor_enabled_at` datetime DEFAULT NULL,
                  `two_factor_last_used_at` datetime DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `uk_user_email` (`email`),
                  KEY `idx_email_tenant` (`email`,`tenant_id`),
                  KEY `idx_users_tenant` (`tenant_id`),
                  KEY `idx_users_email` (`email`),
                  KEY `idx_users_2fa` (`two_factor_enabled`)
                ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table users created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `users`");
        echo "✓ Table users dropped\n";
    }
}
