<?php
/**
 * Migration: Create blog_posts_trash table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateBlogPostsTrashTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_posts_trash` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `post_id` int(11) NOT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  `deleted_by` int(11) NOT NULL,
                  `deleted_by_name` varchar(100) DEFAULT NULL COMMENT 'Cache del nombre',
                  `deleted_by_type` enum('user','admin','superadmin') DEFAULT 'admin',
                  `deleted_at` datetime NOT NULL,
                  `scheduled_permanent_delete` datetime DEFAULT NULL COMMENT 'Auto-eliminar después de 30 días',
                  `reason` varchar(255) DEFAULT NULL COMMENT 'Razón de eliminación (opcional)',
                  `ip_address` varchar(45) DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  KEY `idx_post_id` (`post_id`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_deleted_at` (`deleted_at`),
                  KEY `idx_scheduled_delete` (`scheduled_permanent_delete`),
                  KEY `idx_deleted_by` (`deleted_by`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Papelera temporal de blog posts (recuperable por 30 días)'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_posts_trash created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_posts_trash`");
        echo "✓ Table blog_posts_trash dropped\n";
    }
}
