<?php
/**
 * Migration: Create blog_posts table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateBlogPostsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_posts` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para posts globales)',
                  `user_id` int(11) NOT NULL COMMENT 'ID del autor',
                  `user_type` enum('superadmin','admin','user') NOT NULL DEFAULT 'admin' COMMENT 'Tipo de usuario autor',
                  `title` varchar(500) NOT NULL COMMENT 'Título del post',
                  `slug` varchar(600) NOT NULL COMMENT 'URL amigable',
                  `excerpt` text DEFAULT NULL COMMENT 'Resumen o extracto del post',
                  `content` longtext NOT NULL COMMENT 'Contenido completo del post',
                  `featured_image` varchar(500) DEFAULT NULL COMMENT 'Imagen destacada',
                  `hide_featured_image` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ocultar imagen destacada en vistas públicas',
                  `status` enum('draft','published','trash') DEFAULT 'draft',
                  `visibility` enum('public','private','password') NOT NULL DEFAULT 'public' COMMENT 'Visibilidad del post',
                  `password` varchar(255) DEFAULT NULL COMMENT 'Contraseña si visibility=password',
                  `published_at` datetime DEFAULT NULL COMMENT 'Fecha de publicación',
                  `base_locale` varchar(10) NOT NULL DEFAULT 'es' COMMENT 'Idioma base del post',
                  `allow_comments` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Permitir comentarios',
                  `comment_count` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Contador de comentarios',
                  `view_count` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Contador de vistas',
                  `featured` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Post destacado',
                  `template` varchar(255) DEFAULT NULL COMMENT 'Plantilla personalizada para el post',
                  `seo_title` varchar(500) DEFAULT NULL COMMENT 'Título para SEO',
                  `seo_description` text DEFAULT NULL COMMENT 'Descripción para SEO',
                  `seo_keywords` text DEFAULT NULL COMMENT 'Palabras clave',
                  `seo_image` varchar(500) DEFAULT NULL COMMENT 'Imagen para redes sociales',
                  `canonical_url` varchar(500) DEFAULT NULL COMMENT 'URL canónica',
                  `robots_directive` varchar(100) DEFAULT 'index,follow' COMMENT 'Directivas para robots',
                  `twitter_title` varchar(500) DEFAULT NULL COMMENT 'Título para Twitter Card',
                  `twitter_description` text DEFAULT NULL COMMENT 'Descripción para Twitter Card',
                  `twitter_image` varchar(500) DEFAULT NULL COMMENT 'Imagen para Twitter Card',
                  `show_hero` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Mostrar sección hero',
                  `hero_image` varchar(500) DEFAULT NULL COMMENT 'Imagen de hero',
                  `hero_title` varchar(500) DEFAULT NULL COMMENT 'Título alternativo para hero',
                  `hero_content` text DEFAULT NULL COMMENT 'Contenido del hero',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  `deleted_at` datetime DEFAULT NULL COMMENT 'Fecha y hora de eliminación lógica',
                  `deleted_by` int(11) DEFAULT NULL COMMENT 'ID del usuario que eliminó el registro',
                  `revision_count` int(11) DEFAULT 0 COMMENT 'Contador de revisiones (cache)',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_slug` (`tenant_id`,`slug`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_user_id` (`user_id`),
                  KEY `idx_user_type` (`user_type`),
                  KEY `idx_slug` (`slug`),
                  KEY `idx_status` (`status`),
                  KEY `idx_visibility` (`visibility`),
                  KEY `idx_published_at` (`published_at`),
                  KEY `idx_featured` (`featured`),
                  KEY `idx_created_at` (`created_at`),
                  KEY `idx_blog_posts_deleted_at` (`deleted_at`),
                  KEY `idx_blog_posts_tenant` (`tenant_id`),
                  KEY `idx_blog_posts_status` (`status`),
                  KEY `idx_blog_posts_published` (`published_at`),
                  KEY `idx_blog_posts_slug` (`slug`),
                  KEY `idx_blog_posts_tenant_status` (`tenant_id`,`status`),
                  KEY `idx_blog_posts_deleted` (`deleted_at`),
                  CONSTRAINT `fk_blog_posts_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_posts created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_posts`");
        echo "✓ Table blog_posts dropped\n";
    }
}
