<?php
/**
 * Migration: Create user_roles table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateUserRolesTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `user_roles` (
                  `user_id` int(11) NOT NULL,
                  `user_type` enum('admin','user','superadmin') NOT NULL,
                  `role_id` int(11) NOT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`user_id`,`user_type`,`role_id`),
                  KEY `role_id` (`role_id`),
                  KEY `idx_user_roles_user_id` (`user_id`),
                  KEY `fk_user_roles_tenant` (`tenant_id`),
                  CONSTRAINT `fk_user_roles_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`),
                  CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table user_roles created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `user_roles`");
        echo "✓ Table user_roles dropped\n";
    }
}
