<?php
/**
 * Migration: Create site_menus table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateSiteMenusTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS `site_menus` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `title` varchar(255) DEFAULT NULL,
                  `location` varchar(255) DEFAULT NULL,
                  `show_title` tinyint(1) NOT NULL DEFAULT 1,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  `tenant_id` int(11) DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  KEY `idx_tenant_id` (`tenant_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            ");

            // Añadir columna show_title si la tabla ya existe pero no tiene la columna
            $stmt = $pdo->query("SHOW COLUMNS FROM `site_menus` LIKE 'show_title'");
            if ($stmt->rowCount() === 0) {
                $pdo->exec("ALTER TABLE `site_menus` ADD COLUMN `show_title` tinyint(1) NOT NULL DEFAULT 1 AFTER `location`");
            }
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table site_menus created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `site_menus`");
        echo "✓ Table site_menus dropped\n";
    }
}
