<?php
/**
 * Migration: Create admin_menu_customizations table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateAdminMenuCustomizationsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admin_menu_customizations` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL,
                  `admin_menu_id` int(11) NOT NULL,
                  `custom_title` varchar(255) DEFAULT NULL,
                  `custom_icon` varchar(100) DEFAULT NULL,
                  `custom_icon_type` enum('bi','fas','far','fal') DEFAULT NULL,
                  `custom_order_position` int(11) DEFAULT NULL,
                  `is_hidden` tinyint(1) DEFAULT 0,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_menu` (`tenant_id`,`admin_menu_id`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_admin_menu_id` (`admin_menu_id`),
                  CONSTRAINT `admin_menu_customizations_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
                  CONSTRAINT `admin_menu_customizations_ibfk_2` FOREIGN KEY (`admin_menu_id`) REFERENCES `admin_menus` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table admin_menu_customizations created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `admin_menu_customizations`");
        echo "✓ Table admin_menu_customizations dropped\n";
    }
}
