<?php
/**
 * Migration: Create react_sliders table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateReactSlidersTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `react_sliders` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `name` varchar(255) NOT NULL COMMENT 'Nombre del slider',
                  `identifier` varchar(100) NOT NULL COMMENT 'Identificador único',
                  `engine` enum('swiper','slick','keen','embla') DEFAULT 'swiper' COMMENT 'Motor del slider',
                  `settings` text DEFAULT NULL COMMENT 'Configuración JSON',
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL = global)',
                  `is_active` tinyint(1) DEFAULT 1 COMMENT '1 = Activo, 0 = Inactivo',
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_identifier_tenant` (`identifier`,`tenant_id`),
                  KEY `tenant_id` (`tenant_id`),
                  KEY `is_active` (`is_active`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sliders React modernos'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table react_sliders created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `react_sliders`");
        echo "✓ Table react_sliders dropped\n";
    }
}
