<?php
/**
 * Migration: Create scheduled_tasks table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateScheduledTasksTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `scheduled_tasks` (
                  `task_name` varchar(100) NOT NULL COMMENT 'Nombre único de la tarea',
                  `last_run` datetime DEFAULT NULL COMMENT 'Última vez que se ejecutó',
                  `next_run` datetime DEFAULT NULL COMMENT 'Próxima ejecución programada',
                  `status` enum('idle','running','failed') DEFAULT 'idle' COMMENT 'Estado actual',
                  `last_error` text DEFAULT NULL COMMENT 'Último error ocurrido',
                  `last_duration` int(11) DEFAULT NULL COMMENT 'Duración de última ejecución (segundos)',
                  `run_count` int(11) DEFAULT 0 COMMENT 'Número total de ejecuciones',
                  `success_count` int(11) DEFAULT 0 COMMENT 'Número de ejecuciones exitosas',
                  `fail_count` int(11) DEFAULT 0 COMMENT 'Número de ejecuciones fallidas',
                  `locked_until` datetime DEFAULT NULL COMMENT 'Lock para evitar ejecuciones concurrentes',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`task_name`),
                  KEY `idx_status` (`status`),
                  KEY `idx_next_run` (`next_run`),
                  KEY `idx_locked_until` (`locked_until`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tracking de tareas programadas (cron/pseudo-cron)'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table scheduled_tasks created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `scheduled_tasks`");
        echo "✓ Table scheduled_tasks dropped\n";
    }
}
