<?php
/**
 * Migration: Create media_folders table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateMediaFoldersTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `media_folders` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL,
                  `disk` varchar(50) DEFAULT 'media',
                  `parent_id` int(11) DEFAULT NULL,
                  `name` varchar(255) NOT NULL,
                  `slug` varchar(255) NOT NULL,
                  `path` varchar(512) NOT NULL,
                  `description` text DEFAULT NULL,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_folder_path` (`tenant_id`,`path`(255)),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_parent_id` (`parent_id`),
                  KEY `idx_path` (`path`(255)),
                  KEY `idx_media_folders_disk` (`disk`),
                  KEY `idx_media_folders_disk_tenant` (`disk`,`tenant_id`,`parent_id`),
                  CONSTRAINT `media_folders_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `media_folders` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table media_folders created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `media_folders`");
        echo "✓ Table media_folders dropped\n";
    }
}
