<?php
/**
 * Migration: Create blog_post_categories table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateBlogPostCategoriesTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_categories` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
                  `category_id` int(10) unsigned NOT NULL COMMENT 'ID de la categoría',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_post_category` (`post_id`,`category_id`),
                  KEY `idx_post_id` (`post_id`),
                  KEY `idx_category_id` (`category_id`),
                  KEY `idx_blog_post_categories_post` (`post_id`),
                  KEY `idx_blog_post_categories_category` (`category_id`),
                  CONSTRAINT `fk_blog_post_categories_category` FOREIGN KEY (`category_id`) REFERENCES `blog_categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                  CONSTRAINT `fk_blog_post_categories_post` FOREIGN KEY (`post_id`) REFERENCES `blog_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                  CONSTRAINT `fk_bpc_category` FOREIGN KEY (`category_id`) REFERENCES `blog_categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                  CONSTRAINT `fk_bpc_post` FOREIGN KEY (`post_id`) REFERENCES `blog_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_post_categories created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_post_categories`");
        echo "✓ Table blog_post_categories dropped\n";
    }
}
