<?php
/**
 * Migration: Create page_meta table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreatePageMetaTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `page_meta` (
                  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                  `page_id` int(11) NOT NULL,
                  `meta_key` varchar(255) NOT NULL,
                  `meta_value` longtext DEFAULT NULL,
                  `created_at` timestamp NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `idx_page_meta_page_id` (`page_id`),
                  KEY `idx_page_meta_key` (`meta_key`),
                  CONSTRAINT `fk_page_meta_page_id` FOREIGN KEY (`page_id`) REFERENCES `pages` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table page_meta created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `page_meta`");
        echo "✓ Table page_meta dropped\n";
    }
}
