<?php
/**
 * Migration: Create page_revisions table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreatePageRevisionsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `page_revisions` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `page_id` int(11) NOT NULL,
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'NULL para páginas de superadmin',
                  `user_id` int(11) DEFAULT NULL,
                  `user_name` varchar(100) DEFAULT NULL COMMENT 'Cache del nombre para auditoría',
                  `user_type` enum('user','admin','superadmin') DEFAULT 'admin',
                  `revision_type` enum('autosave','manual','published','restored','scheduled','initial') NOT NULL DEFAULT 'manual',
                  `title` varchar(255) NOT NULL,
                  `slug` varchar(255) DEFAULT NULL,
                  `content` longtext NOT NULL,
                  `excerpt` text DEFAULT NULL,
                  `slider_image` varchar(255) DEFAULT NULL,
                  `meta_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'SEO, visibilidad, layout, custom fields, etc.' CHECK (json_valid(`meta_data`)),
                  `status` enum('draft','published','scheduled','trash') DEFAULT NULL,
                  `created_at` datetime NOT NULL,
                  `ip_address` varchar(45) DEFAULT NULL,
                  `user_agent` text DEFAULT NULL,
                  `changes_summary` varchar(255) DEFAULT NULL COMMENT 'Descripción breve de los cambios',
                  PRIMARY KEY (`id`),
                  KEY `idx_page_id` (`page_id`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_created_at` (`created_at`),
                  KEY `idx_revision_type` (`revision_type`),
                  KEY `idx_user_id` (`user_id`)
                ) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Historial completo de revisiones de páginas'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table page_revisions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `page_revisions`");
        echo "✓ Table page_revisions dropped\n";
    }
}
