<?php
/**
 * Migration: Create ip_blacklist table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateIpBlacklistTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `ip_blacklist` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `ip_address` varchar(45) NOT NULL,
                  `reason` varchar(255) DEFAULT NULL,
                  `blocked_by` varchar(50) DEFAULT 'system',
                  `expires_at` datetime DEFAULT NULL,
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_ip` (`ip_address`),
                  KEY `idx_expires` (`expires_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table ip_blacklist created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `ip_blacklist`");
        echo "✓ Table ip_blacklist dropped\n";
    }
}
