<?php
/**
 * Migration: Create waf_logs table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateWafLogsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `waf_logs` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `type` varchar(50) NOT NULL,
                  `source` varchar(100) NOT NULL,
                  `ip_address` varchar(45) NOT NULL,
                  `uri` text DEFAULT NULL,
                  `method` varchar(10) DEFAULT NULL,
                  `user_agent` text DEFAULT NULL,
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `idx_type` (`type`),
                  KEY `idx_ip` (`ip_address`),
                  KEY `idx_date` (`created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table waf_logs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `waf_logs`");
        echo "✓ Table waf_logs dropped\n";
    }
}
