<?php
/**
 * Migration: Create tenant_admin_menu_visibility table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateTenantAdminMenuVisibilityTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_admin_menu_visibility` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) NOT NULL,
                  `admin_menu_id` int(11) NOT NULL,
                  `is_visible` tinyint(1) DEFAULT 1,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_menu` (`tenant_id`,`admin_menu_id`),
                  KEY `admin_menu_id` (`admin_menu_id`),
                  CONSTRAINT `tenant_admin_menu_visibility_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
                  CONSTRAINT `tenant_admin_menu_visibility_ibfk_2` FOREIGN KEY (`admin_menu_id`) REFERENCES `admin_menus` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table tenant_admin_menu_visibility created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `tenant_admin_menu_visibility`");
        echo "✓ Table tenant_admin_menu_visibility dropped\n";
    }
}
