<?php
/**
 * Migration: Create notifications table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateNotificationsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `notifications` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `user_id` int(11) NOT NULL COMMENT 'ID del usuario destinatario',
                  `user_type` enum('admin','super_admin') NOT NULL COMMENT 'Tipo de usuario',
                  `type` varchar(100) NOT NULL COMMENT 'Tipo de notificación',
                  `title` varchar(255) NOT NULL COMMENT 'Título',
                  `message` text NOT NULL COMMENT 'Mensaje',
                  `data` text DEFAULT NULL COMMENT 'Datos adicionales (JSON)',
                  `is_read` tinyint(1) DEFAULT 0 COMMENT '1 = Leída, 0 = No leída',
                  `read_at` datetime DEFAULT NULL COMMENT 'Fecha de lectura',
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `user_type_id` (`user_type`,`user_id`),
                  KEY `is_read` (`is_read`),
                  KEY `created_at` (`created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Notificaciones de usuarios'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table notifications created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `notifications`");
        echo "✓ Table notifications dropped\n";
    }
}
