<?php
/**
 * Migration: Create page_meta table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102213
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreatePageMetaTable_2025_12_11_102213
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `page_meta` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `page_id` int(11) NOT NULL,
  `meta_key` varchar(255) NOT NULL,
  `meta_value` longtext DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_page_meta_page_id` (`page_id`),
  KEY `idx_page_meta_key` (`meta_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE page_meta (
  id SERIAL PRIMARY KEY,
  page_id INTEGER NOT NULL,
  meta_key VARCHAR(255) NOT NULL,
  meta_value TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX page_meta_idx_page_meta_page_id ON page_meta(page_id)");
            $pdo->exec("CREATE INDEX page_meta_idx_page_meta_key ON page_meta(meta_key)");
        }

        echo "✓ Table page_meta created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `page_meta`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS page_meta");
        }

        echo "✓ Table page_meta dropped\n";
    }
}
