<?php
/**
 * Migration: Create admin_session_tokens table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102213
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAdminSessionTokensTable_2025_12_11_102213
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admin_session_tokens` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL,
  `token` varchar(64) NOT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `persistent` tinyint(1) DEFAULT '1',
  `created_at` datetime NOT NULL,
  `expires_at` datetime NOT NULL,
  `last_used_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_admin_token` (`token`),
  KEY `fk_admin_token` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE admin_session_tokens (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER NOT NULL,
  token VARCHAR(64) NOT NULL,
  ip VARCHAR(45),
  user_agent VARCHAR(255),
  persistent SMALLINT DEFAULT '1',
  created_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  last_used_at TIMESTAMP NOT NULL,
  UNIQUE (token)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX admin_session_tokens_fk_admin_token ON admin_session_tokens(admin_id)");
        }

        echo "✓ Table admin_session_tokens created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `admin_session_tokens`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS admin_session_tokens");
        }

        echo "✓ Table admin_session_tokens dropped\n";
    }
}
