<?php
/**
 * Migration: Create superadmin_plugin_assets table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginAssetsTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_assets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plugin_id` int(11) NOT NULL COMMENT 'ID del plugin',
  `type` enum('css','js') NOT NULL COMMENT 'Tipo de asset',
  `path` varchar(500) NOT NULL COMMENT 'Ruta del archivo',
  `location` enum('header','footer') DEFAULT 'footer' COMMENT 'Dónde cargar el asset',
  `priority` int(11) DEFAULT '10' COMMENT 'Prioridad de carga',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '1 = Activo, 0 = Inactivo',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `type` (`type`),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE superadmin_plugin_assets (
  id SERIAL PRIMARY KEY,
  plugin_id INTEGER NOT NULL,
  "type" VARCHAR(20) NOT NULL,
  path VARCHAR(500) NOT NULL,
  location VARCHAR(20) DEFAULT 'footer',
  priority INTEGER DEFAULT '10',
  is_active SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK ("type" IN ('css', 'js')),
  CHECK (location IN ('header', 'footer'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX superadmin_plugin_assets_plugin_id ON superadmin_plugin_assets(plugin_id)");
            $pdo->exec("CREATE INDEX superadmin_plugin_assets_type ON superadmin_plugin_assets("type")");
            $pdo->exec("CREATE INDEX superadmin_plugin_assets_is_active ON superadmin_plugin_assets(is_active)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_assets.plugin_id IS 'ID del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_assets."type" IS 'Tipo de asset'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_assets.path IS 'Ruta del archivo'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_assets.location IS 'Dónde cargar el asset'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_assets.priority IS 'Prioridad de carga'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_assets.is_active IS '1 = Activo, 0 = Inactivo'");
        }

        echo "✓ Table superadmin_plugin_assets created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_assets`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS superadmin_plugin_assets");
        }

        echo "✓ Table superadmin_plugin_assets dropped\n";
    }
}
