<?php
/**
 * Migration: Create superadmin_plugin_routes table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginRoutesTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_routes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plugin_id` int(11) NOT NULL COMMENT 'ID del plugin',
  `method` varchar(10) NOT NULL COMMENT 'GET, POST, PUT, DELETE, etc.',
  `path` varchar(500) NOT NULL COMMENT 'Ruta del endpoint',
  `controller` varchar(500) NOT NULL COMMENT 'Controlador',
  `action` varchar(255) NOT NULL COMMENT 'Método del controlador',
  `middleware` text DEFAULT NULL COMMENT 'Middlewares (JSON array)',
  `name` varchar(255) DEFAULT NULL COMMENT 'Nombre de la ruta',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '1 = Activa, 0 = Inactiva',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE superadmin_plugin_routes (
  id SERIAL PRIMARY KEY,
  plugin_id INTEGER NOT NULL,
  method VARCHAR(10) NOT NULL,
  path VARCHAR(500) NOT NULL,
  controller VARCHAR(500) NOT NULL,
  "action" VARCHAR(255) NOT NULL,
  middleware TEXT,
  name VARCHAR(255),
  is_active SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX superadmin_plugin_routes_plugin_id ON superadmin_plugin_routes(plugin_id)");
            $pdo->exec("CREATE INDEX superadmin_plugin_routes_is_active ON superadmin_plugin_routes(is_active)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.plugin_id IS 'ID del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.method IS 'GET, POST, PUT, DELETE, etc.'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.path IS 'Ruta del endpoint'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.controller IS 'Controlador'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes."action" IS 'Método del controlador'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.middleware IS 'Middlewares (JSON array)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.name IS 'Nombre de la ruta'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_routes.is_active IS '1 = Activa, 0 = Inactiva'");
        }

        echo "✓ Table superadmin_plugin_routes created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_routes`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS superadmin_plugin_routes");
        }

        echo "✓ Table superadmin_plugin_routes dropped\n";
    }
}
