<?php
/**
 * Migration: Create role_permissions table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateRolePermissionsTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `role_permissions` (
  `role_id` int(11) NOT NULL,
  `permission_id` int(11) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_role_permissions_permission_id` (`permission_id`),
  KEY `fk_role_permissions_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE role_permissions (
  role_id INTEGER NOT NULL,
  permission_id INTEGER NOT NULL,
  tenant_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX role_permissions_idx_role_permissions_permission_id ON role_permissions(permission_id)");
            $pdo->exec("CREATE INDEX role_permissions_fk_role_permissions_tenant ON role_permissions(tenant_id)");
        }

        echo "✓ Table role_permissions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `role_permissions`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS role_permissions");
        }

        echo "✓ Table role_permissions dropped\n";
    }
}
