<?php
/**
 * Migration: Create site_menu_translations table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSiteMenuTranslationsTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `site_menu_translations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menu_id` int(11) NOT NULL,
  `locale` varchar(10) NOT NULL DEFAULT 'es',
  `title` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `menu_id` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE site_menu_translations (
  id SERIAL PRIMARY KEY,
  menu_id INTEGER NOT NULL,
  locale VARCHAR(10) NOT NULL DEFAULT 'es',
  title VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX site_menu_translations_menu_id ON site_menu_translations(menu_id)");
        }

        echo "✓ Table site_menu_translations created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `site_menu_translations`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS site_menu_translations");
        }

        echo "✓ Table site_menu_translations dropped\n";
    }
}
