<?php
/**
 * Migration: Create ai_usage_logs table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102213
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAiUsageLogsTable_2025_12_11_102213
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `ai_usage_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `provider_id` int(11) DEFAULT NULL,
  `prompt` text DEFAULT NULL,
  `tokens_used` int(11) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_type` varchar(20) DEFAULT NULL,
  `module` varchar(50) DEFAULT NULL,
  `action` varchar(50) DEFAULT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `provider_id` (`provider_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE ai_usage_logs (
  id SERIAL PRIMARY KEY,
  provider_id INTEGER,
  prompt TEXT,
  tokens_used INTEGER,
  status VARCHAR(50),
  user_id INTEGER,
  user_type VARCHAR(20),
  module VARCHAR(50),
  "action" VARCHAR(50),
  tenant_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX ai_usage_logs_provider_id ON ai_usage_logs(provider_id)");
        }

        echo "✓ Table ai_usage_logs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `ai_usage_logs`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS ai_usage_logs");
        }

        echo "✓ Table ai_usage_logs dropped\n";
    }
}
