<?php
/**
 * Migration: Create user_roles table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateUserRolesTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `user_roles` (
  `user_id` int(11) NOT NULL,
  `user_type` enum('admin','user','superadmin') NOT NULL,
  `role_id` int(11) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `role_id` (`role_id`),
  KEY `idx_user_roles_user_id` (`user_id`),
  KEY `fk_user_roles_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE user_roles (
  user_id INTEGER NOT NULL,
  user_type VARCHAR(20) NOT NULL,
  role_id INTEGER NOT NULL,
  tenant_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (user_type IN ('admin', 'user', 'superadmin'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX user_roles_role_id ON user_roles(role_id)");
            $pdo->exec("CREATE INDEX user_roles_idx_user_roles_user_id ON user_roles(user_id)");
            $pdo->exec("CREATE INDEX user_roles_fk_user_roles_tenant ON user_roles(tenant_id)");
        }

        echo "✓ Table user_roles created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `user_roles`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS user_roles");
        }

        echo "✓ Table user_roles dropped\n";
    }
}
