<?php
/**
 * Migration: Create blog_tags table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102213
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogTagsTable_2025_12_11_102213
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para etiquetas globales)',
  `name` varchar(100) NOT NULL COMMENT 'Nombre de la etiqueta',
  `slug` varchar(150) NOT NULL COMMENT 'URL amigable',
  `description` text DEFAULT NULL COMMENT 'Descripción de la etiqueta',
  `color` varchar(7) DEFAULT NULL COMMENT 'Color en formato hexadecimal',
  `post_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Contador de posts',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL COMMENT 'Fecha y hora de eliminación lógica',
  `deleted_by` int(11) DEFAULT NULL COMMENT 'ID del usuario que eliminó el registro',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_slug` (`tenant_id`, `slug`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_slug` (`slug`),
  KEY `idx_blog_tags_deleted_at` (`deleted_at`),
  KEY `idx_blog_tags_tenant` (`tenant_id`),
  KEY `idx_blog_tags_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_tags (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(150) NOT NULL,
  description TEXT,
  color VARCHAR(7),
  post_count INTEGER NOT NULL DEFAULT '0',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  deleted_by INTEGER,
  UNIQUE (tenant_id, slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_tags_idx_tenant_id ON blog_tags(tenant_id)");
            $pdo->exec("CREATE INDEX blog_tags_idx_slug ON blog_tags(slug)");
            $pdo->exec("CREATE INDEX blog_tags_idx_blog_tags_deleted_at ON blog_tags(deleted_at)");
            $pdo->exec("CREATE INDEX blog_tags_idx_blog_tags_tenant ON blog_tags(tenant_id)");
            $pdo->exec("CREATE INDEX blog_tags_idx_blog_tags_slug ON blog_tags(slug)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_tags.tenant_id IS 'ID del tenant (NULL para etiquetas globales)'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.name IS 'Nombre de la etiqueta'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.slug IS 'URL amigable'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.description IS 'Descripción de la etiqueta'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.color IS 'Color en formato hexadecimal'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.post_count IS 'Contador de posts'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.deleted_at IS 'Fecha y hora de eliminación lógica'");
            $pdo->exec("COMMENT ON COLUMN blog_tags.deleted_by IS 'ID del usuario que eliminó el registro'");
        }

        echo "✓ Table blog_tags created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_tags`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_tags");
        }

        echo "✓ Table blog_tags dropped\n";
    }
}
