<?php
/**
 * Migration: Create waf_logs table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateWafLogsTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `waf_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `source` varchar(100) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `uri` text DEFAULT NULL,
  `method` varchar(10) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_type` (`type`),
  KEY `idx_ip` (`ip_address`),
  KEY `idx_date` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE waf_logs (
  id SERIAL PRIMARY KEY,
  "type" VARCHAR(50) NOT NULL,
  source VARCHAR(100) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  uri TEXT,
  method VARCHAR(10),
  user_agent TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX waf_logs_idx_type ON waf_logs("type")");
            $pdo->exec("CREATE INDEX waf_logs_idx_ip ON waf_logs(ip_address)");
            $pdo->exec("CREATE INDEX waf_logs_idx_date ON waf_logs(created_at)");
        }

        echo "✓ Table waf_logs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `waf_logs`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS waf_logs");
        }

        echo "✓ Table waf_logs dropped\n";
    }
}
