<?php
/**
 * Migration: Create blog_post_tags table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102213
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogPostTagsTable_2025_12_11_102213
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
  `tag_id` int(10) unsigned NOT NULL COMMENT 'ID de la etiqueta',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_post_tag` (`post_id`, `tag_id`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_tag_id` (`tag_id`),
  KEY `idx_blog_post_tags_post` (`post_id`),
  KEY `idx_blog_post_tags_tag` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_post_tags (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (post_id, tag_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_post_tags_idx_post_id ON blog_post_tags(post_id)");
            $pdo->exec("CREATE INDEX blog_post_tags_idx_tag_id ON blog_post_tags(tag_id)");
            $pdo->exec("CREATE INDEX blog_post_tags_idx_blog_post_tags_post ON blog_post_tags(post_id)");
            $pdo->exec("CREATE INDEX blog_post_tags_idx_blog_post_tags_tag ON blog_post_tags(tag_id)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_post_tags.post_id IS 'ID del post'");
            $pdo->exec("COMMENT ON COLUMN blog_post_tags.tag_id IS 'ID de la etiqueta'");
        }

        echo "✓ Table blog_post_tags created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_post_tags`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_post_tags");
        }

        echo "✓ Table blog_post_tags dropped\n";
    }
}
