<?php
/**
 * Migration: Create ai_providers table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102213
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAiProvidersTable_2025_12_11_102213
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `ai_providers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `api_key` varchar(255) DEFAULT NULL,
  `endpoint` varchar(255) DEFAULT NULL,
  `provider_type` enum('openai','claude','gemini','other') NOT NULL DEFAULT 'openai',
  `model` varchar(100) DEFAULT 'gpt-4',
  `temperature` float DEFAULT '0.7',
  `max_tokens` int(11) DEFAULT '1000',
  `active` tinyint(1) DEFAULT '0',
  `system_wide` tinyint(1) DEFAULT '0',
  `tenant_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE ai_providers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  api_key VARCHAR(255),
  endpoint VARCHAR(255),
  provider_type VARCHAR(20) NOT NULL DEFAULT 'openai',
  model VARCHAR(100) DEFAULT 'gpt-4',
  temperature TEXT DEFAULT '0.7',
  max_tokens INTEGER DEFAULT '1000',
  active SMALLINT DEFAULT '0',
  system_wide SMALLINT DEFAULT '0',
  tenant_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (provider_type IN ('openai', 'claude', 'gemini', 'other')),
  UNIQUE (name, tenant_id)
)
            ");
        }

        echo "✓ Table ai_providers created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `ai_providers`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS ai_providers");
        }

        echo "✓ Table ai_providers dropped\n";
    }
}
