<?php
/**
 * Migration: Create superadmin_plugin_logs table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102214
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginLogsTable_2025_12_11_102214
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plugin_id` int(11) DEFAULT NULL COMMENT 'ID del plugin (NULL si es del sistema)',
  `action` varchar(100) NOT NULL COMMENT 'Acción realizada',
  `message` text NOT NULL COMMENT 'Mensaje del log',
  `level` enum('info','warning','error','debug') DEFAULT 'info' COMMENT 'Nivel del log',
  `data` text DEFAULT NULL COMMENT 'Datos adicionales (JSON)',
  `user_id` int(11) DEFAULT NULL COMMENT 'ID del usuario que realizó la acción',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `level` (`level`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE superadmin_plugin_logs (
  id SERIAL PRIMARY KEY,
  plugin_id INTEGER,
  "action" VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,
  "level" VARCHAR(20) DEFAULT 'info',
  "data" TEXT,
  user_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK ("level" IN ('info', 'warning', 'error', 'debug'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX superadmin_plugin_logs_plugin_id ON superadmin_plugin_logs(plugin_id)");
            $pdo->exec("CREATE INDEX superadmin_plugin_logs_level ON superadmin_plugin_logs("level")");
            $pdo->exec("CREATE INDEX superadmin_plugin_logs_created_at ON superadmin_plugin_logs(created_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_logs.plugin_id IS 'ID del plugin (NULL si es del sistema)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_logs."action" IS 'Acción realizada'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_logs.message IS 'Mensaje del log'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_logs."level" IS 'Nivel del log'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_logs."data" IS 'Datos adicionales (JSON)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_logs.user_id IS 'ID del usuario que realizó la acción'");
        }

        echo "✓ Table superadmin_plugin_logs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_logs`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS superadmin_plugin_logs");
        }

        echo "✓ Table superadmin_plugin_logs dropped\n";
    }
}
