<?php
/**
 * Migration: Create admins table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102305
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAdminsTable_2025_12_11_102305
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `two_factor_enabled` tinyint(1) DEFAULT '0',
  `two_factor_secret` varchar(64) DEFAULT NULL,
  `two_factor_recovery_codes` text DEFAULT NULL,
  `two_factor_enabled_at` datetime DEFAULT NULL,
  `two_factor_last_used_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_email_tenant` (`email`, `tenant_id`),
  KEY `idx_admins_tenant` (`tenant_id`),
  KEY `idx_admins_email` (`email`),
  KEY `idx_admins_2fa` (`two_factor_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE admins (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  avatar VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  two_factor_enabled SMALLINT DEFAULT '0',
  two_factor_secret VARCHAR(64),
  two_factor_recovery_codes TEXT,
  two_factor_enabled_at TIMESTAMP,
  two_factor_last_used_at TIMESTAMP,
  UNIQUE (email)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX admins_idx_email_tenant ON admins(email, tenant_id)");
            $pdo->exec("CREATE INDEX admins_idx_admins_tenant ON admins(tenant_id)");
            $pdo->exec("CREATE INDEX admins_idx_admins_email ON admins(email)");
            $pdo->exec("CREATE INDEX admins_idx_admins_2fa ON admins(two_factor_enabled)");
        }

        echo "✓ Table admins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `admins`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS admins");
        }

        echo "✓ Table admins dropped\n";
    }
}
