<?php
/**
 * Migration: Create blog_posts table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102305
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogPostsTable_2025_12_11_102305
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para posts globales)',
  `user_id` int(11) NOT NULL COMMENT 'ID del autor',
  `user_type` enum('superadmin','admin','user') NOT NULL DEFAULT 'admin' COMMENT 'Tipo de usuario autor',
  `title` varchar(500) NOT NULL COMMENT 'Título del post',
  `slug` varchar(600) NOT NULL COMMENT 'URL amigable',
  `excerpt` text DEFAULT NULL COMMENT 'Resumen o extracto del post',
  `content` longtext NOT NULL COMMENT 'Contenido completo del post',
  `featured_image` varchar(500) DEFAULT NULL COMMENT 'Imagen destacada',
  `hide_featured_image` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Ocultar imagen destacada en vistas públicas',
  `template` varchar(100) DEFAULT 'single',
  `status` enum('draft','published','trash') DEFAULT 'draft',
  `visibility` enum('public','private','password') NOT NULL DEFAULT 'public' COMMENT 'Visibilidad del post',
  `password` varchar(255) DEFAULT NULL COMMENT 'Contraseña si visibility=password',
  `published_at` datetime DEFAULT NULL COMMENT 'Fecha de publicación',
  `base_locale` varchar(10) NOT NULL DEFAULT 'es' COMMENT 'Idioma base del post',
  `allow_comments` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Permitir comentarios',
  `comment_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Contador de comentarios',
  `view_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Contador de vistas',
  `featured` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Post destacado',
  `seo_title` varchar(500) DEFAULT NULL COMMENT 'Título para SEO',
  `seo_description` text DEFAULT NULL COMMENT 'Descripción para SEO',
  `seo_keywords` text DEFAULT NULL COMMENT 'Palabras clave',
  `seo_image` varchar(500) DEFAULT NULL COMMENT 'Imagen para redes sociales',
  `canonical_url` varchar(500) DEFAULT NULL COMMENT 'URL canónica',
  `robots_directive` varchar(100) DEFAULT 'index,follow' COMMENT 'Directivas para robots',
  `twitter_title` varchar(500) DEFAULT NULL COMMENT 'Título para Twitter Card',
  `twitter_description` text DEFAULT NULL COMMENT 'Descripción para Twitter Card',
  `twitter_image` varchar(500) DEFAULT NULL COMMENT 'Imagen para Twitter Card',
  `show_hero` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Mostrar sección hero',
  `hero_image` varchar(500) DEFAULT NULL COMMENT 'Imagen de hero',
  `hero_title` varchar(500) DEFAULT NULL COMMENT 'Título alternativo para hero',
  `hero_content` text DEFAULT NULL COMMENT 'Contenido del hero',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL COMMENT 'Fecha y hora de eliminación lógica',
  `deleted_by` int(11) DEFAULT NULL COMMENT 'ID del usuario que eliminó el registro',
  `revision_count` int(11) DEFAULT '0' COMMENT 'Contador de revisiones (cache)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_slug` (`tenant_id`, `slug`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_type` (`user_type`),
  KEY `idx_slug` (`slug`),
  KEY `idx_status` (`status`),
  KEY `idx_visibility` (`visibility`),
  KEY `idx_published_at` (`published_at`),
  KEY `idx_featured` (`featured`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_blog_posts_deleted_at` (`deleted_at`),
  KEY `idx_blog_posts_tenant` (`tenant_id`),
  KEY `idx_blog_posts_status` (`status`),
  KEY `idx_blog_posts_published` (`published_at`),
  KEY `idx_blog_posts_slug` (`slug`),
  KEY `idx_blog_posts_tenant_status` (`tenant_id`, `status`),
  KEY `idx_blog_posts_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_posts (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  user_id INTEGER NOT NULL,
  user_type VARCHAR(20) NOT NULL DEFAULT 'admin',
  title VARCHAR(500) NOT NULL,
  slug VARCHAR(600) NOT NULL,
  excerpt TEXT,
  content TEXT NOT NULL,
  featured_image VARCHAR(500),
  hide_featured_image SMALLINT NOT NULL DEFAULT '0',
  template VARCHAR(100) DEFAULT 'single',
  status VARCHAR(20) DEFAULT 'draft',
  visibility VARCHAR(20) NOT NULL DEFAULT 'public',
  password VARCHAR(255),
  published_at TIMESTAMP,
  base_locale VARCHAR(10) NOT NULL DEFAULT 'es',
  allow_comments SMALLINT NOT NULL DEFAULT '1',
  comment_count INTEGER NOT NULL DEFAULT '0',
  view_count INTEGER NOT NULL DEFAULT '0',
  featured SMALLINT NOT NULL DEFAULT '0',
  seo_title VARCHAR(500),
  seo_description TEXT,
  seo_keywords TEXT,
  seo_image VARCHAR(500),
  canonical_url VARCHAR(500),
  robots_directive VARCHAR(100) DEFAULT 'index,follow',
  twitter_title VARCHAR(500),
  twitter_description TEXT,
  twitter_image VARCHAR(500),
  show_hero SMALLINT NOT NULL DEFAULT '0',
  hero_image VARCHAR(500),
  hero_title VARCHAR(500),
  hero_content TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  deleted_by INTEGER,
  revision_count INTEGER DEFAULT '0',
  CHECK (user_type IN ('superadmin', 'admin', 'user')),
  CHECK (status IN ('draft', 'published', 'trash')),
  CHECK (visibility IN ('public', 'private', 'password')),
  UNIQUE (tenant_id, slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_posts_idx_tenant_id ON blog_posts(tenant_id)");
            $pdo->exec("CREATE INDEX blog_posts_idx_user_id ON blog_posts(user_id)");
            $pdo->exec("CREATE INDEX blog_posts_idx_user_type ON blog_posts(user_type)");
            $pdo->exec("CREATE INDEX blog_posts_idx_slug ON blog_posts(slug)");
            $pdo->exec("CREATE INDEX blog_posts_idx_status ON blog_posts(status)");
            $pdo->exec("CREATE INDEX blog_posts_idx_visibility ON blog_posts(visibility)");
            $pdo->exec("CREATE INDEX blog_posts_idx_published_at ON blog_posts(published_at)");
            $pdo->exec("CREATE INDEX blog_posts_idx_featured ON blog_posts(featured)");
            $pdo->exec("CREATE INDEX blog_posts_idx_created_at ON blog_posts(created_at)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_deleted_at ON blog_posts(deleted_at)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_tenant ON blog_posts(tenant_id)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_status ON blog_posts(status)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_published ON blog_posts(published_at)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_slug ON blog_posts(slug)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_tenant_status ON blog_posts(tenant_id, status)");
            $pdo->exec("CREATE INDEX blog_posts_idx_blog_posts_deleted ON blog_posts(deleted_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_posts.tenant_id IS 'ID del tenant (NULL para posts globales)'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.user_id IS 'ID del autor'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.user_type IS 'Tipo de usuario autor'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.title IS 'Título del post'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.slug IS 'URL amigable'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.excerpt IS 'Resumen o extracto del post'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.content IS 'Contenido completo del post'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.featured_image IS 'Imagen destacada'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.hide_featured_image IS 'Ocultar imagen destacada en vistas públicas'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.visibility IS 'Visibilidad del post'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.password IS 'Contraseña si visibility=password'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.published_at IS 'Fecha de publicación'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.base_locale IS 'Idioma base del post'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.allow_comments IS 'Permitir comentarios'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.comment_count IS 'Contador de comentarios'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.view_count IS 'Contador de vistas'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.featured IS 'Post destacado'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.seo_title IS 'Título para SEO'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.seo_description IS 'Descripción para SEO'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.seo_keywords IS 'Palabras clave'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.seo_image IS 'Imagen para redes sociales'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.canonical_url IS 'URL canónica'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.robots_directive IS 'Directivas para robots'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.twitter_title IS 'Título para Twitter Card'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.twitter_description IS 'Descripción para Twitter Card'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.twitter_image IS 'Imagen para Twitter Card'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.show_hero IS 'Mostrar sección hero'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.hero_image IS 'Imagen de hero'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.hero_title IS 'Título alternativo para hero'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.hero_content IS 'Contenido del hero'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.deleted_at IS 'Fecha y hora de eliminación lógica'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.deleted_by IS 'ID del usuario que eliminó el registro'");
            $pdo->exec("COMMENT ON COLUMN blog_posts.revision_count IS 'Contador de revisiones (cache)'");
        }

        echo "✓ Table blog_posts created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_posts`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_posts");
        }

        echo "✓ Table blog_posts dropped\n";
    }
}
