<?php
/**
 * Migration: Create admin_activity table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102305
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAdminActivityTable_2025_12_11_102305
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admin_activity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `last_active` datetime NOT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_admin_activity` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE admin_activity (
  id SERIAL PRIMARY KEY,
  admin_id INTEGER NOT NULL,
  tenant_id INTEGER,
  last_active TIMESTAMP NOT NULL,
  ip VARCHAR(45),
  user_agent VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (admin_id)
)
            ");
        }

        echo "✓ Table admin_activity created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `admin_activity`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS admin_activity");
        }

        echo "✓ Table admin_activity dropped\n";
    }
}
