<?php
/**
 * Migration: Create themes table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102306
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateThemesTable_2025_12_11_102306
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `themes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '0',
  `installed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tenant_id` int(11) DEFAULT NULL,
  `config` longtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE themes (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100),
  active SMALLINT DEFAULT '0',
  installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenant_id INTEGER,
  config TEXT
)
            ");
        }

        echo "✓ Table themes created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `themes`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS themes");
        }

        echo "✓ Table themes dropped\n";
    }
}
