<?php
/**
 * Migration: Create superadmin_plugin_logs table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginLogsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_logs` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `plugin_id` int(11) DEFAULT NULL COMMENT 'ID del plugin (NULL si es del sistema)',
                  `action` varchar(100) NOT NULL COMMENT 'Acción realizada',
                  `message` text NOT NULL COMMENT 'Mensaje del log',
                  `level` enum('info','warning','error','debug') DEFAULT 'info' COMMENT 'Nivel del log',
                  `data` text DEFAULT NULL COMMENT 'Datos adicionales (JSON)',
                  `user_id` int(11) DEFAULT NULL COMMENT 'ID del usuario que realizó la acción',
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `plugin_id` (`plugin_id`),
                  KEY `level` (`level`),
                  KEY `created_at` (`created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Registro de actividad de plugins'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table superadmin_plugin_logs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_logs`");
        echo "✓ Table superadmin_plugin_logs dropped\n";
    }
}
