<?php
/**
 * Migration: Create widget_instances table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateWidgetInstancesTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `widget_instances` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(10) unsigned DEFAULT NULL,
                  `theme_slug` varchar(50) NOT NULL,
                  `area_slug` varchar(50) NOT NULL,
                  `widget_slug` varchar(50) NOT NULL,
                  `position` int(10) unsigned NOT NULL DEFAULT 0,
                  `config` text DEFAULT NULL,
                  `created_at` timestamp NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_widget_instance` (`tenant_id`,`theme_slug`,`area_slug`,`position`),
                  KEY `idx_widget_instance_tenant` (`tenant_id`),
                  KEY `idx_widget_instance_area` (`theme_slug`,`area_slug`),
                  KEY `idx_widget_instance_lookup` (`tenant_id`,`theme_slug`,`area_slug`,`position`)
                ) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table widget_instances created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `widget_instances`");
        echo "✓ Table widget_instances dropped\n";
    }
}
