<?php
/**
 * Migration: Add 'custom' plan to tenants table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025-12-21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This migration adds 'custom' as a valid plan type for tenants
 * with custom domains (domain linking via nameserver change).
 */

use Screenart\Musedock\Database;

class AddCustomPlanToTenants_2025_12_21_172000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            // PostgreSQL: Check if 'custom' already exists in the enum
            $checkStmt = $pdo->query("
                SELECT EXISTS (
                    SELECT 1 FROM pg_enum
                    WHERE enumlabel = 'custom'
                    AND enumtypid = (
                        SELECT atttypid FROM pg_attribute
                        WHERE attrelid = 'tenants'::regclass
                        AND attname = 'plan'
                    )
                ) as exists
            ");
            $exists = $checkStmt->fetch(\PDO::FETCH_ASSOC)['exists'] ?? false;

            if (!$exists || $exists === 'f') {
                // Add 'custom' to the enum type
                $pdo->exec("ALTER TYPE tenants_plan_check ADD VALUE IF NOT EXISTS 'custom'");
                echo "✓ Added 'custom' to PostgreSQL plan enum\n";
            } else {
                echo "✓ 'custom' already exists in PostgreSQL plan enum\n";
            }
        } else {
            // MySQL/MariaDB: Modify the ENUM column
            // First check current enum values
            $stmt = $pdo->query("SHOW COLUMNS FROM tenants WHERE Field = 'plan'");
            $column = $stmt->fetch(\PDO::FETCH_ASSOC);

            if ($column && strpos($column['Type'], 'custom') === false) {
                // Add 'custom' to the enum
                $pdo->exec("
                    ALTER TABLE tenants
                    MODIFY COLUMN plan ENUM('free', 'starter', 'business', 'custom') NOT NULL DEFAULT 'free'
                ");
                echo "✓ Added 'custom' to MySQL plan enum\n";
            } else {
                echo "✓ 'custom' already exists in MySQL plan enum\n";
            }
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            // PostgreSQL: Cannot easily remove enum values, but we can update existing rows
            $pdo->exec("UPDATE tenants SET plan = 'business' WHERE plan = 'custom'");
            echo "✓ Updated 'custom' plans to 'business' (enum value remains but unused)\n";
        } else {
            // MySQL: First update any 'custom' plans to 'business'
            $pdo->exec("UPDATE tenants SET plan = 'business' WHERE plan = 'custom'");

            // Then remove 'custom' from enum
            $pdo->exec("
                ALTER TABLE tenants
                MODIFY COLUMN plan ENUM('free', 'starter', 'business') NOT NULL DEFAULT 'free'
            ");
            echo "✓ Removed 'custom' from MySQL plan enum\n";
        }
    }
}
