<?php
/**
 * Migration: Create theme_options table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateThemeOptionsTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `theme_options` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(10) unsigned DEFAULT NULL,
  `theme_slug` varchar(50) NOT NULL,
  `value` longtext NOT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_theme_tenant` (`theme_slug`, `tenant_id`),
  UNIQUE KEY `unique_theme_per_tenant` (`tenant_id`, `theme_slug`),
  KEY `idx_theme_options_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE theme_options (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  theme_slug VARCHAR(50) NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (theme_slug, tenant_id),
  UNIQUE (tenant_id, theme_slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX theme_options_idx_theme_options_tenant_id ON theme_options(tenant_id)");
        }

        echo "✓ Table theme_options created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `theme_options`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS theme_options");
        }

        echo "✓ Table theme_options dropped\n";
    }
}
