<?php
/**
 * Migration: Create domain_orders table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025-12-21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This table tracks domain registration orders through OpenProvider.
 */

use Screenart\Musedock\Database;

class CreateDomainOrdersTable_2025_12_21_200000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS domain_orders (
                    id SERIAL PRIMARY KEY,
                    customer_id INT NOT NULL,
                    tenant_id INT NULL,

                    -- Domain info
                    domain VARCHAR(255) NOT NULL,
                    extension VARCHAR(20) NOT NULL,

                    -- OpenProvider
                    openprovider_domain_id INT NULL,
                    openprovider_order_id INT NULL,
                    openprovider_contact_handle VARCHAR(50) NULL,

                    -- Pricing
                    price_currency VARCHAR(3) DEFAULT 'EUR',
                    price_amount DECIMAL(10,2) NOT NULL,
                    period INT DEFAULT 1,

                    -- Status
                    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'registered', 'failed', 'cancelled')),
                    error_message TEXT NULL,

                    -- Cloudflare
                    cloudflare_zone_id VARCHAR(255) NULL,
                    cloudflare_configured SMALLINT DEFAULT 0,

                    -- Timestamps
                    registered_at TIMESTAMP NULL,
                    expires_at TIMESTAMP NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                    CONSTRAINT fk_domain_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
                    CONSTRAINT fk_domain_orders_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL
                )
            ");

            // Indexes
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_orders_domain ON domain_orders(domain)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_orders_status ON domain_orders(status)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_orders_customer ON domain_orders(customer_id)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_orders_tenant ON domain_orders(tenant_id)");

            // Trigger for updated_at
            $pdo->exec("
                CREATE OR REPLACE FUNCTION update_domain_orders_updated_at()
                RETURNS TRIGGER AS \$\$
                BEGIN
                    NEW.updated_at = CURRENT_TIMESTAMP;
                    RETURN NEW;
                END;
                \$\$ LANGUAGE plpgsql
            ");

            $pdo->exec("
                DROP TRIGGER IF EXISTS trigger_domain_orders_updated_at ON domain_orders
            ");

            $pdo->exec("
                CREATE TRIGGER trigger_domain_orders_updated_at
                BEFORE UPDATE ON domain_orders
                FOR EACH ROW
                EXECUTE FUNCTION update_domain_orders_updated_at()
            ");

            echo "✓ Created domain_orders table (PostgreSQL)\n";

        } else {
            // MySQL/MariaDB
            // Note: customer_id is INT UNSIGNED to match customers.id
            // tenant_id is INT (signed) to match tenants.id which is int(11)
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS domain_orders (
                    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    customer_id INT UNSIGNED NOT NULL,
                    tenant_id INT NULL,

                    -- Domain info
                    domain VARCHAR(255) NOT NULL,
                    extension VARCHAR(20) NOT NULL,

                    -- OpenProvider
                    openprovider_domain_id INT NULL,
                    openprovider_order_id INT NULL,
                    openprovider_contact_handle VARCHAR(50) NULL,

                    -- Pricing
                    price_currency VARCHAR(3) DEFAULT 'EUR',
                    price_amount DECIMAL(10,2) NOT NULL,
                    period INT DEFAULT 1,

                    -- Status
                    status ENUM('pending', 'processing', 'registered', 'failed', 'cancelled') DEFAULT 'pending',
                    error_message TEXT NULL,

                    -- Cloudflare
                    cloudflare_zone_id VARCHAR(255) NULL,
                    cloudflare_configured TINYINT(1) DEFAULT 0,

                    -- Timestamps
                    registered_at TIMESTAMP NULL,
                    expires_at TIMESTAMP NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                    -- Foreign keys
                    CONSTRAINT fk_domain_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
                    CONSTRAINT fk_domain_orders_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL,

                    -- Indexes
                    INDEX idx_domain_orders_domain (domain),
                    INDEX idx_domain_orders_status (status),
                    INDEX idx_domain_orders_customer (customer_id),
                    INDEX idx_domain_orders_tenant (tenant_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");

            echo "✓ Created domain_orders table (MySQL)\n";
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            $pdo->exec("DROP TRIGGER IF EXISTS trigger_domain_orders_updated_at ON domain_orders");
            $pdo->exec("DROP FUNCTION IF EXISTS update_domain_orders_updated_at()");
        }

        $pdo->exec("DROP TABLE IF EXISTS domain_orders");
        echo "✓ Dropped domain_orders table\n";
    }
}
