<?php
/**
 * Migration: Create admin_tenant_menus table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateAdminTenantMenusTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admin_tenant_menus` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) NOT NULL,
                  `parent_id` int(11) DEFAULT NULL,
                  `title` varchar(255) NOT NULL,
                  `slug` varchar(255) NOT NULL,
                  `url` varchar(500) NOT NULL,
                  `icon` varchar(100) DEFAULT NULL,
                  `icon_type` enum('bi','fas','far','fal') DEFAULT 'bi',
                  `order_position` int(11) DEFAULT 0,
                  `permission` varchar(255) DEFAULT NULL,
                  `is_active` tinyint(1) DEFAULT 1,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_slug` (`tenant_id`,`slug`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_parent_id` (`parent_id`),
                  KEY `idx_is_active` (`is_active`),
                  CONSTRAINT `admin_tenant_menus_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `admin_tenant_menus` (`id`) ON DELETE CASCADE,
                  CONSTRAINT `admin_tenant_menus_ibfk_2` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table admin_tenant_menus created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `admin_tenant_menus`");
        echo "✓ Table admin_tenant_menus dropped\n";
    }
}
