<?php
/**
 * Migration: Create customer_tenant_credentials table
 * Generated by MuseDock Migration System
 * Generated at: 2025_12_22_130000
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * Esta tabla guarda la relación entre customers y los admins de sus tenants
 * Permite al customer ver y gestionar las credenciales de acceso a cada tenant
 */

use Screenart\Musedock\Database;

class CreateCustomerTenantCredentialsTable_2025_12_22_130000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
        $isPostgres = ($driver === 'pgsql');

        // Verificar si la tabla ya existe
        if ($isPostgres) {
            $checkSql = "SELECT to_regclass('public.customer_tenant_credentials')";
            $result = $pdo->query($checkSql)->fetchColumn();
            if ($result) {
                echo "✓ Table customer_tenant_credentials already exists, skipping\n";
                return;
            }
        } else {
            $checkSql = "SHOW TABLES LIKE 'customer_tenant_credentials'";
            $result = $pdo->query($checkSql)->fetch();
            if ($result) {
                echo "✓ Table customer_tenant_credentials already exists, skipping\n";
                return;
            }
        }

        if ($isPostgres) {
            $pdo->exec("
                CREATE TABLE customer_tenant_credentials (
                    id SERIAL PRIMARY KEY,
                    customer_id INTEGER NOT NULL,
                    tenant_id INTEGER NOT NULL,
                    admin_id INTEGER NOT NULL,
                    admin_email VARCHAR(255) NOT NULL,
                    admin_password_hash VARCHAR(255) NOT NULL,
                    initial_password VARCHAR(100) NULL,
                    password_changed BOOLEAN DEFAULT FALSE,
                    last_password_change TIMESTAMP NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(customer_id, tenant_id)
                )
            ");

            // Crear índices
            $pdo->exec("CREATE INDEX idx_ctc_customer ON customer_tenant_credentials(customer_id)");
            $pdo->exec("CREATE INDEX idx_ctc_tenant ON customer_tenant_credentials(tenant_id)");
            $pdo->exec("CREATE INDEX idx_ctc_admin ON customer_tenant_credentials(admin_id)");

            // Comentarios
            $pdo->exec("COMMENT ON TABLE customer_tenant_credentials IS 'Relaciona customers con los admins de sus tenants'");
            $pdo->exec("COMMENT ON COLUMN customer_tenant_credentials.initial_password IS 'Password inicial en texto plano (se borra tras primer login)'");

        } else {
            // MySQL/MariaDB
            $pdo->exec("
                CREATE TABLE customer_tenant_credentials (
                    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    customer_id INT UNSIGNED NOT NULL COMMENT 'FK a customers.id',
                    tenant_id INT UNSIGNED NOT NULL COMMENT 'FK a tenants.id',
                    admin_id INT UNSIGNED NOT NULL COMMENT 'FK a admins.id',
                    admin_email VARCHAR(255) NOT NULL COMMENT 'Email del admin del tenant',
                    admin_password_hash VARCHAR(255) NOT NULL COMMENT 'Hash del password actual',
                    initial_password VARCHAR(100) NULL COMMENT 'Password inicial (se borra tras primer cambio)',
                    password_changed TINYINT(1) DEFAULT 0 COMMENT 'Si el customer ya cambió el password',
                    last_password_change TIMESTAMP NULL COMMENT 'Última vez que se cambió el password',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    UNIQUE KEY uk_customer_tenant (customer_id, tenant_id),
                    INDEX idx_customer (customer_id),
                    INDEX idx_tenant (tenant_id),
                    INDEX idx_admin (admin_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
                COMMENT='Relaciona customers con los admins de sus tenants'
            ");
        }

        echo "✓ Table customer_tenant_credentials created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `customer_tenant_credentials`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS customer_tenant_credentials");
        }

        echo "✓ Table customer_tenant_credentials dropped\n";
    }
}
