<?php
/**
 * Migration: Create tenant_modules table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateTenantModulesTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_modules` (
                  `tenant_id` int(11) NOT NULL,
                  `module_id` int(11) NOT NULL,
                  `enabled` tinyint(1) DEFAULT 1,
                  `installed_at` timestamp NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`tenant_id`,`module_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table tenant_modules created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `tenant_modules`");
        echo "✓ Table tenant_modules dropped\n";
    }
}
