<?php
/**
 * Migration: Create gallery_settings table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_091120
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateGallerySettingsTable_2025_12_11_091120
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `gallery_settings` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) unsigned DEFAULT NULL COMMENT 'NULL = configuración global',
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `setting_type` enum('string','int','bool','json','array') DEFAULT 'string',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_setting_tenant` (`setting_key`, `tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE gallery_settings (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  setting_key VARCHAR(100) NOT NULL,
  setting_value TEXT,
  setting_type VARCHAR(20) DEFAULT 'string',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (setting_type IN ('string', 'int', 'bool', 'json', 'array')),
  UNIQUE (setting_key, tenant_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX idx_tenant_id ON gallery_settings(tenant_id)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN gallery_settings.tenant_id IS 'NULL = configuración global'");
        }

        echo "✓ Table gallery_settings created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `gallery_settings`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS gallery_settings");
        }

        echo "✓ Table gallery_settings dropped\n";
    }
}
