<?php
/**
 * Migration: Create custom_form_fields table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateCustomFormFieldsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `custom_form_fields` (
                  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                  `form_id` int(11) unsigned NOT NULL,
                  `field_type` varchar(50) NOT NULL COMMENT 'text, email, textarea, select, etc.',
                  `field_name` varchar(100) NOT NULL COMMENT 'Nombre interno del campo',
                  `field_label` varchar(255) NOT NULL COMMENT 'Etiqueta visible',
                  `placeholder` varchar(255) DEFAULT NULL,
                  `default_value` text DEFAULT NULL,
                  `help_text` varchar(500) DEFAULT NULL COMMENT 'Texto de ayuda bajo el campo',
                  `options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Opciones para select, radio, checkbox_group' CHECK (json_valid(`options`)),
                  `validation_rules` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Reglas de validación' CHECK (json_valid(`validation_rules`)),
                  `is_required` tinyint(1) DEFAULT 0,
                  `min_length` int(11) DEFAULT NULL,
                  `max_length` int(11) DEFAULT NULL,
                  `min_value` decimal(15,2) DEFAULT NULL,
                  `max_value` decimal(15,2) DEFAULT NULL,
                  `pattern` varchar(500) DEFAULT NULL COMMENT 'Regex para validación',
                  `error_message` varchar(500) DEFAULT NULL COMMENT 'Mensaje de error personalizado',
                  `field_class` varchar(255) DEFAULT NULL COMMENT 'Clases CSS adicionales',
                  `wrapper_class` varchar(255) DEFAULT NULL COMMENT 'Clases CSS del contenedor',
                  `width` varchar(20) DEFAULT 'full' COMMENT 'full, half, third, quarter',
                  `conditional_logic` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Lógica condicional' CHECK (json_valid(`conditional_logic`)),
                  `sort_order` int(11) DEFAULT 0,
                  `is_active` tinyint(1) DEFAULT 1,
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_field_form` (`form_id`,`field_name`),
                  KEY `idx_form_id` (`form_id`),
                  KEY `idx_sort_order` (`sort_order`),
                  KEY `idx_field_type` (`field_type`),
                  CONSTRAINT `fk_form_fields_form` FOREIGN KEY (`form_id`) REFERENCES `custom_forms` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table custom_form_fields created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `custom_form_fields`");
        echo "✓ Table custom_form_fields dropped\n";
    }
}
