<?php
/**
 * Migration: Create super_admins table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_110144
 */

use Screenart\Musedock\Database;

class CreateSuperAdminsTable_2025_12_08_110144
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `super_admins` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `name` varchar(100) DEFAULT NULL,
                  `email` varchar(255) NOT NULL,
                  `password` varchar(255) NOT NULL,
                  `avatar` varchar(255) DEFAULT NULL,
                  `role` varchar(50) DEFAULT 'superadmin',
                  `is_root` tinyint(1) DEFAULT 0,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT NULL,
                  `two_factor_enabled` tinyint(1) DEFAULT 0,
                  `two_factor_secret` varchar(64) DEFAULT NULL,
                  `two_factor_recovery_codes` text DEFAULT NULL,
                  `two_factor_enabled_at` datetime DEFAULT NULL,
                  `two_factor_last_used_at` datetime DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `email` (`email`),
                  KEY `idx_email` (`email`),
                  KEY `idx_super_admins_2fa` (`two_factor_enabled`),
                  KEY `idx_super_admins_is_root` (`is_root`)
                ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table super_admins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `super_admins`");
        echo "✓ Table super_admins dropped\n";
    }
}
