<?php
/**
 * Migration: Fix include_www column type in PostgreSQL
 * Generated by MuseDock - Customer Registration System
 * Compatible with: PostgreSQL only
 *
 * Convierte include_www de SMALLINT a BOOLEAN para consistencia
 */

use Screenart\Musedock\Database;

class FixIncludeWwwType_2025_01_01_000256
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        // Solo aplicar en PostgreSQL
        if ($driver === 'pgsql') {
            try {
                // Verificar si la columna existe y es SMALLINT
                $stmt = $pdo->query("
                    SELECT data_type
                    FROM information_schema.columns
                    WHERE table_name = 'tenants'
                    AND column_name = 'include_www'
                ");

                $result = $stmt->fetch(PDO::FETCH_ASSOC);

                if ($result && $result['data_type'] === 'smallint') {
                    // Convertir SMALLINT a BOOLEAN
                    // Primero convertir valores: 1 -> true, 0/NULL -> false
                    $pdo->exec("
                        ALTER TABLE tenants
                        ALTER COLUMN include_www TYPE BOOLEAN
                        USING CASE
                            WHEN include_www = 1 THEN TRUE
                            ELSE FALSE
                        END
                    ");

                    echo "✓ Column include_www converted from SMALLINT to BOOLEAN\n";
                } else {
                    echo "⚠ Column include_www is not SMALLINT, skipping conversion\n";
                }
            } catch (\Exception $e) {
                echo "⚠ Error converting include_www: " . $e->getMessage() . "\n";
                // No fallar la migración, solo advertir
            }
        } else {
            echo "⚠ MySQL/MariaDB uses TINYINT(1), no conversion needed\n";
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            try {
                // Revertir a SMALLINT si es necesario
                $pdo->exec("
                    ALTER TABLE tenants
                    ALTER COLUMN include_www TYPE SMALLINT
                    USING CASE
                        WHEN include_www = TRUE THEN 1
                        ELSE 0
                    END
                ");
                echo "✓ Column include_www reverted to SMALLINT\n";
            } catch (\Exception $e) {
                echo "⚠ Error reverting include_www: " . $e->getMessage() . "\n";
            }
        }
    }
}
