<?php
/**
 * Migration: Create permissions table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_091120
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreatePermissionsTable_2025_12_11_091120
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `scope` enum('tenant','global') DEFAULT 'tenant',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_permission_per_tenant` (`tenant_id`, `name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE permissions (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(100),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  category VARCHAR(100),
  tenant_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scope VARCHAR(20) DEFAULT 'tenant',
  CHECK (scope IN ('tenant', 'global')),
  UNIQUE (tenant_id, name)
)
            ");
        }

        echo "✓ Table permissions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `permissions`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS permissions");
        }

        echo "✓ Table permissions dropped\n";
    }
}
