<?php
/**
 * Migration: Create pages table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreatePagesTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `pages` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL,
                  `user_id` int(11) DEFAULT NULL,
                  `user_type` enum('admin','superadmin') DEFAULT 'admin',
                  `base_locale` varchar(5) DEFAULT 'es',
                  `title` varchar(255) NOT NULL,
                  `slug` varchar(255) NOT NULL,
                  `content` text DEFAULT NULL,
                  `seo_title` varchar(255) DEFAULT NULL,
                  `seo_description` text DEFAULT NULL,
                  `seo_keywords` varchar(255) DEFAULT NULL,
                  `seo_image` varchar(255) DEFAULT NULL,
                  `canonical_url` varchar(255) DEFAULT NULL,
                  `robots_directive` varchar(50) DEFAULT 'index,follow',
                  `twitter_title` varchar(255) DEFAULT NULL,
                  `twitter_description` text DEFAULT NULL,
                  `twitter_image` varchar(255) DEFAULT NULL,
                  `status` enum('draft','published','trash') DEFAULT 'draft',
                  `is_homepage` tinyint(1) unsigned NOT NULL DEFAULT 0,
                  `show_slider` tinyint(1) DEFAULT 0 COMMENT 'Indica si se debe mostrar el slider',
                  `slider_image` varchar(255) DEFAULT NULL COMMENT 'Ruta a la imagen del slider',
                  `slider_title` varchar(255) DEFAULT NULL COMMENT 'Título personalizado para el slider',
                  `slider_content` text DEFAULT NULL COMMENT 'Contenido HTML para el slider',
                  `hide_title` tinyint(1) DEFAULT 0 COMMENT 'Ocultar el título H1 en la página',
                  `published_at` datetime DEFAULT NULL,
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  `visibility` enum('public','private','members') NOT NULL DEFAULT 'public',
                  `revision_count` int(11) DEFAULT 0 COMMENT 'Contador de revisiones (cache)',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `slug` (`slug`),
                  KEY `idx_is_homepage` (`is_homepage`)
                ) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table pages created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `pages`");
        echo "✓ Table pages dropped\n";
    }
}
