<?php
/**
 * Migration: Fix permissions unique index to include scope
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This migration:
 * 1. Updates scope ENUM to use 'superadmin' and 'tenant' values
 * 2. Changes unique index from (tenant_id, name) to (tenant_id, slug, scope)
 *    This allows the same permission slug to exist in both superadmin and tenant scopes
 */

use Screenart\Musedock\Database;

class FixPermissionsUniqueIndex_2025_12_21_000001
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            // 1. Modify scope ENUM to use correct values
            $pdo->exec("
                ALTER TABLE `permissions`
                MODIFY COLUMN `scope` enum('superadmin','tenant') DEFAULT 'tenant'
            ");

            // 2. Check if old index exists and drop it
            $stmt = $pdo->query("SHOW INDEX FROM permissions WHERE Key_name = 'unique_permission_per_tenant'");
            if ($stmt->fetch()) {
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
                $pdo->exec("ALTER TABLE `permissions` DROP INDEX `unique_permission_per_tenant`");
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
            }

            // 3. Check if new index doesn't exist and create it
            $stmt = $pdo->query("SHOW INDEX FROM permissions WHERE Key_name = 'unique_permission_scope'");
            if (!$stmt->fetch()) {
                $pdo->exec("
                    ALTER TABLE `permissions`
                    ADD UNIQUE KEY `unique_permission_scope` (`tenant_id`, `slug`, `scope`)
                ");
            }
        } else {
            // PostgreSQL
            // 1. Update scope constraint - first check if it exists
            try {
                $pdo->exec("ALTER TABLE permissions DROP CONSTRAINT IF EXISTS permissions_scope_check");
            } catch (\Exception $e) {
                // Constraint might not exist, continue
            }
            $pdo->exec("ALTER TABLE permissions ADD CONSTRAINT permissions_scope_check CHECK (scope IN ('superadmin', 'tenant'))");

            // 2. Drop old unique constraint if exists
            try {
                $pdo->exec("ALTER TABLE permissions DROP CONSTRAINT IF EXISTS permissions_tenant_id_name_key");
            } catch (\Exception $e) {
                // Constraint might not exist
            }
            try {
                $pdo->exec("ALTER TABLE permissions DROP CONSTRAINT IF EXISTS unique_permission_per_tenant");
            } catch (\Exception $e) {
                // Constraint might not exist
            }

            // 3. Create new unique constraint if not exists
            $stmt = $pdo->query("
                SELECT 1 FROM pg_constraint
                WHERE conname = 'unique_permission_scope'
            ");
            if (!$stmt->fetch()) {
                $pdo->exec("ALTER TABLE permissions ADD CONSTRAINT unique_permission_scope UNIQUE (tenant_id, slug, scope)");
            }
        }

        echo "✓ Permissions unique index updated to include scope\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            // Revert scope ENUM
            $pdo->exec("
                ALTER TABLE `permissions`
                MODIFY COLUMN `scope` enum('tenant','global') DEFAULT 'tenant'
            ");

            // Revert index change
            $stmt = $pdo->query("SHOW INDEX FROM permissions WHERE Key_name = 'unique_permission_scope'");
            if ($stmt->fetch()) {
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
                $pdo->exec("ALTER TABLE `permissions` DROP INDEX `unique_permission_scope`");
                $pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
            }

            $stmt = $pdo->query("SHOW INDEX FROM permissions WHERE Key_name = 'unique_permission_per_tenant'");
            if (!$stmt->fetch()) {
                $pdo->exec("
                    ALTER TABLE `permissions`
                    ADD UNIQUE KEY `unique_permission_per_tenant` (`tenant_id`, `name`)
                ");
            }
        } else {
            // PostgreSQL
            try {
                $pdo->exec("ALTER TABLE permissions DROP CONSTRAINT IF EXISTS permissions_scope_check");
            } catch (\Exception $e) {
                // Ignore
            }
            $pdo->exec("ALTER TABLE permissions ADD CONSTRAINT permissions_scope_check CHECK (scope IN ('tenant', 'global'))");

            try {
                $pdo->exec("ALTER TABLE permissions DROP CONSTRAINT IF EXISTS unique_permission_scope");
            } catch (\Exception $e) {
                // Ignore
            }

            $stmt = $pdo->query("
                SELECT 1 FROM pg_constraint
                WHERE conname = 'permissions_tenant_id_name_key'
            ");
            if (!$stmt->fetch()) {
                $pdo->exec("ALTER TABLE permissions ADD CONSTRAINT permissions_tenant_id_name_key UNIQUE (tenant_id, name)");
            }
        }

        echo "✓ Permissions unique index reverted\n";
    }
}
