<?php
/**
 * Migration: Add is_root_admin column to admins table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_12_120000
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This field distinguishes between the primary admin of a tenant (root)
 * and additional admins created later.
 */

use Screenart\Musedock\Database;

class AddIsRootAdminToAdminsTable_2025_12_12_120000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $this->upMySQL($pdo);
        } else {
            $this->upPostgreSQL($pdo);
        }
    }

    private function upMySQL(PDO $pdo)
    {
        // Check if column already exists
        $stmt = $pdo->query("SHOW COLUMNS FROM `admins` LIKE 'is_root_admin'");
        if ($stmt->fetch()) {
            echo "  Column 'is_root_admin' already exists, skipping...\n";
            return;
        }

        // Add the column
        $pdo->exec("
            ALTER TABLE `admins`
            ADD COLUMN `is_root_admin` TINYINT(1) NOT NULL DEFAULT 0
            AFTER `tenant_id`
        ");

        // Create index
        $pdo->exec("CREATE INDEX `idx_admins_is_root_admin` ON `admins`(`is_root_admin`)");

        // Mark the first admin of each tenant as root
        $pdo->exec("
            UPDATE admins a1
            INNER JOIN (
                SELECT tenant_id, MIN(id) as first_admin_id
                FROM admins
                WHERE tenant_id IS NOT NULL
                GROUP BY tenant_id
            ) a2 ON a1.id = a2.first_admin_id
            SET a1.is_root_admin = 1
        ");

        echo "✓ Column 'is_root_admin' added and existing admins updated.\n";
    }

    private function upPostgreSQL(PDO $pdo)
    {
        // Check if column already exists
        $stmt = $pdo->prepare("
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'admins' AND column_name = 'is_root_admin'
        ");
        $stmt->execute();
        if ($stmt->fetch()) {
            echo "  Column 'is_root_admin' already exists, skipping...\n";
            return;
        }

        // Add the column
        $pdo->exec("ALTER TABLE admins ADD COLUMN is_root_admin SMALLINT NOT NULL DEFAULT 0");

        // Create index
        $pdo->exec("CREATE INDEX idx_admins_is_root_admin ON admins(is_root_admin)");

        // Mark the first admin of each tenant as root
        $pdo->exec("
            UPDATE admins a1
            SET is_root_admin = 1
            FROM (
                SELECT tenant_id, MIN(id) as first_admin_id
                FROM admins
                WHERE tenant_id IS NOT NULL
                GROUP BY tenant_id
            ) a2
            WHERE a1.id = a2.first_admin_id
        ");

        echo "✓ Column 'is_root_admin' added and existing admins updated.\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $this->downMySQL($pdo);
        } else {
            $this->downPostgreSQL($pdo);
        }
    }

    private function downMySQL(PDO $pdo)
    {
        try {
            $pdo->exec("DROP INDEX `idx_admins_is_root_admin` ON `admins`");
        } catch (\Exception $e) {
            // Index might not exist
        }

        $pdo->exec("ALTER TABLE `admins` DROP COLUMN IF EXISTS `is_root_admin`");
        echo "✓ Column 'is_root_admin' removed.\n";
    }

    private function downPostgreSQL(PDO $pdo)
    {
        try {
            $pdo->exec("DROP INDEX IF EXISTS idx_admins_is_root_admin");
        } catch (\Exception $e) {
            // Index might not exist
        }

        $pdo->exec("ALTER TABLE admins DROP COLUMN IF EXISTS is_root_admin");
        echo "✓ Column 'is_root_admin' removed.\n";
    }
}
