<?php
/**
 * Migration: Create site_menu_items table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSiteMenuItemsTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `site_menu_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent` int(11) DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `sort` int(11) DEFAULT '0',
  `depth` int(11) DEFAULT '0',
  `title` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `label` varchar(255) DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `target` varchar(50) DEFAULT NULL,
  `menu_id` int(11) DEFAULT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `page_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `menu_id` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE site_menu_items (
  id SERIAL PRIMARY KEY,
  parent INTEGER,
  link VARCHAR(255),
  sort INTEGER DEFAULT '0',
  depth INTEGER DEFAULT '0',
  title VARCHAR(255),
  name VARCHAR(255),
  label VARCHAR(255),
  slug VARCHAR(255),
  \"type\" VARCHAR(50),
  target VARCHAR(50),
  menu_id INTEGER,
  tenant_id INTEGER,
  page_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX site_menu_items_menu_id ON site_menu_items(menu_id)");
        }

        echo "✓ Table site_menu_items created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `site_menu_items`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS site_menu_items");
        }

        echo "✓ Table site_menu_items dropped\n";
    }
}
