<?php
/**
 * Migration: Create support_tickets table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104034
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSupportTicketsTable_2025_12_11_104034
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `support_tickets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL COMMENT 'ID del tenant',
  `admin_id` int(11) NOT NULL COMMENT 'ID del admin que crea el ticket',
  `assigned_to` int(11) DEFAULT NULL COMMENT 'ID del superadmin asignado',
  `subject` varchar(500) NOT NULL COMMENT 'Asunto del ticket',
  `description` text NOT NULL COMMENT 'Descripción del problema',
  `priority` enum('low','normal','high','urgent') DEFAULT 'normal' COMMENT 'Prioridad',
  `status` enum('open','in_progress','resolved','closed') DEFAULT 'open' COMMENT 'Estado',
  `resolved_at` datetime DEFAULT NULL COMMENT 'Fecha de resolución',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `admin_id` (`admin_id`),
  KEY `assigned_to` (`assigned_to`),
  KEY `status` (`status`),
  KEY `priority` (`priority`),
  KEY `created_at` (`created_at`),
  KEY `idx_tickets_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tickets_assigned` (`assigned_to`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE support_tickets (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  admin_id INTEGER NOT NULL,
  assigned_to INTEGER,
  subject VARCHAR(500) NOT NULL,
  description TEXT NOT NULL,
  priority VARCHAR(20) DEFAULT 'normal',
  status VARCHAR(20) DEFAULT 'open',
  resolved_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  CHECK (status IN ('open', 'in_progress', 'resolved', 'closed'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX support_tickets_tenant_id ON support_tickets(tenant_id)");
            $pdo->exec("CREATE INDEX support_tickets_admin_id ON support_tickets(admin_id)");
            $pdo->exec("CREATE INDEX support_tickets_assigned_to ON support_tickets(assigned_to)");
            $pdo->exec("CREATE INDEX support_tickets_status ON support_tickets(status)");
            $pdo->exec("CREATE INDEX support_tickets_priority ON support_tickets(priority)");
            $pdo->exec("CREATE INDEX support_tickets_created_at ON support_tickets(created_at)");
            $pdo->exec("CREATE INDEX support_tickets_idx_tickets_tenant_status ON support_tickets(tenant_id, status)");
            $pdo->exec("CREATE INDEX support_tickets_idx_tickets_assigned ON support_tickets(assigned_to, status)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN support_tickets.tenant_id IS 'ID del tenant'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.admin_id IS 'ID del admin que crea el ticket'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.assigned_to IS 'ID del superadmin asignado'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.subject IS 'Asunto del ticket'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.description IS 'Descripción del problema'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.priority IS 'Prioridad'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.status IS 'Estado'");
            $pdo->exec("COMMENT ON COLUMN support_tickets.resolved_at IS 'Fecha de resolución'");
        }

        echo "✓ Table support_tickets created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `support_tickets`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS support_tickets");
        }

        echo "✓ Table support_tickets dropped\n";
    }
}
