<?php
/**
 * Migration: Create custom_forms table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateCustomFormsTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `custom_forms` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) unsigned DEFAULT NULL COMMENT 'NULL = formulario global',
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `submit_button_text` varchar(100) DEFAULT 'Enviar',
  `success_message` text DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `redirect_url` varchar(500) DEFAULT NULL COMMENT 'URL de redirección tras envío',
  `email_to` varchar(500) DEFAULT NULL COMMENT 'Emails separados por coma',
  `email_subject` varchar(255) DEFAULT NULL,
  `email_from_name` varchar(100) DEFAULT NULL,
  `email_from_email` varchar(255) DEFAULT NULL,
  `email_reply_to` varchar(255) DEFAULT NULL,
  `send_confirmation_email` tinyint(1) DEFAULT '0',
  `confirmation_email_subject` varchar(255) DEFAULT NULL,
  `confirmation_email_message` text DEFAULT NULL,
  `store_submissions` tinyint(1) DEFAULT '1',
  `enable_recaptcha` tinyint(1) DEFAULT '0',
  `form_class` varchar(255) DEFAULT NULL COMMENT 'Clases CSS adicionales',
  `settings` longtext DEFAULT NULL COMMENT 'Configuración adicional JSON',
  `is_active` tinyint(1) DEFAULT '1',
  `submissions_count` int(11) unsigned DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_slug_tenant` (`slug`, `tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE custom_forms (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  description TEXT,
  submit_button_text VARCHAR(100) DEFAULT 'Enviar',
  success_message TEXT,
  error_message TEXT,
  redirect_url VARCHAR(500),
  email_to VARCHAR(500),
  email_subject VARCHAR(255),
  email_from_name VARCHAR(100),
  email_from_email VARCHAR(255),
  email_reply_to VARCHAR(255),
  send_confirmation_email SMALLINT DEFAULT '0',
  confirmation_email_subject VARCHAR(255),
  confirmation_email_message TEXT,
  store_submissions SMALLINT DEFAULT '1',
  enable_recaptcha SMALLINT DEFAULT '0',
  form_class VARCHAR(255),
  settings TEXT,
  is_active SMALLINT DEFAULT '1',
  submissions_count INTEGER DEFAULT '0',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (slug, tenant_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX custom_forms_idx_tenant_id ON custom_forms(tenant_id)");
            $pdo->exec("CREATE INDEX custom_forms_idx_is_active ON custom_forms(is_active)");
            $pdo->exec("CREATE INDEX custom_forms_idx_created_at ON custom_forms(created_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN custom_forms.tenant_id IS 'NULL = formulario global'");
            $pdo->exec("COMMENT ON COLUMN custom_forms.redirect_url IS 'URL de redirección tras envío'");
            $pdo->exec("COMMENT ON COLUMN custom_forms.email_to IS 'Emails separados por coma'");
            $pdo->exec("COMMENT ON COLUMN custom_forms.form_class IS 'Clases CSS adicionales'");
            $pdo->exec("COMMENT ON COLUMN custom_forms.settings IS 'Configuración adicional JSON'");
        }

        echo "✓ Table custom_forms created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `custom_forms`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS custom_forms");
        }

        echo "✓ Table custom_forms dropped\n";
    }
}
