<?php
/**
 * Migration: Add Cloudflare columns to tenants table
 * Generated by MuseDock - Customer Registration System
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * Añade columnas para gestionar subdominios FREE con Cloudflare
 * Incluye relación con customers y tracking de configuración
 */

use Screenart\Musedock\Database;

class AddCloudflareColumnsToTenants_2025_01_01_000242
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            // Check if columns already exist
            $stmt = $pdo->query("SHOW COLUMNS FROM tenants LIKE 'customer_id'");
            if ($stmt->rowCount() > 0) {
                echo "⚠ Columns already exist, skipping...\n";
                return;
            }

            $pdo->exec("
                ALTER TABLE `tenants`
                    -- Relación con customer
                    ADD COLUMN `customer_id` INT UNSIGNED NULL COMMENT 'FK to customers table',
                    ADD COLUMN `plan` ENUM('free', 'starter', 'business') NOT NULL DEFAULT 'free',

                    -- Cloudflare DNS tracking
                    ADD COLUMN `cloudflare_record_id` VARCHAR(100) NULL COMMENT 'Cloudflare DNS record ID',
                    ADD COLUMN `cloudflare_proxied` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Proxy orange enabled',
                    ADD COLUMN `cloudflare_configured_at` TIMESTAMP NULL,
                    ADD COLUMN `cloudflare_error_log` TEXT NULL COMMENT 'Last Cloudflare error',

                    -- Subdomain identification
                    ADD COLUMN `is_subdomain` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Is .musedock.com subdomain',
                    ADD COLUMN `parent_domain` VARCHAR(255) NULL COMMENT 'musedock.com for FREE subdomains',

                    -- Foreign Key constraint
                    ADD CONSTRAINT `fk_tenants_customer`
                        FOREIGN KEY (`customer_id`)
                        REFERENCES `customers`(`id`)
                        ON DELETE CASCADE,

                    -- CRITICAL INDEX for query performance
                    ADD INDEX `idx_tenants_customer_id` (`customer_id`),
                    ADD INDEX `idx_tenants_plan` (`plan`),
                    ADD INDEX `idx_tenants_is_subdomain` (`is_subdomain`)
            ");
        } else {
            // PostgreSQL - check if columns exist
            $stmt = $pdo->query("
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'tenants' AND column_name = 'customer_id'
            ");
            if ($stmt->rowCount() > 0) {
                echo "⚠ Columns already exist, skipping...\n";
                return;
            }

            // Add columns
            $pdo->exec("
                ALTER TABLE tenants
                    ADD COLUMN IF NOT EXISTS customer_id INT NULL,
                    ADD COLUMN IF NOT EXISTS plan VARCHAR(20) NOT NULL DEFAULT 'free'
                        CHECK (plan IN ('free', 'starter', 'business')),
                    ADD COLUMN IF NOT EXISTS cloudflare_record_id VARCHAR(100) NULL,
                    ADD COLUMN IF NOT EXISTS cloudflare_proxied SMALLINT NOT NULL DEFAULT 1,
                    ADD COLUMN IF NOT EXISTS cloudflare_configured_at TIMESTAMP NULL,
                    ADD COLUMN IF NOT EXISTS cloudflare_error_log TEXT NULL,
                    ADD COLUMN IF NOT EXISTS is_subdomain SMALLINT NOT NULL DEFAULT 0,
                    ADD COLUMN IF NOT EXISTS parent_domain VARCHAR(255) NULL
            ");

            // Add Foreign Key constraint
            $pdo->exec("
                ALTER TABLE tenants
                    ADD CONSTRAINT fk_tenants_customer
                        FOREIGN KEY (customer_id)
                        REFERENCES customers(id)
                        ON DELETE CASCADE
            ");

            // Create indexes for query performance
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_tenants_customer_id ON tenants(customer_id)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_tenants_plan ON tenants(plan)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_tenants_is_subdomain ON tenants(is_subdomain)");
        }

        echo "✓ Cloudflare columns added to tenants table\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                ALTER TABLE `tenants`
                    DROP FOREIGN KEY `fk_tenants_customer`,
                    DROP INDEX `idx_tenants_customer_id`,
                    DROP INDEX `idx_tenants_plan`,
                    DROP INDEX `idx_tenants_is_subdomain`,
                    DROP COLUMN `customer_id`,
                    DROP COLUMN `plan`,
                    DROP COLUMN `cloudflare_record_id`,
                    DROP COLUMN `cloudflare_proxied`,
                    DROP COLUMN `cloudflare_configured_at`,
                    DROP COLUMN `cloudflare_error_log`,
                    DROP COLUMN `is_subdomain`,
                    DROP COLUMN `parent_domain`
            ");
        } else {
            // Drop indexes
            $pdo->exec("DROP INDEX IF EXISTS idx_tenants_customer_id");
            $pdo->exec("DROP INDEX IF EXISTS idx_tenants_plan");
            $pdo->exec("DROP INDEX IF EXISTS idx_tenants_is_subdomain");

            // Drop Foreign Key
            $pdo->exec("ALTER TABLE tenants DROP CONSTRAINT IF EXISTS fk_tenants_customer");

            // Drop columns
            $pdo->exec("
                ALTER TABLE tenants
                    DROP COLUMN IF EXISTS customer_id,
                    DROP COLUMN IF EXISTS plan,
                    DROP COLUMN IF EXISTS cloudflare_record_id,
                    DROP COLUMN IF EXISTS cloudflare_proxied,
                    DROP COLUMN IF EXISTS cloudflare_configured_at,
                    DROP COLUMN IF EXISTS cloudflare_error_log,
                    DROP COLUMN IF EXISTS is_subdomain,
                    DROP COLUMN IF EXISTS parent_domain
            ");
        }

        echo "✓ Cloudflare columns removed from tenants table\n";
    }
}
