<?php
/**
 * Migration: Create super_admin_session_tokens table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateSuperAdminSessionTokensTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `super_admin_session_tokens` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `super_admin_id` int(11) NOT NULL,
                  `token` varchar(64) NOT NULL,
                  `ip` varchar(45) DEFAULT NULL,
                  `user_agent` varchar(255) DEFAULT NULL,
                  `persistent` tinyint(1) DEFAULT 1,
                  `created_at` datetime NOT NULL,
                  `expires_at` datetime NOT NULL,
                  `last_used_at` datetime NOT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `uk_super_admin_token` (`token`),
                  KEY `fk_super_admin_token` (`super_admin_id`),
                  CONSTRAINT `fk_super_admin_token` FOREIGN KEY (`super_admin_id`) REFERENCES `super_admins` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table super_admin_session_tokens created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `super_admin_session_tokens`");
        echo "✓ Table super_admin_session_tokens dropped\n";
    }
}
