<?php
/**
 * Migration: Create tenant_modules table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104034
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateTenantModulesTable_2025_12_11_104034
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_modules` (
  `tenant_id` int(11) NOT NULL,
  `module_id` int(11) NOT NULL,
  `enabled` tinyint(1) DEFAULT '1',
  `installed_at` timestamp DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE tenant_modules (
  tenant_id INTEGER NOT NULL,
  module_id INTEGER NOT NULL,
  enabled SMALLINT DEFAULT '1',
  installed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");
        }

        echo "✓ Table tenant_modules created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `tenant_modules`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS tenant_modules");
        }

        echo "✓ Table tenant_modules dropped\n";
    }
}
