<?php
/**
 * Migration: Create gallery_images table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateGalleryImagesTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `gallery_images` (
                  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                  `gallery_id` int(11) unsigned NOT NULL,
                  `disk` varchar(50) NOT NULL DEFAULT 'local',
                  `public_token` varchar(64) DEFAULT NULL,
                  `file_name` varchar(255) NOT NULL COMMENT 'Nombre original del archivo',
                  `file_path` varchar(500) NOT NULL COMMENT 'Ruta interna del archivo',
                  `file_hash` varchar(64) DEFAULT NULL COMMENT 'Hash SHA256 para verificación',
                  `file_size` int(11) unsigned DEFAULT 0 COMMENT 'Tamaño en bytes',
                  `mime_type` varchar(100) DEFAULT NULL,
                  `image_url` varchar(500) NOT NULL COMMENT 'URL pública permanente',
                  `thumbnail_url` varchar(500) DEFAULT NULL COMMENT 'URL de miniatura',
                  `medium_url` varchar(500) DEFAULT NULL COMMENT 'URL de tamaño medio',
                  `title` varchar(255) DEFAULT NULL,
                  `alt_text` varchar(255) DEFAULT NULL COMMENT 'Texto alternativo para SEO',
                  `caption` text DEFAULT NULL COMMENT 'Descripción de la imagen',
                  `link_url` varchar(500) DEFAULT NULL COMMENT 'URL de enlace opcional',
                  `link_target` enum('_self','_blank') DEFAULT '_self',
                  `width` int(11) unsigned DEFAULT NULL COMMENT 'Ancho original en px',
                  `height` int(11) unsigned DEFAULT NULL COMMENT 'Alto original en px',
                  `sort_order` int(11) DEFAULT 0,
                  `is_active` tinyint(1) DEFAULT 1,
                  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Metadatos EXIF y adicionales' CHECK (json_valid(`metadata`)),
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `idx_gallery_id` (`gallery_id`),
                  KEY `idx_sort_order` (`sort_order`),
                  KEY `idx_is_active` (`is_active`),
                  KEY `idx_file_hash` (`file_hash`),
                  KEY `idx_public_token` (`public_token`),
                  CONSTRAINT `fk_gallery_images_gallery` FOREIGN KEY (`gallery_id`) REFERENCES `image_galleries` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table gallery_images created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `gallery_images`");
        echo "✓ Table gallery_images dropped\n";
    }
}
