<?php
/**
 * Migration: Create react_slides table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateReactSlidesTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `react_slides` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slider_id` int(11) NOT NULL COMMENT 'ID del slider',
  `title` varchar(255) DEFAULT NULL COMMENT 'Título de la diapositiva',
  `subtitle` varchar(255) DEFAULT NULL COMMENT 'Subtítulo',
  `description` text DEFAULT NULL COMMENT 'Descripción',
  `image_url` varchar(500) NOT NULL COMMENT 'URL de la imagen',
  `button_text` varchar(100) DEFAULT NULL COMMENT 'Texto del botón',
  `button_link` varchar(500) DEFAULT NULL COMMENT 'Enlace del botón',
  `button_target` enum('_self','_blank') DEFAULT '_self' COMMENT 'Target del enlace',
  `background_color` varchar(20) DEFAULT NULL COMMENT 'Color de fondo',
  `text_color` varchar(20) DEFAULT '#ffffff' COMMENT 'Color del texto',
  `overlay_opacity` decimal(3,2) DEFAULT '0.30' COMMENT 'Opacidad del overlay (0.00-1.00)',
  `sort_order` int(11) DEFAULT '0' COMMENT 'Orden de visualización',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '1 = Activo, 0 = Inactivo',
  `custom_css` text DEFAULT NULL COMMENT 'CSS personalizado',
  `custom_data` text DEFAULT NULL COMMENT 'Datos personalizados (JSON)',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `slider_id` (`slider_id`),
  KEY `sort_order` (`sort_order`),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE react_slides (
  id SERIAL PRIMARY KEY,
  slider_id INTEGER NOT NULL,
  title VARCHAR(255),
  subtitle VARCHAR(255),
  description TEXT,
  image_url VARCHAR(500) NOT NULL,
  button_text VARCHAR(100),
  button_link VARCHAR(500),
  button_target VARCHAR(20) DEFAULT '_self',
  background_color VARCHAR(20),
  text_color VARCHAR(20) DEFAULT '#ffffff',
  overlay_opacity DECIMAL(3,2) DEFAULT '0.30',
  sort_order INTEGER DEFAULT '0',
  is_active SMALLINT DEFAULT '1',
  custom_css TEXT,
  custom_data TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (button_target IN ('_self', '_blank'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX react_slides_slider_id ON react_slides(slider_id)");
            $pdo->exec("CREATE INDEX react_slides_sort_order ON react_slides(sort_order)");
            $pdo->exec("CREATE INDEX react_slides_is_active ON react_slides(is_active)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN react_slides.slider_id IS 'ID del slider'");
            $pdo->exec("COMMENT ON COLUMN react_slides.title IS 'Título de la diapositiva'");
            $pdo->exec("COMMENT ON COLUMN react_slides.subtitle IS 'Subtítulo'");
            $pdo->exec("COMMENT ON COLUMN react_slides.description IS 'Descripción'");
            $pdo->exec("COMMENT ON COLUMN react_slides.image_url IS 'URL de la imagen'");
            $pdo->exec("COMMENT ON COLUMN react_slides.button_text IS 'Texto del botón'");
            $pdo->exec("COMMENT ON COLUMN react_slides.button_link IS 'Enlace del botón'");
            $pdo->exec("COMMENT ON COLUMN react_slides.button_target IS 'Target del enlace'");
            $pdo->exec("COMMENT ON COLUMN react_slides.background_color IS 'Color de fondo'");
            $pdo->exec("COMMENT ON COLUMN react_slides.text_color IS 'Color del texto'");
            $pdo->exec("COMMENT ON COLUMN react_slides.overlay_opacity IS 'Opacidad del overlay (0.00-1.00)'");
            $pdo->exec("COMMENT ON COLUMN react_slides.sort_order IS 'Orden de visualización'");
            $pdo->exec("COMMENT ON COLUMN react_slides.is_active IS '1 = Activo, 0 = Inactivo'");
            $pdo->exec("COMMENT ON COLUMN react_slides.custom_css IS 'CSS personalizado'");
            $pdo->exec("COMMENT ON COLUMN react_slides.custom_data IS 'Datos personalizados (JSON)'");
        }

        echo "✓ Table react_slides created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `react_slides`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS react_slides");
        }

        echo "✓ Table react_slides dropped\n";
    }
}
