<?php
/**
 * Migration: Create marketplace_items table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_091120
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateMarketplaceItemsTable_2025_12_11_091120
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `marketplace_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) NOT NULL COMMENT 'Identificador único del item',
  `type` enum('module','plugin','theme') NOT NULL COMMENT 'Tipo de item',
  `name` varchar(255) DEFAULT NULL COMMENT 'Nombre del item',
  `version` varchar(20) DEFAULT '1.0.0' COMMENT 'Versión instalada',
  `author` varchar(255) DEFAULT NULL COMMENT 'Autor del item',
  `description` text DEFAULT NULL COMMENT 'Descripción del item',
  `marketplace_id` varchar(100) DEFAULT NULL COMMENT 'ID del item en el marketplace remoto',
  `installed_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de instalación',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Última actualización',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_item` (`slug`, `type`),
  KEY `idx_type` (`type`),
  KEY `idx_installed_at` (`installed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE marketplace_items (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL,
  name VARCHAR(255),
  version VARCHAR(20) DEFAULT '1.0.0',
  author VARCHAR(255),
  description TEXT,
  marketplace_id VARCHAR(100),
  installed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (type IN ('module', 'plugin', 'theme')),
  UNIQUE (slug, type)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX idx_type ON marketplace_items(type)");
            $pdo->exec("CREATE INDEX idx_installed_at ON marketplace_items(installed_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN marketplace_items.slug IS 'Identificador único del item'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.type IS 'Tipo de item'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.name IS 'Nombre del item'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.version IS 'Versión instalada'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.author IS 'Autor del item'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.description IS 'Descripción del item'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.marketplace_id IS 'ID del item en el marketplace remoto'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.installed_at IS 'Fecha de instalación'");
            $pdo->exec("COMMENT ON COLUMN marketplace_items.updated_at IS 'Última actualización'");
        }

        echo "✓ Table marketplace_items created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `marketplace_items`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS marketplace_items");
        }

        echo "✓ Table marketplace_items dropped\n";
    }
}
