<?php
/**
 * Migration: Create tenant_plugins table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102306
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateTenantPluginsTable_2025_12_11_102306
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_plugins` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL COMMENT 'ID del tenant',
  `slug` varchar(100) NOT NULL COMMENT 'Identificador único del plugin',
  `name` varchar(255) NOT NULL COMMENT 'Nombre del plugin',
  `description` text DEFAULT NULL COMMENT 'Descripción del plugin',
  `version` varchar(20) NOT NULL DEFAULT '1.0.0' COMMENT 'Versión del plugin',
  `author` varchar(255) DEFAULT NULL COMMENT 'Autor del plugin',
  `active` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Si está activo (desactivado por defecto por seguridad)',
  `installed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de instalación',
  `updated_at` timestamp DEFAULT NULL,
  `settings` text DEFAULT NULL COMMENT 'JSON con configuración del plugin',
  `permissions` text DEFAULT NULL COMMENT 'JSON con permisos requeridos del plugin',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_plugin` (`tenant_id`, `slug`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_active` (`active`),
  KEY `idx_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE tenant_plugins (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  slug VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  "version" VARCHAR(20) NOT NULL DEFAULT '1.0.0',
  author VARCHAR(255),
  active SMALLINT NOT NULL DEFAULT '0',
  installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  settings TEXT,
  permissions TEXT,
  UNIQUE (tenant_id, slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX tenant_plugins_idx_tenant_id ON tenant_plugins(tenant_id)");
            $pdo->exec("CREATE INDEX tenant_plugins_idx_active ON tenant_plugins(active)");
            $pdo->exec("CREATE INDEX tenant_plugins_idx_slug ON tenant_plugins(slug)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.tenant_id IS 'ID del tenant'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.slug IS 'Identificador único del plugin'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.name IS 'Nombre del plugin'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.description IS 'Descripción del plugin'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.\"version\" IS 'Versión del plugin'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.author IS 'Autor del plugin'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.active IS 'Si está activo (desactivado por defecto por seguridad)'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.installed_at IS 'Fecha de instalación'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.settings IS 'JSON con configuración del plugin'");
            $pdo->exec("COMMENT ON COLUMN tenant_plugins.permissions IS 'JSON con permisos requeridos del plugin'");
        }

        echo "✓ Table tenant_plugins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `tenant_plugins`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS tenant_plugins");
        }

        echo "✓ Table tenant_plugins dropped\n";
    }
}
