<?php
/**
 * Migration: Create rate_limits table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateRateLimitsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `rate_limits` (
                  `identifier` varchar(255) NOT NULL COMMENT 'Identificador único (email|tenant|IP)',
                  `attempts` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Número de intentos',
                  `expires_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Fecha de expiración del bloqueo',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Fecha de creación',
                  PRIMARY KEY (`identifier`),
                  KEY `idx_expires_at` (`expires_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Control de rate limiting para prevenir fuerza bruta'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table rate_limits created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `rate_limits`");
        echo "✓ Table rate_limits dropped\n";
    }
}
