<?php
/**
 * Migration: Create theme_options table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateThemeOptionsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `theme_options` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(10) unsigned DEFAULT NULL,
                  `theme_slug` varchar(50) NOT NULL,
                  `value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`value`)),
                  `created_at` timestamp NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_theme_tenant` (`theme_slug`,`tenant_id`),
                  UNIQUE KEY `unique_theme_per_tenant` (`tenant_id`,`theme_slug`),
                  KEY `idx_theme_options_tenant_id` (`tenant_id`)
                ) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table theme_options created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `theme_options`");
        echo "✓ Table theme_options dropped\n";
    }
}
