<?php
/**
 * Migration: Update domain_orders for multiple contacts and hosting options
 * Generated by MuseDock Migration System
 * Generated at: 2025_12_22_120000
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * Adds columns for:
 * - Separate contact handles (owner, admin, tech, billing)
 * - Hosting option (dns_only or musedock_hosting)
 * - Custom nameservers
 */

use Screenart\Musedock\Database;

class UpdateDomainOrdersContacts_2025_12_22_120000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
        $isPostgres = ($driver === 'pgsql');

        // Check if columns already exist
        if ($isPostgres) {
            $checkSql = "SELECT column_name FROM information_schema.columns
                         WHERE table_name = 'domain_orders' AND column_name = 'owner_handle'";
        } else {
            $checkSql = "SHOW COLUMNS FROM domain_orders LIKE 'owner_handle'";
        }

        $result = $pdo->query($checkSql)->fetch();
        if ($result) {
            echo "✓ domain_orders already has contact handle columns, skipping\n";
            return;
        }

        if ($isPostgres) {
            // PostgreSQL
            $pdo->exec("
                ALTER TABLE domain_orders
                ADD COLUMN IF NOT EXISTS owner_handle VARCHAR(50) NULL,
                ADD COLUMN IF NOT EXISTS admin_handle VARCHAR(50) NULL,
                ADD COLUMN IF NOT EXISTS tech_handle VARCHAR(50) NULL,
                ADD COLUMN IF NOT EXISTS billing_handle VARCHAR(50) NULL,
                ADD COLUMN IF NOT EXISTS hosting_type VARCHAR(20) DEFAULT 'musedock_hosting',
                ADD COLUMN IF NOT EXISTS custom_nameservers TEXT NULL,
                ADD COLUMN IF NOT EXISTS use_cloudflare_ns BOOLEAN DEFAULT TRUE
            ");

            // Comments
            $pdo->exec("COMMENT ON COLUMN domain_orders.hosting_type IS 'dns_only or musedock_hosting'");
            $pdo->exec("COMMENT ON COLUMN domain_orders.custom_nameservers IS 'JSON array of custom nameservers'");

        } else {
            // MySQL/MariaDB - check each column individually to avoid errors
            $columns = [
                "ADD COLUMN owner_handle VARCHAR(50) NULL AFTER openprovider_contact_handle",
                "ADD COLUMN admin_handle VARCHAR(50) NULL AFTER owner_handle",
                "ADD COLUMN tech_handle VARCHAR(50) NULL AFTER admin_handle",
                "ADD COLUMN billing_handle VARCHAR(50) NULL AFTER tech_handle",
                "ADD COLUMN hosting_type ENUM('dns_only', 'musedock_hosting') DEFAULT 'musedock_hosting' AFTER billing_handle",
                "ADD COLUMN custom_nameservers TEXT NULL COMMENT 'JSON array of custom nameservers' AFTER hosting_type",
                "ADD COLUMN use_cloudflare_ns TINYINT(1) DEFAULT 1 AFTER custom_nameservers"
            ];

            foreach ($columns as $columnDef) {
                try {
                    $pdo->exec("ALTER TABLE domain_orders " . $columnDef);
                } catch (PDOException $e) {
                    // Column may already exist, ignore error
                    if (strpos($e->getMessage(), 'Duplicate column') === false) {
                        throw $e;
                    }
                }
            }
        }

        // Migrate existing data: copy openprovider_contact_handle to all handle columns
        $pdo->exec("
            UPDATE domain_orders
            SET owner_handle = openprovider_contact_handle,
                admin_handle = openprovider_contact_handle,
                tech_handle = openprovider_contact_handle,
                billing_handle = openprovider_contact_handle
            WHERE openprovider_contact_handle IS NOT NULL
              AND owner_handle IS NULL
        ");

        echo "✓ domain_orders updated with contact handles and hosting options\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
        $isPostgres = ($driver === 'pgsql');

        if ($isPostgres) {
            $pdo->exec("
                ALTER TABLE domain_orders
                DROP COLUMN IF EXISTS owner_handle,
                DROP COLUMN IF EXISTS admin_handle,
                DROP COLUMN IF EXISTS tech_handle,
                DROP COLUMN IF EXISTS billing_handle,
                DROP COLUMN IF EXISTS hosting_type,
                DROP COLUMN IF EXISTS custom_nameservers,
                DROP COLUMN IF EXISTS use_cloudflare_ns
            ");
        } else {
            // MySQL needs individual DROP COLUMN statements
            $columns = ['owner_handle', 'admin_handle', 'tech_handle', 'billing_handle', 'hosting_type', 'custom_nameservers', 'use_cloudflare_ns'];
            foreach ($columns as $column) {
                try {
                    $pdo->exec("ALTER TABLE domain_orders DROP COLUMN {$column}");
                } catch (PDOException $e) {
                    // Column may not exist, ignore error
                }
            }
        }

        echo "✓ domain_orders contact handle columns removed\n";
    }
}
