<?php
/**
 * Migration: Create tenant_plugins table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateTenantPluginsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_plugins` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) NOT NULL COMMENT 'ID del tenant',
                  `slug` varchar(100) NOT NULL COMMENT 'Identificador único del plugin',
                  `name` varchar(255) NOT NULL COMMENT 'Nombre del plugin',
                  `description` text DEFAULT NULL COMMENT 'Descripción del plugin',
                  `version` varchar(20) NOT NULL DEFAULT '1.0.0' COMMENT 'Versión del plugin',
                  `author` varchar(255) DEFAULT NULL COMMENT 'Autor del plugin',
                  `active` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Si está activo (desactivado por defecto por seguridad)',
                  `installed_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Fecha de instalación',
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  `settings` text DEFAULT NULL COMMENT 'JSON con configuración del plugin',
                  `permissions` text DEFAULT NULL COMMENT 'JSON con permisos requeridos del plugin',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_plugin` (`tenant_id`,`slug`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_active` (`active`),
                  KEY `idx_slug` (`slug`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Plugins privados por tenant (aislados)'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table tenant_plugins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `tenant_plugins`");
        echo "✓ Table tenant_plugins dropped\n";
    }
}
