<?php
/**
 * Migration: Create superadmin_plugins table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginsTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) NOT NULL COMMENT 'Identificador único del plugin',
  `name` varchar(255) NOT NULL COMMENT 'Nombre del plugin',
  `description` text DEFAULT NULL COMMENT 'Descripción del plugin',
  `version` varchar(50) DEFAULT '1.0.0' COMMENT 'Versión del plugin',
  `author` varchar(255) DEFAULT NULL COMMENT 'Autor del plugin',
  `author_url` varchar(500) DEFAULT NULL COMMENT 'URL del autor',
  `plugin_url` varchar(500) DEFAULT NULL COMMENT 'URL del plugin',
  `path` varchar(500) NOT NULL COMMENT 'Ruta del directorio del plugin',
  `main_file` varchar(255) NOT NULL COMMENT 'Archivo principal del plugin',
  `namespace` varchar(255) DEFAULT NULL COMMENT 'Namespace del plugin',
  `is_active` tinyint(1) DEFAULT '0' COMMENT '1 = Activo, 0 = Inactivo',
  `is_installed` tinyint(1) DEFAULT '0' COMMENT '1 = Instalado, 0 = No instalado',
  `auto_activate` tinyint(1) DEFAULT '0' COMMENT 'Activar automáticamente al instalar',
  `requires_php` varchar(50) DEFAULT NULL COMMENT 'Versión mínima de PHP requerida',
  `requires_musedock` varchar(50) DEFAULT NULL COMMENT 'Versión mínima de MuseDock',
  `dependencies` text DEFAULT NULL COMMENT 'Dependencias del plugin (JSON)',
  `settings` longtext DEFAULT NULL COMMENT 'Configuración del plugin (JSON)',
  `installed_at` datetime DEFAULT NULL COMMENT 'Fecha de instalación',
  `activated_at` datetime DEFAULT NULL COMMENT 'Fecha de última activación',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `is_active` (`is_active`),
  KEY `is_installed` (`is_installed`),
  KEY `idx_active_plugins` (`is_active`, `is_installed`),
  KEY `idx_plugin_slug` (`slug`, `is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE superadmin_plugins (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  version VARCHAR(50) DEFAULT '1.0.0',
  author VARCHAR(255),
  author_url VARCHAR(500),
  plugin_url VARCHAR(500),
  path VARCHAR(500) NOT NULL,
  main_file VARCHAR(255) NOT NULL,
  namespace VARCHAR(255),
  is_active SMALLINT DEFAULT '0',
  is_installed SMALLINT DEFAULT '0',
  auto_activate SMALLINT DEFAULT '0',
  requires_php VARCHAR(50),
  requires_musedock VARCHAR(50),
  dependencies TEXT,
  settings TEXT,
  installed_at TIMESTAMP,
  activated_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX superadmin_plugins_is_active ON superadmin_plugins(is_active)");
            $pdo->exec("CREATE INDEX superadmin_plugins_is_installed ON superadmin_plugins(is_installed)");
            $pdo->exec("CREATE INDEX superadmin_plugins_idx_active_plugins ON superadmin_plugins(is_active, is_installed)");
            $pdo->exec("CREATE INDEX superadmin_plugins_idx_plugin_slug ON superadmin_plugins(slug, is_active)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.slug IS 'Identificador único del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.name IS 'Nombre del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.description IS 'Descripción del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.version IS 'Versión del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.author IS 'Autor del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.author_url IS 'URL del autor'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.plugin_url IS 'URL del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.path IS 'Ruta del directorio del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.main_file IS 'Archivo principal del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.namespace IS 'Namespace del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.is_active IS '1 = Activo, 0 = Inactivo'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.is_installed IS '1 = Instalado, 0 = No instalado'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.auto_activate IS 'Activar automáticamente al instalar'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.requires_php IS 'Versión mínima de PHP requerida'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.requires_musedock IS 'Versión mínima de MuseDock'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.dependencies IS 'Dependencias del plugin (JSON)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.settings IS 'Configuración del plugin (JSON)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.installed_at IS 'Fecha de instalación'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugins.activated_at IS 'Fecha de última activación'");
        }

        echo "✓ Table superadmin_plugins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugins`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS superadmin_plugins");
        }

        echo "✓ Table superadmin_plugins dropped\n";
    }
}
