<?php
/**
 * Migration: Add missing columns to slider_slides table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_16_171500
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class AddMissingColumnsToSliderSlides_2025_12_16_171500
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        echo "🔄 Adding missing columns to slider_slides table...\n";

        // Obtener columnas existentes
        $existingColumns = $this->getExistingColumns($pdo, $driver);

        // Definir columnas a añadir (solo las que NO existen)
        $columnsToAdd = [];

        if (!in_array('link_text', $existingColumns)) {
            $columnsToAdd['link_text'] = [
                'mysql' => 'VARCHAR(120) NULL',
                'pgsql' => 'VARCHAR(120)'
            ];
        }

        if (!in_array('link2_url', $existingColumns)) {
            $columnsToAdd['link2_url'] = [
                'mysql' => 'TEXT NULL',
                'pgsql' => 'TEXT'
            ];
        }

        if (!in_array('link2_target', $existingColumns)) {
            $columnsToAdd['link2_target'] = [
                'mysql' => "VARCHAR(16) NOT NULL DEFAULT '_self'",
                'pgsql' => "VARCHAR(16) NOT NULL DEFAULT '_self'"
            ];
        }

        if (!in_array('link2_text', $existingColumns)) {
            $columnsToAdd['link2_text'] = [
                'mysql' => 'VARCHAR(120) NULL',
                'pgsql' => 'VARCHAR(120)'
            ];
        }

        if (!in_array('title_bold', $existingColumns)) {
            $columnsToAdd['title_bold'] = [
                'mysql' => 'TINYINT(1) NOT NULL DEFAULT 1',
                'pgsql' => 'SMALLINT NOT NULL DEFAULT 1'
            ];
        }

        if (!in_array('button_custom', $existingColumns)) {
            $columnsToAdd['button_custom'] = [
                'mysql' => 'TINYINT(1) NOT NULL DEFAULT 0',
                'pgsql' => 'SMALLINT NOT NULL DEFAULT 0'
            ];
        }

        if (!in_array('button_bg_color', $existingColumns)) {
            $columnsToAdd['button_bg_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('button_text_color', $existingColumns)) {
            $columnsToAdd['button_text_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('button_border_color', $existingColumns)) {
            $columnsToAdd['button_border_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('button2_custom', $existingColumns)) {
            $columnsToAdd['button2_custom'] = [
                'mysql' => 'TINYINT(1) NOT NULL DEFAULT 0',
                'pgsql' => 'SMALLINT NOT NULL DEFAULT 0'
            ];
        }

        if (!in_array('button2_bg_color', $existingColumns)) {
            $columnsToAdd['button2_bg_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('button2_text_color', $existingColumns)) {
            $columnsToAdd['button2_text_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('button2_border_color', $existingColumns)) {
            $columnsToAdd['button2_border_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('button_shape', $existingColumns)) {
            $columnsToAdd['button_shape'] = [
                'mysql' => "VARCHAR(16) NOT NULL DEFAULT 'rounded'",
                'pgsql' => "VARCHAR(16) NOT NULL DEFAULT 'rounded'"
            ];
        }

        if (!in_array('title_font', $existingColumns)) {
            $columnsToAdd['title_font'] = [
                'mysql' => 'VARCHAR(255) NULL',
                'pgsql' => 'VARCHAR(255)'
            ];
        }

        if (!in_array('title_color', $existingColumns)) {
            $columnsToAdd['title_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        if (!in_array('description_font', $existingColumns)) {
            $columnsToAdd['description_font'] = [
                'mysql' => 'VARCHAR(255) NULL',
                'pgsql' => 'VARCHAR(255)'
            ];
        }

        if (!in_array('description_color', $existingColumns)) {
            $columnsToAdd['description_color'] = [
                'mysql' => 'VARCHAR(32) NULL',
                'pgsql' => 'VARCHAR(32)'
            ];
        }

        // Si no hay columnas para añadir, salir
        if (empty($columnsToAdd)) {
            echo "✅ All columns already exist in slider_slides table\n";
            return;
        }

        // Añadir columnas según el driver
        $addedCount = 0;
        foreach ($columnsToAdd as $columnName => $definitions) {
            try {
                if ($driver === 'mysql') {
                    $sql = "ALTER TABLE `slider_slides` ADD COLUMN `{$columnName}` {$definitions['mysql']}";
                } else {
                    $sql = "ALTER TABLE slider_slides ADD COLUMN {$columnName} {$definitions['pgsql']}";
                }

                $pdo->exec($sql);
                echo "  ✓ Added column: {$columnName}\n";
                $addedCount++;
            } catch (PDOException $e) {
                echo "  ✗ Error adding column {$columnName}: " . $e->getMessage() . "\n";
            }
        }

        echo "\n📊 Summary: {$addedCount} columns added to slider_slides\n";
        echo "✅ Migration completed\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        echo "⚠️  Reverting migration: removing added columns from slider_slides...\n";

        $columnsToRemove = [
            'link_text', 'link2_url', 'link2_target', 'link2_text',
            'title_bold', 'button_custom', 'button_bg_color', 'button_text_color',
            'button_border_color', 'button2_custom', 'button2_bg_color',
            'button2_text_color', 'button2_border_color', 'button_shape',
            'title_font', 'title_color', 'description_font', 'description_color'
        ];

        $removedCount = 0;
        foreach ($columnsToRemove as $columnName) {
            try {
                if ($driver === 'mysql') {
                    $sql = "ALTER TABLE `slider_slides` DROP COLUMN IF EXISTS `{$columnName}`";
                } else {
                    $sql = "ALTER TABLE slider_slides DROP COLUMN IF EXISTS {$columnName}";
                }

                $pdo->exec($sql);
                echo "  ✓ Removed column: {$columnName}\n";
                $removedCount++;
            } catch (PDOException $e) {
                // Columna no existe, continuar
                echo "  - Column {$columnName} does not exist\n";
            }
        }

        echo "\n📊 Summary: {$removedCount} columns removed from slider_slides\n";
        echo "✅ Rollback completed\n";
    }

    /**
     * Get existing columns from the table
     */
    private function getExistingColumns($pdo, $driver)
    {
        $columns = [];

        try {
            if ($driver === 'mysql') {
                $stmt = $pdo->query("SHOW COLUMNS FROM `slider_slides`");
                while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                    $columns[] = $row['Field'];
                }
            } else {
                // PostgreSQL
                $stmt = $pdo->query("SELECT column_name FROM information_schema.columns WHERE table_name = 'slider_slides'");
                while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                    $columns[] = $row['column_name'];
                }
            }
        } catch (PDOException $e) {
            echo "  ⚠️  Warning: Could not retrieve existing columns. Assuming table needs all columns.\n";
        }

        return $columns;
    }
}
