<?php
/**
 * Migration: Create scheduled_tasks table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateScheduledTasksTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `scheduled_tasks` (
  `task_name` varchar(100) NOT NULL COMMENT 'Nombre único de la tarea',
  `last_run` datetime DEFAULT NULL COMMENT 'Última vez que se ejecutó',
  `next_run` datetime DEFAULT NULL COMMENT 'Próxima ejecución programada',
  `status` enum('idle','running','failed') DEFAULT 'idle' COMMENT 'Estado actual',
  `last_error` text DEFAULT NULL COMMENT 'Último error ocurrido',
  `last_duration` int(11) DEFAULT NULL COMMENT 'Duración de última ejecución (segundos)',
  `run_count` int(11) DEFAULT '0' COMMENT 'Número total de ejecuciones',
  `success_count` int(11) DEFAULT '0' COMMENT 'Número de ejecuciones exitosas',
  `fail_count` int(11) DEFAULT '0' COMMENT 'Número de ejecuciones fallidas',
  `locked_until` datetime DEFAULT NULL COMMENT 'Lock para evitar ejecuciones concurrentes',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_status` (`status`),
  KEY `idx_next_run` (`next_run`),
  KEY `idx_locked_until` (`locked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE scheduled_tasks (
  task_name VARCHAR(100) NOT NULL,
  last_run TIMESTAMP,
  next_run TIMESTAMP,
  status VARCHAR(20) DEFAULT 'idle',
  last_error TEXT,
  last_duration INTEGER,
  run_count INTEGER DEFAULT '0',
  success_count INTEGER DEFAULT '0',
  fail_count INTEGER DEFAULT '0',
  locked_until TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('idle', 'running', 'failed'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX scheduled_tasks_idx_status ON scheduled_tasks(status)");
            $pdo->exec("CREATE INDEX scheduled_tasks_idx_next_run ON scheduled_tasks(next_run)");
            $pdo->exec("CREATE INDEX scheduled_tasks_idx_locked_until ON scheduled_tasks(locked_until)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.task_name IS 'Nombre único de la tarea'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.last_run IS 'Última vez que se ejecutó'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.next_run IS 'Próxima ejecución programada'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.status IS 'Estado actual'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.last_error IS 'Último error ocurrido'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.last_duration IS 'Duración de última ejecución (segundos)'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.run_count IS 'Número total de ejecuciones'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.success_count IS 'Número de ejecuciones exitosas'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.fail_count IS 'Número de ejecuciones fallidas'");
            $pdo->exec("COMMENT ON COLUMN scheduled_tasks.locked_until IS 'Lock para evitar ejecuciones concurrentes'");
        }

        echo "✓ Table scheduled_tasks created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `scheduled_tasks`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS scheduled_tasks");
        }

        echo "✓ Table scheduled_tasks dropped\n";
    }
}
