<?php
/**
 * Migration: Create superadmin_plugin_hooks table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginHooksTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_hooks` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `plugin_id` int(11) NOT NULL COMMENT 'ID del plugin',
                  `hook_name` varchar(255) NOT NULL COMMENT 'Nombre del hook/acción',
                  `callback` varchar(500) NOT NULL COMMENT 'Función callback',
                  `priority` int(11) DEFAULT 10 COMMENT 'Prioridad de ejecución (menor = primero)',
                  `is_active` tinyint(1) DEFAULT 1 COMMENT '1 = Activo, 0 = Inactivo',
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `plugin_id` (`plugin_id`),
                  KEY `hook_name` (`hook_name`),
                  KEY `is_active` (`is_active`),
                  CONSTRAINT `fk_plugin_hooks_plugin` FOREIGN KEY (`plugin_id`) REFERENCES `superadmin_plugins` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Hooks y acciones registradas por plugins'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table superadmin_plugin_hooks created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_hooks`");
        echo "✓ Table superadmin_plugin_hooks dropped\n";
    }
}
