<?php
/**
 * Migration: Create user_permissions table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateUserPermissionsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `user_permissions` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `user_id` int(11) NOT NULL,
                  `permission_slug` varchar(100) NOT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  `granted_by` int(11) DEFAULT NULL COMMENT 'ID del admin que otorgó el permiso',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_user_permission` (`user_id`,`permission_slug`,`tenant_id`),
                  KEY `idx_user_id` (`user_id`),
                  KEY `idx_permission_slug` (`permission_slug`),
                  KEY `idx_tenant_id` (`tenant_id`)
                ) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table user_permissions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `user_permissions`");
        echo "✓ Table user_permissions dropped\n";
    }
}
