<?php
/**
 * Migration: Add soft delete support to customers table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025-12-21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This migration adds:
 * - deleted_at: timestamp for soft delete
 * - deletion_reason: optional reason for deletion
 */

use Screenart\Musedock\Database;

class AddSoftDeleteToCustomers_2025_12_21_170000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        // Check if deleted_at column already exists
        if ($driver === 'pgsql') {
            $checkStmt = $pdo->query("
                SELECT column_name FROM information_schema.columns
                WHERE table_name = 'customers' AND column_name = 'deleted_at'
            ");
        } else {
            $checkStmt = $pdo->query("
                SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'deleted_at'
            ");
        }

        if ($checkStmt->fetch()) {
            echo "✓ Column 'deleted_at' already exists in customers table\n";
            return;
        }

        // Add soft delete columns
        if ($driver === 'pgsql') {
            $pdo->exec("
                ALTER TABLE customers
                ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
                ADD COLUMN deletion_reason VARCHAR(500) NULL DEFAULT NULL
            ");

            // Create index for soft delete queries
            $pdo->exec("
                CREATE INDEX IF NOT EXISTS idx_customers_deleted_at ON customers (deleted_at)
            ");
        } else {
            // MySQL/MariaDB
            $pdo->exec("
                ALTER TABLE customers
                ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL,
                ADD COLUMN deletion_reason VARCHAR(500) NULL DEFAULT NULL
            ");

            // Create index for soft delete queries
            $pdo->exec("
                CREATE INDEX idx_customers_deleted_at ON customers (deleted_at)
            ");
        }

        echo "✓ Added soft delete columns to customers table\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            $pdo->exec("DROP INDEX IF EXISTS idx_customers_deleted_at");
            $pdo->exec("
                ALTER TABLE customers
                DROP COLUMN IF EXISTS deleted_at,
                DROP COLUMN IF EXISTS deletion_reason
            ");
        } else {
            // MySQL/MariaDB
            try {
                $pdo->exec("DROP INDEX idx_customers_deleted_at ON customers");
            } catch (\Exception $e) {
                // Index might not exist
            }
            $pdo->exec("
                ALTER TABLE customers
                DROP COLUMN IF EXISTS deleted_at,
                DROP COLUMN IF EXISTS deletion_reason
            ");
        }

        echo "✓ Removed soft delete columns from customers table\n";
    }
}
