<?php
/**
 * Migration: Create slugs table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSlugsTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `slugs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL,
  `module` varchar(50) NOT NULL,
  `reference_id` int(11) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `prefix` varchar(50) DEFAULT NULL,
  `locale` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_slug` (`tenant_id`, `slug`, `prefix`),
  UNIQUE KEY `slug_unique` (`slug`, `module`, `reference_id`, `tenant_id`, `prefix`),
  UNIQUE KEY `unique_slug` (`module`, `reference_id`, `slug`, `tenant_id`, `prefix`),
  KEY `idx_slugs_tenant` (`tenant_id`),
  KEY `idx_slugs_module_reference` (`module`, `reference_id`),
  KEY `idx_slugs_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE slugs (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  module VARCHAR(50) NOT NULL,
  reference_id INTEGER NOT NULL,
  slug VARCHAR(255) NOT NULL,
  prefix VARCHAR(50),
  locale VARCHAR(5),
  UNIQUE (tenant_id, slug, prefix),
  UNIQUE (slug, module, reference_id, tenant_id, prefix),
  UNIQUE (module, reference_id, slug, tenant_id, prefix)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX slugs_idx_slugs_tenant ON slugs(tenant_id)");
            $pdo->exec("CREATE INDEX slugs_idx_slugs_module_reference ON slugs(module, reference_id)");
            $pdo->exec("CREATE INDEX slugs_idx_slugs_slug ON slugs(slug)");
        }

        echo "✓ Table slugs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `slugs`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS slugs");
        }

        echo "✓ Table slugs dropped\n";
    }
}
