<?php
/**
 * Migration: Create marketplace_items table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateMarketplaceItemsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `marketplace_items` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `slug` varchar(100) NOT NULL COMMENT 'Identificador único del item',
                  `type` enum('module','plugin','theme') NOT NULL COMMENT 'Tipo de item',
                  `name` varchar(255) DEFAULT NULL COMMENT 'Nombre del item',
                  `version` varchar(20) DEFAULT '1.0.0' COMMENT 'Versión instalada',
                  `author` varchar(255) DEFAULT NULL COMMENT 'Autor del item',
                  `description` text DEFAULT NULL COMMENT 'Descripción del item',
                  `marketplace_id` varchar(100) DEFAULT NULL COMMENT 'ID del item en el marketplace remoto',
                  `installed_at` datetime DEFAULT current_timestamp() COMMENT 'Fecha de instalación',
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Última actualización',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_item` (`slug`,`type`),
                  KEY `idx_type` (`type`),
                  KEY `idx_installed_at` (`installed_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Items instalados desde el Marketplace'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table marketplace_items created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `marketplace_items`");
        echo "✓ Table marketplace_items dropped\n";
    }
}
