<?php
/**
 * Migration: Create role_permissions table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateRolePermissionsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `role_permissions` (
                  `role_id` int(11) NOT NULL,
                  `permission_id` int(11) NOT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`role_id`,`permission_id`),
                  KEY `idx_role_permissions_permission_id` (`permission_id`),
                  KEY `fk_role_permissions_tenant` (`tenant_id`),
                  CONSTRAINT `fk_role_permissions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`),
                  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
                  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table role_permissions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `role_permissions`");
        echo "✓ Table role_permissions dropped\n";
    }
}
