<?php
/**
 * Migration: Create blog_post_categories table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102305
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogPostCategoriesTable_2025_12_11_102305
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
  `category_id` int(10) unsigned NOT NULL COMMENT 'ID de la categoría',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_post_category` (`post_id`, `category_id`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_blog_post_categories_post` (`post_id`),
  KEY `idx_blog_post_categories_category` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_post_categories (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL,
  category_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (post_id, category_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_post_categories_idx_post_id ON blog_post_categories(post_id)");
            $pdo->exec("CREATE INDEX blog_post_categories_idx_category_id ON blog_post_categories(category_id)");
            $pdo->exec("CREATE INDEX blog_post_categories_idx_blog_post_categories_post ON blog_post_categories(post_id)");
            $pdo->exec("CREATE INDEX blog_post_categories_idx_blog_post_categories_category ON blog_post_categories(category_id)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_post_categories.post_id IS 'ID del post'");
            $pdo->exec("COMMENT ON COLUMN blog_post_categories.category_id IS 'ID de la categoría'");
        }

        echo "✓ Table blog_post_categories created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_post_categories`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_post_categories");
        }

        echo "✓ Table blog_post_categories dropped\n";
    }
}
