<?php
/**
 * Migration: Create superadmin_plugin_menus table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginMenusTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_menus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plugin_id` int(11) NOT NULL COMMENT 'ID del plugin',
  `parent_id` int(11) DEFAULT NULL COMMENT 'ID del menú padre (para submenús)',
  `title` varchar(255) NOT NULL COMMENT 'Título del menú',
  `icon` varchar(100) DEFAULT NULL COMMENT 'Icono del menú',
  `icon_type` varchar(20) DEFAULT 'bi' COMMENT 'Tipo de icono (bi, fas, etc.)',
  `url` varchar(500) DEFAULT NULL COMMENT 'URL del menú',
  `permission` varchar(255) DEFAULT NULL COMMENT 'Permiso requerido',
  `order` int(11) DEFAULT '0' COMMENT 'Orden de visualización',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '1 = Activo, 0 = Inactivo',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `parent_id` (`parent_id`),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE superadmin_plugin_menus (
  id SERIAL PRIMARY KEY,
  plugin_id INTEGER NOT NULL,
  parent_id INTEGER,
  title VARCHAR(255) NOT NULL,
  icon VARCHAR(100),
  icon_type VARCHAR(20) DEFAULT 'bi',
  url VARCHAR(500),
  permission VARCHAR(255),
  \"order\" INTEGER DEFAULT '0',
  is_active SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX superadmin_plugin_menus_plugin_id ON superadmin_plugin_menus(plugin_id)");
            $pdo->exec("CREATE INDEX superadmin_plugin_menus_parent_id ON superadmin_plugin_menus(parent_id)");
            $pdo->exec("CREATE INDEX superadmin_plugin_menus_is_active ON superadmin_plugin_menus(is_active)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.plugin_id IS 'ID del plugin'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.parent_id IS 'ID del menú padre (para submenús)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.title IS 'Título del menú'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.icon IS 'Icono del menú'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.icon_type IS 'Tipo de icono (bi, fas, etc.)'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.url IS 'URL del menú'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.permission IS 'Permiso requerido'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.\"order\" IS 'Orden de visualización'");
            $pdo->exec("COMMENT ON COLUMN superadmin_plugin_menus.is_active IS '1 = Activo, 0 = Inactivo'");
        }

        echo "✓ Table superadmin_plugin_menus created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_menus`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS superadmin_plugin_menus");
        }

        echo "✓ Table superadmin_plugin_menus dropped\n";
    }
}
