<?php
/**
 * Migration: Add storage quota columns to tenants table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_13_040000
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class AddStorageQuotaToTenantsTable_2025_12_13_040000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            // Cuota de almacenamiento en MB (default 1024 = 1GB)
            $pdo->exec("
                ALTER TABLE `tenants`
                ADD COLUMN `storage_quota_mb` INT UNSIGNED NOT NULL DEFAULT 1024
                COMMENT 'Cuota de almacenamiento en MB (1024 = 1GB)'
            ");

            // Espacio usado en bytes (para precisión)
            $pdo->exec("
                ALTER TABLE `tenants`
                ADD COLUMN `storage_used_bytes` BIGINT UNSIGNED NOT NULL DEFAULT 0
                COMMENT 'Espacio de almacenamiento usado en bytes'
            ");

            // Índice para consultas de uso
            $pdo->exec("
                CREATE INDEX idx_tenants_storage ON `tenants` (`storage_quota_mb`, `storage_used_bytes`)
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                ALTER TABLE tenants
                ADD COLUMN storage_quota_mb INTEGER NOT NULL DEFAULT 1024
            ");

            $pdo->exec("
                ALTER TABLE tenants
                ADD COLUMN storage_used_bytes BIGINT NOT NULL DEFAULT 0
            ");

            // Índice
            $pdo->exec("
                CREATE INDEX idx_tenants_storage ON tenants (storage_quota_mb, storage_used_bytes)
            ");

            // Comentarios
            $pdo->exec("COMMENT ON COLUMN tenants.storage_quota_mb IS 'Cuota de almacenamiento en MB (1024 = 1GB)'");
            $pdo->exec("COMMENT ON COLUMN tenants.storage_used_bytes IS 'Espacio de almacenamiento usado en bytes'");
        }

        echo "✓ Added storage quota columns to tenants table\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP INDEX idx_tenants_storage ON `tenants`");
            $pdo->exec("ALTER TABLE `tenants` DROP COLUMN `storage_used_bytes`");
            $pdo->exec("ALTER TABLE `tenants` DROP COLUMN `storage_quota_mb`");
        } else {
            $pdo->exec("DROP INDEX IF EXISTS idx_tenants_storage");
            $pdo->exec("ALTER TABLE tenants DROP COLUMN IF EXISTS storage_used_bytes");
            $pdo->exec("ALTER TABLE tenants DROP COLUMN IF EXISTS storage_quota_mb");
        }

        echo "✓ Removed storage quota columns from tenants table\n";
    }
}
