<?php
/**
 * Migration: Create page_translations table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreatePageTranslationsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `page_translations` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `page_id` int(11) NOT NULL,
                  `locale` varchar(5) NOT NULL,
                  `title` varchar(255) NOT NULL,
                  `slug` varchar(255) NOT NULL,
                  `content` text NOT NULL,
                  `seo_title` varchar(255) DEFAULT NULL,
                  `seo_description` text DEFAULT NULL,
                  `seo_keywords` varchar(255) DEFAULT NULL,
                  `seo_image` varchar(255) DEFAULT NULL,
                  `canonical_url` varchar(255) DEFAULT NULL,
                  `robots_directive` varchar(50) DEFAULT 'index,follow',
                  `twitter_title` varchar(255) DEFAULT NULL,
                  `twitter_description` text DEFAULT NULL,
                  `twitter_image` varchar(255) DEFAULT NULL,
                  `created_at` datetime DEFAULT NULL,
                  `updated_at` datetime DEFAULT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `page_id` (`page_id`,`locale`)
                ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table page_translations created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `page_translations`");
        echo "✓ Table page_translations dropped\n";
    }
}
