<?php
/**
 * Migration: Create user_session_tokens table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateUserSessionTokensTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `user_session_tokens` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `user_id` int(10) unsigned NOT NULL,
                  `token` varchar(64) NOT NULL,
                  `ip` varchar(45) DEFAULT NULL,
                  `user_agent` varchar(255) DEFAULT NULL,
                  `persistent` tinyint(1) DEFAULT 1,
                  `created_at` datetime NOT NULL,
                  `expires_at` datetime NOT NULL,
                  `last_used_at` datetime NOT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `uk_user_token` (`token`),
                  KEY `fk_user_token` (`user_id`),
                  CONSTRAINT `fk_user_token` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table user_session_tokens created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `user_session_tokens`");
        echo "✓ Table user_session_tokens dropped\n";
    }
}
