<?php
/**
 * Migration: Create superadmin_plugins table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugins` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `slug` varchar(100) NOT NULL COMMENT 'Identificador único del plugin',
                  `name` varchar(255) NOT NULL COMMENT 'Nombre del plugin',
                  `description` text DEFAULT NULL COMMENT 'Descripción del plugin',
                  `version` varchar(50) DEFAULT '1.0.0' COMMENT 'Versión del plugin',
                  `author` varchar(255) DEFAULT NULL COMMENT 'Autor del plugin',
                  `author_url` varchar(500) DEFAULT NULL COMMENT 'URL del autor',
                  `plugin_url` varchar(500) DEFAULT NULL COMMENT 'URL del plugin',
                  `path` varchar(500) NOT NULL COMMENT 'Ruta del directorio del plugin',
                  `main_file` varchar(255) NOT NULL COMMENT 'Archivo principal del plugin',
                  `namespace` varchar(255) DEFAULT NULL COMMENT 'Namespace del plugin',
                  `is_active` tinyint(1) DEFAULT 0 COMMENT '1 = Activo, 0 = Inactivo',
                  `is_installed` tinyint(1) DEFAULT 0 COMMENT '1 = Instalado, 0 = No instalado',
                  `auto_activate` tinyint(1) DEFAULT 0 COMMENT 'Activar automáticamente al instalar',
                  `requires_php` varchar(50) DEFAULT NULL COMMENT 'Versión mínima de PHP requerida',
                  `requires_musedock` varchar(50) DEFAULT NULL COMMENT 'Versión mínima de MuseDock',
                  `dependencies` text DEFAULT NULL COMMENT 'Dependencias del plugin (JSON)',
                  `settings` longtext DEFAULT NULL COMMENT 'Configuración del plugin (JSON)',
                  `installed_at` datetime DEFAULT NULL COMMENT 'Fecha de instalación',
                  `activated_at` datetime DEFAULT NULL COMMENT 'Fecha de última activación',
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `slug` (`slug`),
                  KEY `is_active` (`is_active`),
                  KEY `is_installed` (`is_installed`),
                  KEY `idx_active_plugins` (`is_active`,`is_installed`),
                  KEY `idx_plugin_slug` (`slug`,`is_active`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Plugins instalados en el dominio base (superadmin)'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table superadmin_plugins created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugins`");
        echo "✓ Table superadmin_plugins dropped\n";
    }
}
