<?php
/**
 * Migration: Create pages_trash table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreatePagesTrashTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `pages_trash` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page_id` int(11) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL COMMENT 'NULL para páginas de superadmin',
  `deleted_by` int(11) NOT NULL,
  `deleted_by_name` varchar(100) DEFAULT NULL COMMENT 'Cache del nombre',
  `deleted_by_type` enum('user','admin','superadmin') DEFAULT 'admin',
  `deleted_at` datetime NOT NULL,
  `scheduled_permanent_delete` datetime DEFAULT NULL COMMENT 'Auto-eliminar después de 30 días',
  `reason` varchar(255) DEFAULT NULL COMMENT 'Razón de eliminación (opcional)',
  `ip_address` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_page_id` (`page_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_scheduled_delete` (`scheduled_permanent_delete`),
  KEY `idx_deleted_by` (`deleted_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE pages_trash (
  id SERIAL PRIMARY KEY,
  page_id INTEGER NOT NULL,
  tenant_id INTEGER,
  deleted_by INTEGER NOT NULL,
  deleted_by_name VARCHAR(100),
  deleted_by_type VARCHAR(20) DEFAULT 'admin',
  deleted_at TIMESTAMP NOT NULL,
  scheduled_permanent_delete TIMESTAMP,
  reason VARCHAR(255),
  ip_address VARCHAR(45),
  CHECK (deleted_by_type IN ('user', 'admin', 'superadmin'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX pages_trash_idx_page_id ON pages_trash(page_id)");
            $pdo->exec("CREATE INDEX pages_trash_idx_tenant_id ON pages_trash(tenant_id)");
            $pdo->exec("CREATE INDEX pages_trash_idx_deleted_at ON pages_trash(deleted_at)");
            $pdo->exec("CREATE INDEX pages_trash_idx_scheduled_delete ON pages_trash(scheduled_permanent_delete)");
            $pdo->exec("CREATE INDEX pages_trash_idx_deleted_by ON pages_trash(deleted_by)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN pages_trash.tenant_id IS 'NULL para páginas de superadmin'");
            $pdo->exec("COMMENT ON COLUMN pages_trash.deleted_by_name IS 'Cache del nombre'");
            $pdo->exec("COMMENT ON COLUMN pages_trash.scheduled_permanent_delete IS 'Auto-eliminar después de 30 días'");
            $pdo->exec("COMMENT ON COLUMN pages_trash.reason IS 'Razón de eliminación (opcional)'");
        }

        echo "✓ Table pages_trash created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `pages_trash`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS pages_trash");
        }

        echo "✓ Table pages_trash dropped\n";
    }
}
