<?php
/**
 * Migration: Create tenant_themes table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateTenantThemesTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_themes` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) NOT NULL,
                  `slug` varchar(100) NOT NULL,
                  `name` varchar(255) NOT NULL,
                  `description` text DEFAULT NULL,
                  `version` varchar(20) NOT NULL DEFAULT '1.0.0',
                  `author` varchar(255) DEFAULT NULL,
                  `screenshot` varchar(255) DEFAULT NULL,
                  `active` tinyint(1) NOT NULL DEFAULT 0,
                  `validated` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Pasó validación de seguridad',
                  `security_score` tinyint(3) unsigned DEFAULT NULL COMMENT 'Score de seguridad 0-100',
                  `installed_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  `settings` text DEFAULT NULL COMMENT 'JSON con configuración del tema',
                  `validation_errors` text DEFAULT NULL COMMENT 'JSON con errores de validación',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_theme` (`tenant_id`,`slug`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_active` (`active`),
                  KEY `idx_validated` (`validated`),
                  CONSTRAINT `fk_tenant_themes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table tenant_themes created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `tenant_themes`");
        echo "✓ Table tenant_themes dropped\n";
    }
}
