<?php
/**
 * Migration: Create admin_tenant_menus table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAdminTenantMenusTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admin_tenant_menus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `url` varchar(500) NOT NULL,
  `icon` varchar(100) DEFAULT NULL,
  `icon_type` enum('bi','fas','far','fal') DEFAULT 'bi',
  `order_position` int(11) DEFAULT '0',
  `permission` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_slug` (`tenant_id`, `slug`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE admin_tenant_menus (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  parent_id INTEGER,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  icon VARCHAR(100),
  icon_type VARCHAR(20) DEFAULT 'bi',
  order_position INTEGER DEFAULT '0',
  permission VARCHAR(255),
  is_active SMALLINT DEFAULT '1',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (icon_type IN ('bi', 'fas', 'far', 'fal')),
  UNIQUE (tenant_id, slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX admin_tenant_menus_idx_tenant_id ON admin_tenant_menus(tenant_id)");
            $pdo->exec("CREATE INDEX admin_tenant_menus_idx_parent_id ON admin_tenant_menus(parent_id)");
            $pdo->exec("CREATE INDEX admin_tenant_menus_idx_is_active ON admin_tenant_menus(is_active)");
        }

        echo "✓ Table admin_tenant_menus created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `admin_tenant_menus`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS admin_tenant_menus");
        }

        echo "✓ Table admin_tenant_menus dropped\n";
    }
}
