<?php
/**
 * Migration: Add 'custom' plan to tenants table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025-12-21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This migration adds 'custom' as a valid plan type for tenants
 * with custom domains (domain linking via nameserver change).
 */

use Screenart\Musedock\Database;

class AddCustomPlanToTenants_2025_12_21_172000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            // PostgreSQL: The plan column uses a CHECK constraint, not an ENUM type
            // First, find the constraint name for the plan column
            $stmt = $pdo->query("
                SELECT con.conname as constraint_name
                FROM pg_constraint con
                JOIN pg_class rel ON rel.oid = con.conrelid
                JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY(con.conkey)
                WHERE rel.relname = 'tenants'
                  AND att.attname = 'plan'
                  AND con.contype = 'c'
            ");
            $constraint = $stmt->fetch(\PDO::FETCH_ASSOC);

            if ($constraint) {
                $constraintName = $constraint['constraint_name'];

                // Check if 'custom' is already in the constraint
                $checkStmt = $pdo->query("
                    SELECT pg_get_constraintdef(oid) as definition
                    FROM pg_constraint
                    WHERE conname = '{$constraintName}'
                ");
                $def = $checkStmt->fetch(\PDO::FETCH_ASSOC);

                if ($def && strpos($def['definition'], 'custom') === false) {
                    // Drop old constraint and add new one with 'custom'
                    $pdo->exec("ALTER TABLE tenants DROP CONSTRAINT {$constraintName}");
                    $pdo->exec("ALTER TABLE tenants ADD CONSTRAINT {$constraintName} CHECK (plan IN ('free', 'starter', 'business', 'custom'))");
                    echo "✓ Added 'custom' to PostgreSQL plan CHECK constraint\n";
                } else {
                    echo "✓ 'custom' already exists in PostgreSQL plan constraint\n";
                }
            } else {
                // No constraint found, try to add one
                try {
                    $pdo->exec("ALTER TABLE tenants ADD CONSTRAINT tenants_plan_check CHECK (plan IN ('free', 'starter', 'business', 'custom'))");
                    echo "✓ Created PostgreSQL plan CHECK constraint with 'custom'\n";
                } catch (\Exception $e) {
                    echo "⚠ Could not add CHECK constraint: " . $e->getMessage() . "\n";
                }
            }
        } else {
            // MySQL/MariaDB: Modify the ENUM column
            // First check current enum values
            $stmt = $pdo->query("SHOW COLUMNS FROM tenants WHERE Field = 'plan'");
            $column = $stmt->fetch(\PDO::FETCH_ASSOC);

            if ($column && strpos($column['Type'], 'custom') === false) {
                // Add 'custom' to the enum
                $pdo->exec("
                    ALTER TABLE tenants
                    MODIFY COLUMN plan ENUM('free', 'starter', 'business', 'custom') NOT NULL DEFAULT 'free'
                ");
                echo "✓ Added 'custom' to MySQL plan enum\n";
            } else {
                echo "✓ 'custom' already exists in MySQL plan enum\n";
            }
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            // PostgreSQL: Update rows first, then modify constraint
            $pdo->exec("UPDATE tenants SET plan = 'business' WHERE plan = 'custom'");

            // Find and replace the constraint
            $stmt = $pdo->query("
                SELECT con.conname as constraint_name
                FROM pg_constraint con
                JOIN pg_class rel ON rel.oid = con.conrelid
                JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY(con.conkey)
                WHERE rel.relname = 'tenants'
                  AND att.attname = 'plan'
                  AND con.contype = 'c'
            ");
            $constraint = $stmt->fetch(\PDO::FETCH_ASSOC);

            if ($constraint) {
                $constraintName = $constraint['constraint_name'];
                $pdo->exec("ALTER TABLE tenants DROP CONSTRAINT {$constraintName}");
                $pdo->exec("ALTER TABLE tenants ADD CONSTRAINT {$constraintName} CHECK (plan IN ('free', 'starter', 'business'))");
            }
            echo "✓ Removed 'custom' from PostgreSQL plan CHECK constraint\n";
        } else {
            // MySQL: First update any 'custom' plans to 'business'
            $pdo->exec("UPDATE tenants SET plan = 'business' WHERE plan = 'custom'");

            // Then remove 'custom' from enum
            $pdo->exec("
                ALTER TABLE tenants
                MODIFY COLUMN plan ENUM('free', 'starter', 'business') NOT NULL DEFAULT 'free'
            ");
            echo "✓ Removed 'custom' from MySQL plan enum\n";
        }
    }
}
