<?php
/**
 * Migration: Create image_galleries table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateImageGalleriesTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `image_galleries` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) unsigned DEFAULT NULL COMMENT 'NULL = galería global',
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `thumbnail_url` varchar(500) DEFAULT NULL,
  `layout_type` enum('grid','masonry','carousel','lightbox','justified') DEFAULT 'grid',
  `columns` tinyint(1) DEFAULT '3' COMMENT 'Número de columnas (1-6)',
  `gap` smallint(5) DEFAULT '10' COMMENT 'Espacio entre imágenes en px',
  `settings` longtext DEFAULT NULL COMMENT 'Configuración adicional JSON',
  `is_active` tinyint(1) DEFAULT '1',
  `featured` tinyint(1) DEFAULT '0',
  `sort_order` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_slug_tenant` (`slug`, `tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_featured` (`featured`),
  KEY `idx_layout_type` (`layout_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE image_galleries (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnail_url VARCHAR(500),
  layout_type VARCHAR(20) DEFAULT 'grid',
  columns SMALLINT DEFAULT '3',
  gap INTEGER DEFAULT '10',
  settings TEXT,
  is_active SMALLINT DEFAULT '1',
  featured SMALLINT DEFAULT '0',
  sort_order INTEGER DEFAULT '0',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (layout_type IN ('grid', 'masonry', 'carousel', 'lightbox', 'justified')),
  UNIQUE (slug, tenant_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX image_galleries_idx_tenant_id ON image_galleries(tenant_id)");
            $pdo->exec("CREATE INDEX image_galleries_idx_is_active ON image_galleries(is_active)");
            $pdo->exec("CREATE INDEX image_galleries_idx_featured ON image_galleries(featured)");
            $pdo->exec("CREATE INDEX image_galleries_idx_layout_type ON image_galleries(layout_type)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN image_galleries.tenant_id IS 'NULL = galería global'");
            $pdo->exec("COMMENT ON COLUMN image_galleries.columns IS 'Número de columnas (1-6)'");
            $pdo->exec("COMMENT ON COLUMN image_galleries.gap IS 'Espacio entre imágenes en px'");
            $pdo->exec("COMMENT ON COLUMN image_galleries.settings IS 'Configuración adicional JSON'");
        }

        echo "✓ Table image_galleries created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `image_galleries`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS image_galleries");
        }

        echo "✓ Table image_galleries dropped\n";
    }
}
