<?php
/**
 * Migration: Create site_menu_items table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateSiteMenuItemsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `site_menu_items` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `parent` int(11) DEFAULT NULL,
                  `link` varchar(255) DEFAULT NULL,
                  `sort` int(11) DEFAULT 0,
                  `depth` int(11) DEFAULT 0,
                  `title` varchar(255) DEFAULT NULL,
                  `name` varchar(255) DEFAULT NULL,
                  `label` varchar(255) DEFAULT NULL,
                  `slug` varchar(255) DEFAULT NULL,
                  `type` varchar(50) DEFAULT NULL,
                  `target` varchar(50) DEFAULT NULL,
                  `menu_id` int(11) DEFAULT NULL,
                  `tenant_id` int(11) DEFAULT NULL,
                  `page_id` int(11) DEFAULT NULL,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `menu_id` (`menu_id`),
                  CONSTRAINT `fk_site_menu_items_menu` FOREIGN KEY (`menu_id`) REFERENCES `site_menus` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=99 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table site_menu_items created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `site_menu_items`");
        echo "✓ Table site_menu_items dropped\n";
    }
}
