<?php
/**
 * Migration: Create domain_contacts table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025-12-21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This table stores contact information for domain registrations.
 * Each contact can be reused for multiple domain registrations.
 */

use Screenart\Musedock\Database;

class CreateDomainContactsTable_2025_12_21_200100
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS domain_contacts (
                    id SERIAL PRIMARY KEY,
                    customer_id INT NOT NULL,

                    -- OpenProvider handle
                    openprovider_handle VARCHAR(50) NULL,

                    -- Contact type
                    type VARCHAR(20) DEFAULT 'owner' CHECK (type IN ('owner', 'admin', 'tech', 'billing')),

                    -- Personal info
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100) NOT NULL,
                    company VARCHAR(255) NULL,
                    email VARCHAR(255) NOT NULL,
                    phone VARCHAR(50) NOT NULL,

                    -- Address
                    address_street VARCHAR(255) NOT NULL,
                    address_number VARCHAR(20) NULL,
                    address_city VARCHAR(100) NOT NULL,
                    address_state VARCHAR(100) NULL,
                    address_zipcode VARCHAR(20) NOT NULL,
                    address_country VARCHAR(2) NOT NULL,

                    -- Flags
                    is_default SMALLINT DEFAULT 0,

                    -- Timestamps
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                    CONSTRAINT fk_domain_contacts_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
                )
            ");

            // Indexes
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_contacts_customer ON domain_contacts(customer_id)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_contacts_handle ON domain_contacts(openprovider_handle)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_domain_contacts_email ON domain_contacts(email)");

            // Trigger for updated_at
            $pdo->exec("
                CREATE OR REPLACE FUNCTION update_domain_contacts_updated_at()
                RETURNS TRIGGER AS \$\$
                BEGIN
                    NEW.updated_at = CURRENT_TIMESTAMP;
                    RETURN NEW;
                END;
                \$\$ LANGUAGE plpgsql
            ");

            $pdo->exec("
                DROP TRIGGER IF EXISTS trigger_domain_contacts_updated_at ON domain_contacts
            ");

            $pdo->exec("
                CREATE TRIGGER trigger_domain_contacts_updated_at
                BEFORE UPDATE ON domain_contacts
                FOR EACH ROW
                EXECUTE FUNCTION update_domain_contacts_updated_at()
            ");

            echo "✓ Created domain_contacts table (PostgreSQL)\n";

        } else {
            // MySQL/MariaDB
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS domain_contacts (
                    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    customer_id INT UNSIGNED NOT NULL,

                    -- OpenProvider handle
                    openprovider_handle VARCHAR(50) NULL,

                    -- Contact type
                    type ENUM('owner', 'admin', 'tech', 'billing') DEFAULT 'owner',

                    -- Personal info
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100) NOT NULL,
                    company VARCHAR(255) NULL,
                    email VARCHAR(255) NOT NULL,
                    phone VARCHAR(50) NOT NULL,

                    -- Address
                    address_street VARCHAR(255) NOT NULL,
                    address_number VARCHAR(20) NULL,
                    address_city VARCHAR(100) NOT NULL,
                    address_state VARCHAR(100) NULL,
                    address_zipcode VARCHAR(20) NOT NULL,
                    address_country VARCHAR(2) NOT NULL,

                    -- Flags
                    is_default TINYINT(1) DEFAULT 0,

                    -- Timestamps
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                    -- Foreign keys
                    CONSTRAINT fk_domain_contacts_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,

                    -- Indexes
                    INDEX idx_domain_contacts_customer (customer_id),
                    INDEX idx_domain_contacts_handle (openprovider_handle),
                    INDEX idx_domain_contacts_email (email)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");

            echo "✓ Created domain_contacts table (MySQL)\n";
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            $pdo->exec("DROP TRIGGER IF EXISTS trigger_domain_contacts_updated_at ON domain_contacts");
            $pdo->exec("DROP FUNCTION IF EXISTS update_domain_contacts_updated_at()");
        }

        $pdo->exec("DROP TABLE IF EXISTS domain_contacts");
        echo "✓ Dropped domain_contacts table\n";
    }
}
