<?php
/**
 * Migration: Create gallery_images table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateGalleryImagesTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `gallery_images` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `gallery_id` int(11) unsigned NOT NULL,
  `disk` varchar(50) NOT NULL DEFAULT 'local',
  `public_token` varchar(64) DEFAULT NULL,
  `file_name` varchar(255) NOT NULL COMMENT 'Nombre original del archivo',
  `file_path` varchar(500) NOT NULL COMMENT 'Ruta interna del archivo',
  `file_hash` varchar(64) DEFAULT NULL COMMENT 'Hash SHA256 para verificación',
  `file_size` int(11) unsigned DEFAULT '0' COMMENT 'Tamaño en bytes',
  `mime_type` varchar(100) DEFAULT NULL,
  `image_url` varchar(500) NOT NULL COMMENT 'URL pública permanente',
  `thumbnail_url` varchar(500) DEFAULT NULL COMMENT 'URL de miniatura',
  `medium_url` varchar(500) DEFAULT NULL COMMENT 'URL de tamaño medio',
  `title` varchar(255) DEFAULT NULL,
  `alt_text` varchar(255) DEFAULT NULL COMMENT 'Texto alternativo para SEO',
  `caption` text DEFAULT NULL COMMENT 'Descripción de la imagen',
  `link_url` varchar(500) DEFAULT NULL COMMENT 'URL de enlace opcional',
  `link_target` enum('_self','_blank') DEFAULT '_self',
  `width` int(11) unsigned DEFAULT NULL COMMENT 'Ancho original en px',
  `height` int(11) unsigned DEFAULT NULL COMMENT 'Alto original en px',
  `sort_order` int(11) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `metadata` longtext DEFAULT NULL COMMENT 'Metadatos EXIF y adicionales',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_gallery_id` (`gallery_id`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_file_hash` (`file_hash`),
  KEY `idx_public_token` (`public_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE gallery_images (
  id SERIAL PRIMARY KEY,
  gallery_id INTEGER NOT NULL,
  disk VARCHAR(50) NOT NULL DEFAULT 'local',
  public_token VARCHAR(64),
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_hash VARCHAR(64),
  file_size INTEGER DEFAULT '0',
  mime_type VARCHAR(100),
  image_url VARCHAR(500) NOT NULL,
  thumbnail_url VARCHAR(500),
  medium_url VARCHAR(500),
  title VARCHAR(255),
  alt_text VARCHAR(255),
  caption TEXT,
  link_url VARCHAR(500),
  link_target VARCHAR(20) DEFAULT '_self',
  width INTEGER,
  height INTEGER,
  sort_order INTEGER DEFAULT '0',
  is_active SMALLINT DEFAULT '1',
  metadata TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (link_target IN ('_self', '_blank'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX gallery_images_idx_gallery_id ON gallery_images(gallery_id)");
            $pdo->exec("CREATE INDEX gallery_images_idx_sort_order ON gallery_images(sort_order)");
            $pdo->exec("CREATE INDEX gallery_images_idx_is_active ON gallery_images(is_active)");
            $pdo->exec("CREATE INDEX gallery_images_idx_file_hash ON gallery_images(file_hash)");
            $pdo->exec("CREATE INDEX gallery_images_idx_public_token ON gallery_images(public_token)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN gallery_images.file_name IS 'Nombre original del archivo'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.file_path IS 'Ruta interna del archivo'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.file_hash IS 'Hash SHA256 para verificación'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.file_size IS 'Tamaño en bytes'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.image_url IS 'URL pública permanente'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.thumbnail_url IS 'URL de miniatura'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.medium_url IS 'URL de tamaño medio'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.alt_text IS 'Texto alternativo para SEO'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.caption IS 'Descripción de la imagen'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.link_url IS 'URL de enlace opcional'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.width IS 'Ancho original en px'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.height IS 'Alto original en px'");
            $pdo->exec("COMMENT ON COLUMN gallery_images.metadata IS 'Metadatos EXIF y adicionales'");
        }

        echo "✓ Table gallery_images created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `gallery_images`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS gallery_images");
        }

        echo "✓ Table gallery_images dropped\n";
    }
}
