<?php
/**
 * Migration: Create media_folders table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_091120
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateMediaFoldersTable_2025_12_11_091120
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `media_folders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL,
  `disk` varchar(50) DEFAULT 'media',
  `parent_id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `path` varchar(512) NOT NULL,
  `description` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_folder_path` (`tenant_id`, `path`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_path` (`path`),
  KEY `idx_media_folders_disk` (`disk`),
  KEY `idx_media_folders_disk_tenant` (`disk`, `tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE media_folders (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  disk VARCHAR(50) DEFAULT 'media',
  parent_id INTEGER,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  path VARCHAR(512) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, path)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX idx_tenant_id ON media_folders(tenant_id)");
            $pdo->exec("CREATE INDEX idx_parent_id ON media_folders(parent_id)");
            $pdo->exec("CREATE INDEX idx_path ON media_folders(path)");
            $pdo->exec("CREATE INDEX idx_media_folders_disk ON media_folders(disk)");
            $pdo->exec("CREATE INDEX idx_media_folders_disk_tenant ON media_folders(disk, tenant_id, parent_id)");
        }

        echo "✓ Table media_folders created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `media_folders`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS media_folders");
        }

        echo "✓ Table media_folders dropped\n";
    }
}
