<?php
/**
 * Migration: Create custom_form_fields table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateCustomFormFieldsTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `custom_form_fields` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` int(11) unsigned NOT NULL,
  `field_type` varchar(50) NOT NULL COMMENT 'text, email, textarea, select, etc.',
  `field_name` varchar(100) NOT NULL COMMENT 'Nombre interno del campo',
  `field_label` varchar(255) NOT NULL COMMENT 'Etiqueta visible',
  `placeholder` varchar(255) DEFAULT NULL,
  `default_value` text DEFAULT NULL,
  `help_text` varchar(500) DEFAULT NULL COMMENT 'Texto de ayuda bajo el campo',
  `options` longtext DEFAULT NULL COMMENT 'Opciones para select, radio, checkbox_group',
  `validation_rules` longtext DEFAULT NULL COMMENT 'Reglas de validación',
  `is_required` tinyint(1) DEFAULT '0',
  `min_length` int(11) DEFAULT NULL,
  `max_length` int(11) DEFAULT NULL,
  `min_value` decimal(15,2) DEFAULT NULL,
  `max_value` decimal(15,2) DEFAULT NULL,
  `pattern` varchar(500) DEFAULT NULL COMMENT 'Regex para validación',
  `error_message` varchar(500) DEFAULT NULL COMMENT 'Mensaje de error personalizado',
  `field_class` varchar(255) DEFAULT NULL COMMENT 'Clases CSS adicionales',
  `wrapper_class` varchar(255) DEFAULT NULL COMMENT 'Clases CSS del contenedor',
  `width` varchar(20) DEFAULT 'full' COMMENT 'full, half, third, quarter',
  `conditional_logic` longtext DEFAULT NULL COMMENT 'Lógica condicional',
  `sort_order` int(11) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_field_form` (`form_id`, `field_name`),
  KEY `idx_form_id` (`form_id`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_field_type` (`field_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE custom_form_fields (
  id SERIAL PRIMARY KEY,
  form_id INTEGER NOT NULL,
  field_type VARCHAR(50) NOT NULL,
  field_name VARCHAR(100) NOT NULL,
  field_label VARCHAR(255) NOT NULL,
  placeholder VARCHAR(255),
  default_value TEXT,
  help_text VARCHAR(500),
  \"options\" TEXT,
  validation_rules TEXT,
  is_required SMALLINT DEFAULT '0',
  min_length INTEGER,
  max_length INTEGER,
  min_value DECIMAL(15,2),
  max_value DECIMAL(15,2),
  pattern VARCHAR(500),
  error_message VARCHAR(500),
  field_class VARCHAR(255),
  wrapper_class VARCHAR(255),
  width VARCHAR(20) DEFAULT 'full',
  conditional_logic TEXT,
  sort_order INTEGER DEFAULT '0',
  is_active SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (form_id, field_name)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX custom_form_fields_idx_form_id ON custom_form_fields(form_id)");
            $pdo->exec("CREATE INDEX custom_form_fields_idx_sort_order ON custom_form_fields(sort_order)");
            $pdo->exec("CREATE INDEX custom_form_fields_idx_field_type ON custom_form_fields(field_type)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.field_type IS 'text, email, textarea, select, etc.'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.field_name IS 'Nombre interno del campo'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.field_label IS 'Etiqueta visible'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.help_text IS 'Texto de ayuda bajo el campo'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.\"options\" IS 'Opciones para select, radio, checkbox_group'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.validation_rules IS 'Reglas de validación'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.pattern IS 'Regex para validación'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.error_message IS 'Mensaje de error personalizado'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.field_class IS 'Clases CSS adicionales'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.wrapper_class IS 'Clases CSS del contenedor'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.width IS 'full, half, third, quarter'");
            $pdo->exec("COMMENT ON COLUMN custom_form_fields.conditional_logic IS 'Lógica condicional'");
        }

        echo "✓ Table custom_form_fields created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `custom_form_fields`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS custom_form_fields");
        }

        echo "✓ Table custom_form_fields dropped\n";
    }
}
