<?php
/**
 * Migration: Create customers table
 * Generated by MuseDock - Customer Registration System
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * Tabla de customers (4to nivel de usuarios) para registro público
 */

use Screenart\Musedock\Database;

class CreateCustomersTable_2025_01_01_000240
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS `customers` (
                    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                    `name` VARCHAR(255) NOT NULL,
                    `email` VARCHAR(255) NOT NULL UNIQUE,
                    `password` VARCHAR(255) NOT NULL COMMENT 'bcrypt hash',

                    -- Email verification
                    `email_verification_token` VARCHAR(100) NULL,
                    `email_verified_at` TIMESTAMP NULL,

                    -- Status management
                    `status` ENUM('active', 'suspended', 'pending_verification') NOT NULL DEFAULT 'pending_verification',

                    -- Company info (optional)
                    `company` VARCHAR(255) NULL,
                    `phone` VARCHAR(50) NULL,
                    `country` VARCHAR(2) NULL COMMENT 'ISO 3166-1 alpha-2',

                    -- Security tracking
                    `last_login_at` TIMESTAMP NULL,
                    `last_login_ip` VARCHAR(45) NULL COMMENT 'IPv4 or IPv6',
                    `failed_login_attempts` INT UNSIGNED NOT NULL DEFAULT 0,
                    `locked_until` TIMESTAMP NULL,

                    -- Timestamps
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                    -- Indexes for performance
                    INDEX `idx_status` (`status`),
                    INDEX `idx_email_verified` (`email_verified_at`),
                    INDEX `idx_created_at` (`created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS customers (
                    id SERIAL PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    email VARCHAR(255) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,

                    -- Email verification
                    email_verification_token VARCHAR(100) NULL,
                    email_verified_at TIMESTAMP NULL,

                    -- Status management
                    status VARCHAR(30) NOT NULL DEFAULT 'pending_verification'
                        CHECK (status IN ('active', 'suspended', 'pending_verification')),

                    -- Company info (optional)
                    company VARCHAR(255) NULL,
                    phone VARCHAR(50) NULL,
                    country VARCHAR(2) NULL,

                    -- Security tracking
                    last_login_at TIMESTAMP NULL,
                    last_login_ip VARCHAR(45) NULL,
                    failed_login_attempts INT NOT NULL DEFAULT 0,
                    locked_until TIMESTAMP NULL,

                    -- Timestamps
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_customers_status ON customers(status)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_customers_email_verified ON customers(email_verified_at)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_customers_created_at ON customers(created_at)");

            // Create trigger for updated_at
            $pdo->exec("
                CREATE OR REPLACE FUNCTION update_customers_updated_at()
                RETURNS TRIGGER AS $$
                BEGIN
                    NEW.updated_at = CURRENT_TIMESTAMP;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql
            ");

            $pdo->exec("DROP TRIGGER IF EXISTS trigger_customers_updated_at ON customers");
            $pdo->exec("
                CREATE TRIGGER trigger_customers_updated_at
                    BEFORE UPDATE ON customers
                    FOR EACH ROW
                    EXECUTE FUNCTION update_customers_updated_at()
            ");
        }

        echo "✓ Table customers created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            $pdo->exec("DROP TRIGGER IF EXISTS trigger_customers_updated_at ON customers");
            $pdo->exec("DROP FUNCTION IF EXISTS update_customers_updated_at()");
        }

        $pdo->exec("DROP TABLE IF EXISTS customers");
        echo "✓ Table customers dropped\n";
    }
}
