<?php
/**
 * Migration: Create slugs table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateSlugsTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `slugs` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL,
                  `module` varchar(50) NOT NULL,
                  `reference_id` int(11) NOT NULL,
                  `slug` varchar(255) NOT NULL,
                  `prefix` varchar(50) DEFAULT NULL,
                  `locale` varchar(5) DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `uniq_slug` (`tenant_id`,`slug`,`prefix`),
                  UNIQUE KEY `slug_unique` (`slug`,`module`,`reference_id`,`tenant_id`,`prefix`),
                  UNIQUE KEY `unique_slug` (`module`,`reference_id`,`slug`,`tenant_id`,`prefix`),
                  KEY `idx_slugs_tenant` (`tenant_id`),
                  KEY `idx_slugs_module_reference` (`module`,`reference_id`),
                  KEY `idx_slugs_slug` (`slug`),
                  CONSTRAINT `fk_slugs_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=495 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table slugs created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `slugs`");
        echo "✓ Table slugs dropped\n";
    }
}
