<?php
/**
 * Migration: Add slug column to roles table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_12_120000
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class AddSlugToRolesTable_2025_12_12_120000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            // Check if column already exists
            $stmt = $pdo->query("SHOW COLUMNS FROM `roles` LIKE 'slug'");
            if ($stmt->fetch()) {
                echo "✓ Column slug already exists in roles table\n";
                return;
            }

            $pdo->exec("ALTER TABLE `roles` ADD COLUMN `slug` VARCHAR(100) NULL AFTER `name`");

            // Update existing roles with slug based on name
            $pdo->exec("UPDATE `roles` SET `slug` = LOWER(REPLACE(`name`, ' ', '_')) WHERE `slug` IS NULL");

            // Add index
            $pdo->exec("CREATE INDEX `idx_roles_slug` ON `roles`(`slug`)");
        } else {
            // PostgreSQL - Check if column exists
            $stmt = $pdo->prepare("
                SELECT column_name FROM information_schema.columns
                WHERE table_name = 'roles' AND column_name = 'slug'
            ");
            $stmt->execute();
            if ($stmt->fetch()) {
                echo "✓ Column slug already exists in roles table\n";
                return;
            }

            $pdo->exec("ALTER TABLE roles ADD COLUMN slug VARCHAR(100)");

            // Update existing roles with slug based on name
            $pdo->exec("UPDATE roles SET slug = LOWER(REPLACE(name, ' ', '_')) WHERE slug IS NULL");

            // Add index
            $pdo->exec("CREATE INDEX idx_roles_slug ON roles(slug)");
        }

        echo "✓ Column slug added to roles table\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            try {
                $pdo->exec("DROP INDEX `idx_roles_slug` ON `roles`");
            } catch (\Exception $e) {
                // Index may not exist
            }
            $pdo->exec("ALTER TABLE `roles` DROP COLUMN IF EXISTS `slug`");
        } else {
            try {
                $pdo->exec("DROP INDEX IF EXISTS idx_roles_slug");
            } catch (\Exception $e) {
                // Index may not exist
            }
            $pdo->exec("ALTER TABLE roles DROP COLUMN IF EXISTS slug");
        }

        echo "✓ Column slug removed from roles table\n";
    }
}
