<?php
/**
 * Migration: Fix include_www and is_subdomain to use SMALLINT consistently
 * Generated by MuseDock - Customer Registration System
 * Compatible with: PostgreSQL only
 *
 * Convierte is_subdomain de BOOLEAN a SMALLINT para consistencia
 * Mantiene include_www como SMALLINT y elimina DEFAULT problemático
 */

use Screenart\Musedock\Database;

class FixIncludeWwwType_2025_01_01_000256
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        // Solo aplicar en PostgreSQL
        if ($driver === 'pgsql') {
            try {
                // 1. Convertir is_subdomain de BOOLEAN a SMALLINT
                $stmt = $pdo->query("
                    SELECT data_type
                    FROM information_schema.columns
                    WHERE table_name = 'tenants'
                    AND column_name = 'is_subdomain'
                ");

                $result = $stmt->fetch(PDO::FETCH_ASSOC);

                if ($result && $result['data_type'] === 'boolean') {
                    $pdo->exec("
                        ALTER TABLE tenants
                        ALTER COLUMN is_subdomain TYPE SMALLINT
                        USING CASE
                            WHEN is_subdomain = TRUE THEN 1
                            ELSE 0
                        END
                    ");

                    $pdo->exec("
                        ALTER TABLE tenants
                        ALTER COLUMN is_subdomain SET DEFAULT 0
                    ");

                    echo "✓ Column is_subdomain converted from BOOLEAN to SMALLINT\n";
                }

                // 2. Asegurar que include_www no tenga DEFAULT problemático
                $pdo->exec("
                    ALTER TABLE tenants
                    ALTER COLUMN include_www DROP DEFAULT
                ");

                $pdo->exec("
                    ALTER TABLE tenants
                    ALTER COLUMN include_www SET DEFAULT 1
                ");

                echo "✓ Column include_www default fixed\n";

            } catch (\Exception $e) {
                echo "⚠ Error converting columns: " . $e->getMessage() . "\n";
                // No fallar la migración, solo advertir
            }
        } else {
            echo "⚠ MySQL/MariaDB already uses TINYINT(1), no conversion needed\n";
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            try {
                // Revertir is_subdomain a BOOLEAN
                $pdo->exec("
                    ALTER TABLE tenants
                    ALTER COLUMN is_subdomain TYPE BOOLEAN
                    USING CASE
                        WHEN is_subdomain = 1 THEN TRUE
                        ELSE FALSE
                    END
                ");

                $pdo->exec("
                    ALTER TABLE tenants
                    ALTER COLUMN is_subdomain SET DEFAULT FALSE
                ");

                echo "✓ Column is_subdomain reverted to BOOLEAN\n";
            } catch (\Exception $e) {
                echo "⚠ Error reverting columns: " . $e->getMessage() . "\n";
            }
        }
    }
}
