<?php
/**
 * Migration: Create support_ticket_messages table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateSupportTicketMessagesTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `support_ticket_messages` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `ticket_id` int(11) NOT NULL COMMENT 'ID del ticket',
                  `user_id` int(11) NOT NULL COMMENT 'ID del usuario que escribe',
                  `user_type` enum('admin','super_admin') NOT NULL COMMENT 'Tipo de usuario',
                  `message` text NOT NULL COMMENT 'Mensaje',
                  `is_internal` tinyint(1) DEFAULT 0 COMMENT '1 = Nota interna (solo staff)',
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `ticket_id` (`ticket_id`),
                  KEY `user_type` (`user_type`,`user_id`),
                  KEY `created_at` (`created_at`),
                  CONSTRAINT `fk_ticket_messages_ticket` FOREIGN KEY (`ticket_id`) REFERENCES `support_tickets` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Mensajes/respuestas de tickets'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table support_ticket_messages created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `support_ticket_messages`");
        echo "✓ Table support_ticket_messages dropped\n";
    }
}
