<?php
/**
 * Migration: Create modules table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateModulesTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `version` varchar(20) DEFAULT NULL,
  `author` varchar(100) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `public` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `slug_prefix` varchar(50) DEFAULT NULL,
  `has_slugs` tinyint(1) DEFAULT '0',
  `cms_enabled` tinyint(1) DEFAULT '1',
  `tenant_enabled_default` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Si está habilitado por defecto para nuevos tenants',
  `installed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de instalación',
  `updated_at` timestamp DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE modules (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(100),
  name VARCHAR(100),
  description TEXT,
  \"version\" VARCHAR(20),
  author VARCHAR(100),
  active SMALLINT DEFAULT '1',
  public SMALLINT DEFAULT '0',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  slug_prefix VARCHAR(50),
  has_slugs SMALLINT DEFAULT '0',
  cms_enabled SMALLINT DEFAULT '1',
  tenant_enabled_default SMALLINT NOT NULL DEFAULT '1',
  installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  UNIQUE (slug)
)
            ");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN modules.tenant_enabled_default IS 'Si está habilitado por defecto para nuevos tenants'");
            $pdo->exec("COMMENT ON COLUMN modules.installed_at IS 'Fecha de instalación'");
        }

        echo "✓ Table modules created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `modules`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS modules");
        }

        echo "✓ Table modules dropped\n";
    }
}
