<?php
/**
 * Migration: Create tenant_default_settings table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_120000
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateTenantDefaultSettingsTable_2025_12_11_120000
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_default_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `setting_type` enum('json','string','boolean','integer') NOT NULL DEFAULT 'string',
  `description` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");

            // Insert default settings
            $this->insertDefaultSettings($pdo);
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE tenant_default_settings (
  id SERIAL PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT,
  setting_type VARCHAR(20) NOT NULL DEFAULT 'string',
  description VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (setting_type IN ('json', 'string', 'boolean', 'integer'))
)
            ");

            // Create trigger for updated_at
            $pdo->exec("
                CREATE OR REPLACE FUNCTION update_tenant_default_settings_updated_at()
                RETURNS TRIGGER AS \$\$
                BEGIN
                    NEW.updated_at = CURRENT_TIMESTAMP;
                    RETURN NEW;
                END;
                \$\$ language 'plpgsql';
            ");

            $pdo->exec("
                CREATE TRIGGER update_tenant_default_settings_updated_at
                BEFORE UPDATE ON tenant_default_settings
                FOR EACH ROW
                EXECUTE FUNCTION update_tenant_default_settings_updated_at();
            ");

            // Insert default settings
            $this->insertDefaultSettings($pdo);
        }

        echo "✓ Table tenant_default_settings created\n";
    }

    private function insertDefaultSettings(PDO $pdo)
    {
        $defaultPermissions = json_encode([
            'view_dashboard',
            'manage_content',
            'view_content',
            'manage_media',
            'view_media',
            'manage_users',
            'view_users',
            'manage_settings',
            'view_settings',
            'manage_pages',
            'view_pages',
            'manage_posts',
            'view_posts',
            'manage_categories',
            'view_categories',
            'manage_comments',
            'view_comments',
            'manage_menus',
            'view_menus',
            'manage_themes',
            'view_themes',
            'manage_plugins'
        ]);

        $defaultRoles = json_encode([
            ['name' => 'Admin', 'slug' => 'admin', 'description' => 'Administrador del tenant con acceso completo'],
            ['name' => 'Editor', 'slug' => 'editor', 'description' => 'Editor de contenido'],
            ['name' => 'Viewer', 'slug' => 'viewer', 'description' => 'Solo lectura']
        ]);

        $settings = [
            [
                'setting_key' => 'default_permissions',
                'setting_value' => $defaultPermissions,
                'setting_type' => 'json',
                'description' => 'Permisos que se asignan al rol Admin por defecto'
            ],
            [
                'setting_key' => 'default_roles',
                'setting_value' => $defaultRoles,
                'setting_type' => 'json',
                'description' => 'Roles que se crean por defecto para cada tenant'
            ],
            [
                'setting_key' => 'copy_menus_from_admin',
                'setting_value' => '1',
                'setting_type' => 'boolean',
                'description' => 'Copiar menús desde admin_menus al crear tenant'
            ],
            [
                'setting_key' => 'default_theme',
                'setting_value' => 'default',
                'setting_type' => 'string',
                'description' => 'Tema por defecto para nuevos tenants'
            ],
            [
                'setting_key' => 'assign_admin_role_to_creator',
                'setting_value' => '1',
                'setting_type' => 'boolean',
                'description' => 'Asignar rol Admin al usuario creador del tenant'
            ]
        ];

        $stmt = $pdo->prepare("
            INSERT INTO tenant_default_settings (setting_key, setting_value, setting_type, description)
            VALUES (:setting_key, :setting_value, :setting_type, :description)
        ");

        foreach ($settings as $setting) {
            $stmt->execute($setting);
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `tenant_default_settings`");
        } else {
            $pdo->exec("DROP TRIGGER IF EXISTS update_tenant_default_settings_updated_at ON tenant_default_settings");
            $pdo->exec("DROP FUNCTION IF EXISTS update_tenant_default_settings_updated_at()");
            $pdo->exec("DROP TABLE IF EXISTS tenant_default_settings");
        }

        echo "✓ Table tenant_default_settings dropped\n";
    }
}
