<?php
/**
 * Migration: Create superadmin_plugin_menus table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginMenusTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_menus` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `plugin_id` int(11) NOT NULL COMMENT 'ID del plugin',
                  `parent_id` int(11) DEFAULT NULL COMMENT 'ID del menú padre (para submenús)',
                  `title` varchar(255) NOT NULL COMMENT 'Título del menú',
                  `icon` varchar(100) DEFAULT NULL COMMENT 'Icono del menú',
                  `icon_type` varchar(20) DEFAULT 'bi' COMMENT 'Tipo de icono (bi, fas, etc.)',
                  `url` varchar(500) DEFAULT NULL COMMENT 'URL del menú',
                  `permission` varchar(255) DEFAULT NULL COMMENT 'Permiso requerido',
                  `order` int(11) DEFAULT 0 COMMENT 'Orden de visualización',
                  `is_active` tinyint(1) DEFAULT 1 COMMENT '1 = Activo, 0 = Inactivo',
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `plugin_id` (`plugin_id`),
                  KEY `parent_id` (`parent_id`),
                  KEY `is_active` (`is_active`),
                  CONSTRAINT `fk_plugin_menus_plugin` FOREIGN KEY (`plugin_id`) REFERENCES `superadmin_plugins` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Menús agregados al panel por plugins'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table superadmin_plugin_menus created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_menus`");
        echo "✓ Table superadmin_plugin_menus dropped\n";
    }
}
