<?php
/**
 * Migration: Create blog_categories table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateBlogCategoriesTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_categories` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para categorías globales)',
                  `parent_id` int(10) unsigned DEFAULT NULL COMMENT 'ID de la categoría padre (para jerarquía)',
                  `name` varchar(255) NOT NULL COMMENT 'Nombre de la categoría',
                  `slug` varchar(300) NOT NULL COMMENT 'URL amigable',
                  `description` text DEFAULT NULL COMMENT 'Descripción de la categoría',
                  `image` varchar(500) DEFAULT NULL COMMENT 'Imagen de la categoría',
                  `color` varchar(7) DEFAULT NULL COMMENT 'Color en formato hexadecimal',
                  `order` int(11) NOT NULL DEFAULT 0 COMMENT 'Orden de visualización',
                  `post_count` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Contador de posts',
                  `seo_title` varchar(500) DEFAULT NULL COMMENT 'Título para SEO',
                  `seo_description` text DEFAULT NULL COMMENT 'Descripción para SEO',
                  `seo_keywords` text DEFAULT NULL COMMENT 'Palabras clave',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  `deleted_at` datetime DEFAULT NULL COMMENT 'Fecha y hora de eliminación lógica',
                  `deleted_by` int(11) DEFAULT NULL COMMENT 'ID del usuario que eliminó el registro',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_slug` (`tenant_id`,`slug`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_parent_id` (`parent_id`),
                  KEY `idx_slug` (`slug`),
                  KEY `idx_order` (`order`),
                  KEY `idx_blog_categories_deleted_at` (`deleted_at`),
                  KEY `idx_blog_categories_tenant` (`tenant_id`),
                  KEY `idx_blog_categories_slug` (`slug`),
                  KEY `idx_blog_categories_parent` (`parent_id`),
                  CONSTRAINT `fk_blog_categories_parent` FOREIGN KEY (`parent_id`) REFERENCES `blog_categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                  CONSTRAINT `fk_blog_categories_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_categories created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_categories`");
        echo "✓ Table blog_categories dropped\n";
    }
}
