<?php
/**
 * Migration: Create blog_tags table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateBlogTagsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_tags` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para etiquetas globales)',
                  `name` varchar(100) NOT NULL COMMENT 'Nombre de la etiqueta',
                  `slug` varchar(150) NOT NULL COMMENT 'URL amigable',
                  `description` text DEFAULT NULL COMMENT 'Descripción de la etiqueta',
                  `color` varchar(7) DEFAULT NULL COMMENT 'Color en formato hexadecimal',
                  `post_count` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Contador de posts',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  `deleted_at` datetime DEFAULT NULL COMMENT 'Fecha y hora de eliminación lógica',
                  `deleted_by` int(11) DEFAULT NULL COMMENT 'ID del usuario que eliminó el registro',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_tenant_slug` (`tenant_id`,`slug`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_slug` (`slug`),
                  KEY `idx_blog_tags_deleted_at` (`deleted_at`),
                  KEY `idx_blog_tags_tenant` (`tenant_id`),
                  KEY `idx_blog_tags_slug` (`slug`),
                  CONSTRAINT `fk_blog_tags_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_tags created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_tags`");
        echo "✓ Table blog_tags dropped\n";
    }
}
