<?php
/**
 * Migration: Add site_subtitle setting to tenant_settings
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_21
 * Compatible with: MySQL/MariaDB + PostgreSQL
 *
 * This migration adds a new 'site_subtitle' setting that is separate from
 * 'site_description' (which is for SEO purposes only).
 * The subtitle is what gets displayed visually in the header when enabled.
 */

use Screenart\Musedock\Database;

class AddSiteSubtitleSetting_2025_12_21_000002
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        // Get all tenants that have site_description but no site_subtitle
        // and copy the value to site_subtitle for backwards compatibility
        $keyCol = $driver === 'pgsql' ? '"key"' : '`key`';

        $stmt = $pdo->query("
            SELECT DISTINCT tenant_id, value
            FROM tenant_settings
            WHERE {$keyCol} = 'site_description'
            AND tenant_id NOT IN (
                SELECT tenant_id FROM tenant_settings WHERE {$keyCol} = 'site_subtitle'
            )
        ");

        $tenants = $stmt->fetchAll(\PDO::FETCH_ASSOC);

        foreach ($tenants as $tenant) {
            $insertStmt = $pdo->prepare("
                INSERT INTO tenant_settings (tenant_id, {$keyCol}, value)
                VALUES (?, 'site_subtitle', ?)
            ");
            $insertStmt->execute([$tenant['tenant_id'], $tenant['value'] ?? '']);
        }

        $count = count($tenants);
        echo "✓ Added site_subtitle setting for {$count} tenant(s)\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);

        $keyCol = $driver === 'pgsql' ? '"key"' : '`key`';

        $stmt = $pdo->prepare("DELETE FROM tenant_settings WHERE {$keyCol} = 'site_subtitle'");
        $stmt->execute();

        $count = $stmt->rowCount();
        echo "✓ Removed site_subtitle setting from {$count} tenant(s)\n";
    }
}
