<?php
/**
 * Migration: Create ai_providers table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_014411
 */

use Screenart\Musedock\Database;

class CreateAiProvidersTable_2025_12_08_014411
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `ai_providers` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `name` varchar(100) NOT NULL,
                  `api_key` varchar(255) DEFAULT NULL,
                  `endpoint` varchar(255) DEFAULT NULL,
                  `provider_type` enum('openai','claude','gemini','other') NOT NULL DEFAULT 'openai',
                  `model` varchar(100) DEFAULT 'gpt-4',
                  `temperature` float DEFAULT 0.7,
                  `max_tokens` int(11) DEFAULT 1000,
                  `active` tinyint(1) DEFAULT 0,
                  `system_wide` tinyint(1) DEFAULT 0,
                  `tenant_id` int(11) DEFAULT NULL,
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `name` (`name`,`tenant_id`)
                ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table ai_providers created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `ai_providers`");
        echo "✓ Table ai_providers dropped\n";
    }
}
