<?php
/**
 * Migration: Create superadmin_plugin_routes table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateSuperadminPluginRoutesTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `superadmin_plugin_routes` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `plugin_id` int(11) NOT NULL COMMENT 'ID del plugin',
                  `method` varchar(10) NOT NULL COMMENT 'GET, POST, PUT, DELETE, etc.',
                  `path` varchar(500) NOT NULL COMMENT 'Ruta del endpoint',
                  `controller` varchar(500) NOT NULL COMMENT 'Controlador',
                  `action` varchar(255) NOT NULL COMMENT 'Método del controlador',
                  `middleware` text DEFAULT NULL COMMENT 'Middlewares (JSON array)',
                  `name` varchar(255) DEFAULT NULL COMMENT 'Nombre de la ruta',
                  `is_active` tinyint(1) DEFAULT 1 COMMENT '1 = Activa, 0 = Inactiva',
                  `created_at` datetime DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `plugin_id` (`plugin_id`),
                  KEY `is_active` (`is_active`),
                  CONSTRAINT `fk_plugin_routes_plugin` FOREIGN KEY (`plugin_id`) REFERENCES `superadmin_plugins` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Rutas registradas por plugins'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table superadmin_plugin_routes created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `superadmin_plugin_routes`");
        echo "✓ Table superadmin_plugin_routes dropped\n";
    }
}
