<?php
/**
 * Migration: Fix include_www and is_subdomain to use SMALLINT consistently
 * Generated by MuseDock - Customer Registration System
 * Compatible with: PostgreSQL only
 *
 * Convierte is_subdomain de BOOLEAN a SMALLINT para consistencia
 * Mantiene include_www como SMALLINT y elimina DEFAULT problemático
 */

use Screenart\Musedock\Database;

class FixIncludeWwwType_2025_01_01_000256
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        // Solo aplicar en PostgreSQL
        if ($driver === 'pgsql') {
            try {
                // 1. Arreglar is_subdomain (puede ser BOOLEAN o SMALLINT con DEFAULT incorrecto)
                $stmt = $pdo->query("
                    SELECT data_type, column_default
                    FROM information_schema.columns
                    WHERE table_name = 'tenants'
                    AND column_name = 'is_subdomain'
                ");

                $result = $stmt->fetch(PDO::FETCH_ASSOC);

                if ($result) {
                    // Primero eliminar DEFAULT si existe
                    try {
                        $pdo->exec("ALTER TABLE tenants ALTER COLUMN is_subdomain DROP DEFAULT");
                    } catch (\Exception $e) {
                        // Puede no tener DEFAULT
                    }

                    // Convertir a SMALLINT si es BOOLEAN
                    if ($result['data_type'] === 'boolean') {
                        $pdo->exec("
                            ALTER TABLE tenants
                            ALTER COLUMN is_subdomain TYPE SMALLINT
                            USING CASE
                                WHEN is_subdomain = TRUE THEN 1
                                ELSE 0
                            END
                        ");
                        echo "✓ Column is_subdomain converted from BOOLEAN to SMALLINT\n";
                    }

                    // Establecer DEFAULT correcto
                    $pdo->exec("ALTER TABLE tenants ALTER COLUMN is_subdomain SET DEFAULT 0");
                    echo "✓ Column is_subdomain default set to 0\n";
                }

                // 2. Arreglar cloudflare_proxied (puede ser BOOLEAN o SMALLINT)
                $stmt = $pdo->query("
                    SELECT data_type, column_default
                    FROM information_schema.columns
                    WHERE table_name = 'tenants'
                    AND column_name = 'cloudflare_proxied'
                ");

                $result = $stmt->fetch(PDO::FETCH_ASSOC);

                if ($result) {
                    // Primero eliminar DEFAULT si existe
                    try {
                        $pdo->exec("ALTER TABLE tenants ALTER COLUMN cloudflare_proxied DROP DEFAULT");
                    } catch (\Exception $e) {
                        // Puede no tener DEFAULT
                    }

                    // Convertir a SMALLINT si es BOOLEAN
                    if ($result['data_type'] === 'boolean') {
                        $pdo->exec("
                            ALTER TABLE tenants
                            ALTER COLUMN cloudflare_proxied TYPE SMALLINT
                            USING CASE
                                WHEN cloudflare_proxied = TRUE THEN 1
                                ELSE 0
                            END
                        ");
                        echo "✓ Column cloudflare_proxied converted from BOOLEAN to SMALLINT\n";
                    }

                    // Establecer DEFAULT correcto
                    $pdo->exec("ALTER TABLE tenants ALTER COLUMN cloudflare_proxied SET DEFAULT 1");
                    echo "✓ Column cloudflare_proxied default set to 1\n";
                }

                // 3. Asegurar que include_www tenga DEFAULT correcto
                try {
                    $pdo->exec("ALTER TABLE tenants ALTER COLUMN include_www DROP DEFAULT");
                } catch (\Exception $e) {
                    // Puede no tener DEFAULT
                }

                $pdo->exec("ALTER TABLE tenants ALTER COLUMN include_www SET DEFAULT 1");
                echo "✓ Column include_www default set to 1\n";

            } catch (\Exception $e) {
                echo "⚠ Error converting columns: " . $e->getMessage() . "\n";
                // No fallar la migración, solo advertir
            }
        } else {
            echo "⚠ MySQL/MariaDB already uses TINYINT(1), no conversion needed\n";
        }
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'pgsql') {
            try {
                // No revertir - mantener SMALLINT es la solución correcta
                // Solo advertir que el rollback no hace nada
                echo "⚠ Rollback skipped: SMALLINT is the correct type for compatibility\n";
            } catch (\Exception $e) {
                echo "⚠ Error in rollback: " . $e->getMessage() . "\n";
            }
        }
    }
}
