<?php
/**
 * Migration: Create tenant_themes table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104034
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateTenantThemesTable_2025_12_11_104034
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_themes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `version` varchar(20) NOT NULL DEFAULT '1.0.0',
  `author` varchar(255) DEFAULT NULL,
  `screenshot` varchar(255) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `validated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Pasó validación de seguridad',
  `security_score` tinyint(3) unsigned DEFAULT NULL COMMENT 'Score de seguridad 0-100',
  `installed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT NULL,
  `settings` text DEFAULT NULL COMMENT 'JSON con configuración del tema',
  `validation_errors` text DEFAULT NULL COMMENT 'JSON con errores de validación',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_theme` (`tenant_id`, `slug`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_active` (`active`),
  KEY `idx_validated` (`validated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE tenant_themes (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  slug VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  \"version\" VARCHAR(20) NOT NULL DEFAULT '1.0.0',
  author VARCHAR(255),
  screenshot VARCHAR(255),
  active SMALLINT NOT NULL DEFAULT '0',
  validated SMALLINT NOT NULL DEFAULT '0',
  security_score INTEGER,
  installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  settings TEXT,
  validation_errors TEXT,
  UNIQUE (tenant_id, slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX tenant_themes_idx_tenant_id ON tenant_themes(tenant_id)");
            $pdo->exec("CREATE INDEX tenant_themes_idx_active ON tenant_themes(active)");
            $pdo->exec("CREATE INDEX tenant_themes_idx_validated ON tenant_themes(validated)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN tenant_themes.validated IS 'Pasó validación de seguridad'");
            $pdo->exec("COMMENT ON COLUMN tenant_themes.security_score IS 'Score de seguridad 0-100'");
            $pdo->exec("COMMENT ON COLUMN tenant_themes.settings IS 'JSON con configuración del tema'");
            $pdo->exec("COMMENT ON COLUMN tenant_themes.validation_errors IS 'JSON con errores de validación'");
        }

        echo "✓ Table tenant_themes created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `tenant_themes`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS tenant_themes");
        }

        echo "✓ Table tenant_themes dropped\n";
    }
}
