<?php
/**
 * Migration: Create blog_post_meta table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateBlogPostMetaTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_meta` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
                  `meta_key` varchar(255) NOT NULL COMMENT 'Clave del metadato',
                  `meta_value` longtext DEFAULT NULL COMMENT 'Valor del metadato',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_post_meta_key` (`post_id`,`meta_key`),
                  KEY `idx_post_id` (`post_id`),
                  KEY `idx_meta_key` (`meta_key`),
                  CONSTRAINT `fk_bpm_post` FOREIGN KEY (`post_id`) REFERENCES `blog_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_post_meta created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_post_meta`");
        echo "✓ Table blog_post_meta dropped\n";
    }
}
