<?php
/**
 * Migration: Create custom_forms table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateCustomFormsTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `custom_forms` (
                  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) unsigned DEFAULT NULL COMMENT 'NULL = formulario global',
                  `name` varchar(255) NOT NULL,
                  `slug` varchar(255) NOT NULL,
                  `description` text DEFAULT NULL,
                  `submit_button_text` varchar(100) DEFAULT 'Enviar',
                  `success_message` text DEFAULT NULL,
                  `error_message` text DEFAULT NULL,
                  `redirect_url` varchar(500) DEFAULT NULL COMMENT 'URL de redirección tras envío',
                  `email_to` varchar(500) DEFAULT NULL COMMENT 'Emails separados por coma',
                  `email_subject` varchar(255) DEFAULT NULL,
                  `email_from_name` varchar(100) DEFAULT NULL,
                  `email_from_email` varchar(255) DEFAULT NULL,
                  `email_reply_to` varchar(255) DEFAULT NULL,
                  `send_confirmation_email` tinyint(1) DEFAULT 0,
                  `confirmation_email_subject` varchar(255) DEFAULT NULL,
                  `confirmation_email_message` text DEFAULT NULL,
                  `store_submissions` tinyint(1) DEFAULT 1,
                  `enable_recaptcha` tinyint(1) DEFAULT 0,
                  `form_class` varchar(255) DEFAULT NULL COMMENT 'Clases CSS adicionales',
                  `settings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Configuración adicional JSON' CHECK (json_valid(`settings`)),
                  `is_active` tinyint(1) DEFAULT 1,
                  `submissions_count` int(11) unsigned DEFAULT 0,
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_slug_tenant` (`slug`,`tenant_id`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_is_active` (`is_active`),
                  KEY `idx_created_at` (`created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table custom_forms created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `custom_forms`");
        echo "✓ Table custom_forms dropped\n";
    }
}
