<?php
/**
 * Migration: Create slider_slides table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102306
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSliderSlidesTable_2025_12_11_102306
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `slider_slides` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slider_id` int(10) unsigned NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `link_url` varchar(255) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_slider_slides_slider_id` (`slider_id`),
  KEY `idx_slider_slides_order` (`sort_order`),
  KEY `idx_slider_slides_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE slider_slides (
  id SERIAL PRIMARY KEY,
  slider_id INTEGER NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  title VARCHAR(255),
  description TEXT,
  link_url VARCHAR(255),
  sort_order INTEGER NOT NULL DEFAULT '0',
  is_active SMALLINT NOT NULL DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX slider_slides_idx_slider_slides_slider_id ON slider_slides(slider_id)");
            $pdo->exec("CREATE INDEX slider_slides_idx_slider_slides_order ON slider_slides(sort_order)");
            $pdo->exec("CREATE INDEX slider_slides_idx_slider_slides_active ON slider_slides(is_active)");
        }

        echo "✓ Table slider_slides created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `slider_slides`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS slider_slides");
        }

        echo "✓ Table slider_slides dropped\n";
    }
}
