<?php
/**
 * Migration: Create media table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_104752
 */

use Screenart\Musedock\Database;

class CreateMediaTable_2025_12_08_104752
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver->getDriverName() === 'mysql') {
            $pdo->exec("
                CREATE TABLE `media` (
                  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(10) unsigned DEFAULT NULL,
                  `folder_id` int(11) DEFAULT NULL,
                  `user_id` bigint(20) unsigned DEFAULT NULL,
                  `disk` varchar(50) NOT NULL,
                  `path` text NOT NULL,
                  `public_token` varchar(32) DEFAULT NULL,
                  `filename` varchar(255) NOT NULL,
                  `mime_type` varchar(100) DEFAULT NULL,
                  `size` bigint(20) unsigned NOT NULL DEFAULT 0,
                  `alt_text` varchar(255) DEFAULT NULL,
                  `caption` text DEFAULT NULL,
                  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
                  `created_at` timestamp NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `idx_media_tenant_id` (`tenant_id`),
                  KEY `idx_media_user_id` (`user_id`),
                  KEY `idx_media_disk_path` (`disk`(10),`path`(191)),
                  KEY `idx_folder_id` (`folder_id`),
                  CONSTRAINT `media_ibfk_1` FOREIGN KEY (`folder_id`) REFERENCES `media_folders` (`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table media created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `media`");
        echo "✓ Table media dropped\n";
    }
}
