<?php
/**
 * Migration: Create support_ticket_stats table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104034
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSupportTicketStatsTable_2025_12_11_104034
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `support_ticket_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL COMMENT 'ID del tenant',
  `total_tickets` int(11) DEFAULT '0',
  `open_tickets` int(11) DEFAULT '0',
  `in_progress_tickets` int(11) DEFAULT '0',
  `resolved_tickets` int(11) DEFAULT '0',
  `closed_tickets` int(11) DEFAULT '0',
  `avg_response_time` int(11) DEFAULT NULL COMMENT 'Tiempo promedio de respuesta (minutos)',
  `avg_resolution_time` int(11) DEFAULT NULL COMMENT 'Tiempo promedio de resolución (horas)',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE support_ticket_stats (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  total_tickets INTEGER DEFAULT '0',
  open_tickets INTEGER DEFAULT '0',
  in_progress_tickets INTEGER DEFAULT '0',
  resolved_tickets INTEGER DEFAULT '0',
  closed_tickets INTEGER DEFAULT '0',
  avg_response_time INTEGER,
  avg_resolution_time INTEGER,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id)
)
            ");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN support_ticket_stats.tenant_id IS 'ID del tenant'");
            $pdo->exec("COMMENT ON COLUMN support_ticket_stats.avg_response_time IS 'Tiempo promedio de respuesta (minutos)'");
            $pdo->exec("COMMENT ON COLUMN support_ticket_stats.avg_resolution_time IS 'Tiempo promedio de resolución (horas)'");
        }

        echo "✓ Table support_ticket_stats created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `support_ticket_stats`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS support_ticket_stats");
        }

        echo "✓ Table support_ticket_stats dropped\n";
    }
}
