<?php
/**
 * Migration: Create languages table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102306
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateLanguagesTable_2025_12_11_102306
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `languages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(10) NOT NULL,
  `name` varchar(100) NOT NULL,
  `active` tinyint(1) DEFAULT '1',
  `order_position` int(11) DEFAULT '0',
  `tenant_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE languages (
  id SERIAL PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(100) NOT NULL,
  active SMALLINT DEFAULT '1',
  order_position INTEGER DEFAULT '0',
  tenant_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");
        }

        echo "✓ Table languages created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `languages`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS languages");
        }

        echo "✓ Table languages dropped\n";
    }
}
