<?php
/**
 * Migration: Create blog_post_translations table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateBlogPostTranslationsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_translations` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant',
                  `locale` varchar(10) NOT NULL COMMENT 'Código de idioma (es, en, fr, etc.)',
                  `title` varchar(500) NOT NULL COMMENT 'Título traducido',
                  `excerpt` text DEFAULT NULL COMMENT 'Extracto traducido',
                  `content` longtext NOT NULL COMMENT 'Contenido traducido',
                  `seo_title` varchar(500) DEFAULT NULL COMMENT 'Título SEO traducido',
                  `seo_description` text DEFAULT NULL COMMENT 'Descripción SEO traducida',
                  `seo_keywords` text DEFAULT NULL COMMENT 'Palabras clave traducidas',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_bpt_post_locale` (`post_id`,`locale`),
                  KEY `idx_bpt_post_id` (`post_id`),
                  KEY `idx_bpt_locale` (`locale`),
                  KEY `idx_bpt_tenant_id` (`tenant_id`),
                  CONSTRAINT `fk_blog_post_translations_post` FOREIGN KEY (`post_id`) REFERENCES `blog_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_post_translations created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_post_translations`");
        echo "✓ Table blog_post_translations dropped\n";
    }
}
