<?php
/**
 * Migration: Create media table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateMediaTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `media` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(10) unsigned DEFAULT NULL,
  `folder_id` int(11) DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `disk` varchar(50) NOT NULL,
  `path` text NOT NULL,
  `public_token` varchar(32) DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `seo_filename` varchar(255) DEFAULT NULL,
  `filename` varchar(255) NOT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `alt_text` varchar(255) DEFAULT NULL,
  `caption` text DEFAULT NULL,
  `metadata` longtext DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_media_tenant_id` (`tenant_id`),
  KEY `idx_media_user_id` (`user_id`),
  KEY `idx_media_disk_path` (`disk`, `path`),
  KEY `idx_folder_id` (`folder_id`),
  KEY `idx_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE media (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  folder_id INTEGER,
  user_id INTEGER,
  disk VARCHAR(50) NOT NULL,
  path TEXT NOT NULL,
  public_token VARCHAR(32),
  slug VARCHAR(255),
  seo_filename VARCHAR(255),
  filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100),
  size INTEGER NOT NULL DEFAULT '0',
  alt_text VARCHAR(255),
  caption TEXT,
  metadata TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX media_idx_media_tenant_id ON media(tenant_id)");
            $pdo->exec("CREATE INDEX media_idx_media_user_id ON media(user_id)");
            $pdo->exec("CREATE INDEX media_idx_media_disk_path ON media(disk, path)");
            $pdo->exec("CREATE INDEX media_idx_folder_id ON media(folder_id)");
            $pdo->exec("CREATE INDEX media_idx_slug ON media(slug)");
        }

        echo "✓ Table media created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `media`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS media");
        }

        echo "✓ Table media dropped\n";
    }
}
