<?php
/**
 * Migration: Create users table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104034
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateUsersTable_2025_12_11_104034
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `registered_ip` varchar(45) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `two_factor_enabled` tinyint(1) DEFAULT '0',
  `two_factor_secret` varchar(64) DEFAULT NULL,
  `two_factor_recovery_codes` text DEFAULT NULL,
  `two_factor_enabled_at` datetime DEFAULT NULL,
  `two_factor_last_used_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_email` (`email`),
  KEY `idx_email_tenant` (`email`, `tenant_id`),
  KEY `idx_users_tenant` (`tenant_id`),
  KEY `idx_users_email` (`email`),
  KEY `idx_users_2fa` (`two_factor_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  avatar VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  registered_ip VARCHAR(45),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  two_factor_enabled SMALLINT DEFAULT '0',
  two_factor_secret VARCHAR(64),
  two_factor_recovery_codes TEXT,
  two_factor_enabled_at TIMESTAMP,
  two_factor_last_used_at TIMESTAMP,
  UNIQUE (email)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX users_idx_email_tenant ON users(email, tenant_id)");
            $pdo->exec("CREATE INDEX users_idx_users_tenant ON users(tenant_id)");
            $pdo->exec("CREATE INDEX users_idx_users_email ON users(email)");
            $pdo->exec("CREATE INDEX users_idx_users_2fa ON users(two_factor_enabled)");
        }

        echo "✓ Table users created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `users`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS users");
        }

        echo "✓ Table users dropped\n";
    }
}
