<?php
/**
 * Migration: Create blog_post_meta table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_104033
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogPostMetaTable_2025_12_11_104033
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_meta` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
  `meta_key` varchar(255) NOT NULL COMMENT 'Clave del metadato',
  `meta_value` longtext DEFAULT NULL COMMENT 'Valor del metadato',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_post_meta_key` (`post_id`, `meta_key`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_meta_key` (`meta_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_post_meta (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL,
  meta_key VARCHAR(255) NOT NULL,
  meta_value TEXT,
  UNIQUE (post_id, meta_key)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_post_meta_idx_post_id ON blog_post_meta(post_id)");
            $pdo->exec("CREATE INDEX blog_post_meta_idx_meta_key ON blog_post_meta(meta_key)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_post_meta.post_id IS 'ID del post'");
            $pdo->exec("COMMENT ON COLUMN blog_post_meta.meta_key IS 'Clave del metadato'");
            $pdo->exec("COMMENT ON COLUMN blog_post_meta.meta_value IS 'Valor del metadato'");
        }

        echo "✓ Table blog_post_meta created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_post_meta`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_post_meta");
        }

        echo "✓ Table blog_post_meta dropped\n";
    }
}
