<?php
/**
 * Migration: Create blog_post_tags table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateBlogPostTagsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_tags` (
                  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',
                  `tag_id` int(10) unsigned NOT NULL COMMENT 'ID de la etiqueta',
                  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `unique_post_tag` (`post_id`,`tag_id`),
                  KEY `idx_post_id` (`post_id`),
                  KEY `idx_tag_id` (`tag_id`),
                  KEY `idx_blog_post_tags_post` (`post_id`),
                  KEY `idx_blog_post_tags_tag` (`tag_id`),
                  CONSTRAINT `fk_blog_post_tags_post` FOREIGN KEY (`post_id`) REFERENCES `blog_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                  CONSTRAINT `fk_blog_post_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `blog_tags` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                  CONSTRAINT `fk_bpt_post` FOREIGN KEY (`post_id`) REFERENCES `blog_posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
                  CONSTRAINT `fk_bpt_tag` FOREIGN KEY (`tag_id`) REFERENCES `blog_tags` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table blog_post_tags created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `blog_post_tags`");
        echo "✓ Table blog_post_tags dropped\n";
    }
}
