<?php
/**
 * Migration: Create rate_limits table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_102306
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateRateLimitsTable_2025_12_11_102306
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `rate_limits` (
  `identifier` varchar(255) NOT NULL COMMENT 'Identificador único (email|tenant|IP)',
  `attempts` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Número de intentos',
  `expires_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de expiración del bloqueo',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creación',
  KEY `idx_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE rate_limits (
  identifier VARCHAR(255) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT '0',
  expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX rate_limits_idx_expires_at ON rate_limits(expires_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN rate_limits.identifier IS 'Identificador único (email|tenant|IP)'");
            $pdo->exec("COMMENT ON COLUMN rate_limits.attempts IS 'Número de intentos'");
            $pdo->exec("COMMENT ON COLUMN rate_limits.expires_at IS 'Fecha de expiración del bloqueo'");
            $pdo->exec("COMMENT ON COLUMN rate_limits.created_at IS 'Fecha de creación'");
        }

        echo "✓ Table rate_limits created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `rate_limits`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS rate_limits");
        }

        echo "✓ Table rate_limits dropped\n";
    }
}
