<?php
/**
 * Migration: Create support_tickets table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreateSupportTicketsTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `support_tickets` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `tenant_id` int(11) NOT NULL COMMENT 'ID del tenant',
                  `admin_id` int(11) NOT NULL COMMENT 'ID del admin que crea el ticket',
                  `assigned_to` int(11) DEFAULT NULL COMMENT 'ID del superadmin asignado',
                  `subject` varchar(500) NOT NULL COMMENT 'Asunto del ticket',
                  `description` text NOT NULL COMMENT 'Descripción del problema',
                  `priority` enum('low','normal','high','urgent') DEFAULT 'normal' COMMENT 'Prioridad',
                  `status` enum('open','in_progress','resolved','closed') DEFAULT 'open' COMMENT 'Estado',
                  `resolved_at` datetime DEFAULT NULL COMMENT 'Fecha de resolución',
                  `created_at` datetime DEFAULT current_timestamp(),
                  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                  PRIMARY KEY (`id`),
                  KEY `tenant_id` (`tenant_id`),
                  KEY `admin_id` (`admin_id`),
                  KEY `assigned_to` (`assigned_to`),
                  KEY `status` (`status`),
                  KEY `priority` (`priority`),
                  KEY `created_at` (`created_at`),
                  KEY `idx_tickets_tenant_status` (`tenant_id`,`status`),
                  KEY `idx_tickets_assigned` (`assigned_to`,`status`),
                  CONSTRAINT `fk_tickets_admin` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`id`) ON DELETE CASCADE,
                  CONSTRAINT `fk_tickets_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tickets de soporte de tenants'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table support_tickets created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `support_tickets`");
        echo "✓ Table support_tickets dropped\n";
    }
}
