<?php
/**
 * Migration: Create tenants table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateTenantsTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenants` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) DEFAULT NULL,
  `domain` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` varchar(20) DEFAULT 'active',
  `admin_path` varchar(50) DEFAULT 'admin',
  `theme` varchar(255) DEFAULT 'default',
  `theme_type` enum('global','custom') NOT NULL DEFAULT 'global' COMMENT 'Tipo de tema: global (del sistema) o custom (personalizado)',
  `custom_theme_slug` varchar(100) DEFAULT NULL COMMENT 'Slug del tema personalizado si theme_type=custom',
  PRIMARY KEY (`id`),
  UNIQUE KEY `domain` (`domain`),
  UNIQUE KEY `slug` (`slug`),
  KEY `idx_theme_type` (`theme_type`),
  KEY `idx_custom_theme_slug` (`custom_theme_slug`),
  KEY `idx_tenants_slug` (`slug`),
  KEY `idx_tenants_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE tenants (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100),
  domain VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'active',
  admin_path VARCHAR(50) DEFAULT 'admin',
  theme VARCHAR(255) DEFAULT 'default',
  theme_type VARCHAR(20) NOT NULL DEFAULT 'global',
  custom_theme_slug VARCHAR(100),
  CHECK (theme_type IN ('global', 'custom')),
  UNIQUE (domain),
  UNIQUE (slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX tenants_idx_theme_type ON tenants(theme_type)");
            $pdo->exec("CREATE INDEX tenants_idx_custom_theme_slug ON tenants(custom_theme_slug)");
            $pdo->exec("CREATE INDEX tenants_idx_tenants_slug ON tenants(slug)");
            $pdo->exec("CREATE INDEX tenants_idx_tenants_status ON tenants(status)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN tenants.theme_type IS 'Tipo de tema: global (del sistema) o custom (personalizado)'");
            $pdo->exec("COMMENT ON COLUMN tenants.custom_theme_slug IS 'Slug del tema personalizado si theme_type=custom'");
        }

        echo "✓ Table tenants created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `tenants`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS tenants");
        }

        echo "✓ Table tenants dropped\n";
    }
}
