<?php
/**
 * Migration: Create pages_trash table
 * Generated by MuseDock Migration Generator
 * Generated at: 2025_12_08_103508
 */

use Screenart\Musedock\Database;

class CreatePagesTrashTable_2025_12_08_103508
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = Database::getDriver();

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `pages_trash` (
                  `id` int(11) NOT NULL AUTO_INCREMENT,
                  `page_id` int(11) NOT NULL,
                  `tenant_id` int(11) DEFAULT NULL COMMENT 'NULL para páginas de superadmin',
                  `deleted_by` int(11) NOT NULL,
                  `deleted_by_name` varchar(100) DEFAULT NULL COMMENT 'Cache del nombre',
                  `deleted_by_type` enum('user','admin','superadmin') DEFAULT 'admin',
                  `deleted_at` datetime NOT NULL,
                  `scheduled_permanent_delete` datetime DEFAULT NULL COMMENT 'Auto-eliminar después de 30 días',
                  `reason` varchar(255) DEFAULT NULL COMMENT 'Razón de eliminación (opcional)',
                  `ip_address` varchar(45) DEFAULT NULL,
                  PRIMARY KEY (`id`),
                  KEY `idx_page_id` (`page_id`),
                  KEY `idx_tenant_id` (`tenant_id`),
                  KEY `idx_deleted_at` (`deleted_at`),
                  KEY `idx_scheduled_delete` (`scheduled_permanent_delete`),
                  KEY `idx_deleted_by` (`deleted_by`)
                ) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Papelera temporal de páginas (recuperable por 30 días)'
            ");
        } else {
            // PostgreSQL version - needs manual adjustment
            throw new \Exception('PostgreSQL schema not generated. Please create manually.');
        }

        echo "✓ Table pages_trash created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $pdo->exec("DROP TABLE IF EXISTS `pages_trash`");
        echo "✓ Table pages_trash dropped\n";
    }
}
