<?php
/**
 * Migration: Create api_keys table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2026_04_05_000001
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateApiKeysTable_2026_04_05_000001
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS `api_keys` (
                    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
                    `tenant_id` int(11) DEFAULT NULL COMMENT 'NULL = superadmin/cross-tenant key',
                    `domain_group_id` int(11) DEFAULT NULL COMMENT 'Restricts superadmin key to a domain group from Cross-Publisher',
                    `name` varchar(255) NOT NULL COMMENT 'Descriptive name for the key',
                    `api_key_hash` varchar(64) NOT NULL COMMENT 'SHA-256 hash of the API key',
                    `permissions` text DEFAULT NULL COMMENT 'JSON array of permissions',
                    `rate_limit` int(11) NOT NULL DEFAULT 60 COMMENT 'Requests per minute',
                    `request_count_minute` int(11) NOT NULL DEFAULT 0 COMMENT 'Current minute request count',
                    `last_request_at` datetime DEFAULT NULL COMMENT 'Last request timestamp',
                    `last_used_at` datetime DEFAULT NULL COMMENT 'Last successful use',
                    `expires_at` datetime DEFAULT NULL COMMENT 'Expiration date (NULL = never)',
                    `is_active` tinyint(1) NOT NULL DEFAULT 1,
                    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` timestamp DEFAULT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `unique_api_key_hash` (`api_key_hash`),
                    KEY `idx_api_keys_tenant` (`tenant_id`),
                    KEY `idx_api_keys_active` (`is_active`),
                    KEY `idx_api_keys_expires` (`expires_at`),
                    KEY `idx_api_keys_domain_group` (`domain_group_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE IF NOT EXISTS api_keys (
                    id SERIAL PRIMARY KEY,
                    tenant_id INTEGER DEFAULT NULL,
                    domain_group_id INTEGER DEFAULT NULL,
                    name VARCHAR(255) NOT NULL,
                    api_key_hash VARCHAR(64) NOT NULL,
                    permissions TEXT DEFAULT NULL,
                    rate_limit INTEGER NOT NULL DEFAULT 60,
                    request_count_minute INTEGER NOT NULL DEFAULT 0,
                    last_request_at TIMESTAMP DEFAULT NULL,
                    last_used_at TIMESTAMP DEFAULT NULL,
                    expires_at TIMESTAMP DEFAULT NULL,
                    is_active SMALLINT NOT NULL DEFAULT 1,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT NULL
                )
            ");

            // Indexes
            $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS unique_api_key_hash ON api_keys (api_key_hash)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON api_keys (tenant_id)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_api_keys_active ON api_keys (is_active)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_api_keys_expires ON api_keys (expires_at)");
            $pdo->exec("CREATE INDEX IF NOT EXISTS idx_api_keys_domain_group ON api_keys (domain_group_id)");
        }

        // Add menu item
        $this->seedMenu();
    }

    /**
     * Seed: Add API Keys menu item under Settings.
     */
    private function seedMenu()
    {
        $pdo = Database::connect();

        // Check if already exists
        $stmt = $pdo->prepare("SELECT id FROM admin_menus WHERE slug = 'api-keys' LIMIT 1");
        $stmt->execute();
        if ($stmt->fetchColumn()) return;

        // Find Settings parent menu
        $stmt = $pdo->prepare("SELECT id FROM admin_menus WHERE slug = 'settings' AND parent_id IS NULL LIMIT 1");
        $stmt->execute();
        $parentId = $stmt->fetchColumn();
        if (!$parentId) return;

        $pdo->prepare("
            INSERT INTO admin_menus (parent_id, title, slug, url, icon, icon_type, order_position, permission, is_active, show_in_superadmin, show_in_tenant, created_at, updated_at)
            VALUES (?, 'API Keys', 'api-keys', '{admin_path}/settings/api-keys', 'key', 'bi', 12, NULL, 1, 1, 1, NOW(), NOW())
        ")->execute([$parentId]);
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `api_keys`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS api_keys");
        }
    }
}
