<?php
/**
 * Migration: Create blog_comments table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2026_04_12_210001
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogCommentsTable_2026_04_12_210001
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("\n                CREATE TABLE `blog_comments` (\n  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para comentarios globales)',\n  `post_id` int(10) unsigned NOT NULL COMMENT 'ID del post',\n  `author_name` varchar(120) NOT NULL COMMENT 'Nombre del autor del comentario',\n  `author_email` varchar(190) NOT NULL COMMENT 'Email del autor del comentario',\n  `author_url` varchar(500) DEFAULT NULL COMMENT 'Sitio web opcional del autor',\n  `content` text NOT NULL COMMENT 'Contenido del comentario',\n  `status` enum('pending','approved','spam','rejected') NOT NULL DEFAULT 'pending' COMMENT 'Estado de moderación',\n  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP del autor',\n  `user_agent` varchar(500) DEFAULT NULL COMMENT 'User-Agent del autor',\n  `approved_at` datetime DEFAULT NULL COMMENT 'Fecha de aprobación',\n  `approved_by` int(11) DEFAULT NULL COMMENT 'ID del moderador',\n  `approved_by_type` enum('superadmin','admin') DEFAULT NULL COMMENT 'Tipo de moderador',\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `idx_blog_comments_tenant` (`tenant_id`),\n  KEY `idx_blog_comments_post` (`post_id`),\n  KEY `idx_blog_comments_status` (`status`),\n  KEY `idx_blog_comments_post_status` (`post_id`, `status`),\n  KEY `idx_blog_comments_created` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ");
        } else {
            // PostgreSQL
            $pdo->exec("\n                CREATE TABLE blog_comments (\n  id SERIAL PRIMARY KEY,\n  tenant_id INTEGER,\n  post_id INTEGER NOT NULL,\n  author_name VARCHAR(120) NOT NULL,\n  author_email VARCHAR(190) NOT NULL,\n  author_url VARCHAR(500),\n  content TEXT NOT NULL,\n  status VARCHAR(20) NOT NULL DEFAULT 'pending',\n  ip_address VARCHAR(45),\n  user_agent VARCHAR(500),\n  approved_at TIMESTAMP,\n  approved_by INTEGER,\n  approved_by_type VARCHAR(20),\n  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at TIMESTAMP,\n  CHECK (status IN ('pending', 'approved', 'spam', 'rejected')),\n  CHECK (approved_by_type IN ('superadmin', 'admin') OR approved_by_type IS NULL)\n)\n            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_comments_idx_tenant ON blog_comments(tenant_id)");
            $pdo->exec("CREATE INDEX blog_comments_idx_post ON blog_comments(post_id)");
            $pdo->exec("CREATE INDEX blog_comments_idx_status ON blog_comments(status)");
            $pdo->exec("CREATE INDEX blog_comments_idx_post_status ON blog_comments(post_id, status)");
            $pdo->exec("CREATE INDEX blog_comments_idx_created ON blog_comments(created_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_comments.tenant_id IS 'ID del tenant (NULL para comentarios globales)'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.post_id IS 'ID del post'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.author_name IS 'Nombre del autor del comentario'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.author_email IS 'Email del autor del comentario'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.author_url IS 'Sitio web opcional del autor'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.content IS 'Contenido del comentario'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.status IS 'Estado de moderación'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.ip_address IS 'IP del autor'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.user_agent IS 'User-Agent del autor'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.approved_at IS 'Fecha de aprobación'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.approved_by IS 'ID del moderador'");
            $pdo->exec("COMMENT ON COLUMN blog_comments.approved_by_type IS 'Tipo de moderador'");
        }

        echo "✓ Table blog_comments created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_comments`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_comments");
        }

        echo "✓ Table blog_comments dropped\n";
    }
}
