<?php
/**
 * Migration: Create react_sliders table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateReactSlidersTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `react_sliders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Nombre del slider',
  `identifier` varchar(100) NOT NULL COMMENT 'Identificador único',
  `engine` enum('swiper','slick','keen','embla') DEFAULT 'swiper' COMMENT 'Motor del slider',
  `settings` text DEFAULT NULL COMMENT 'Configuración JSON',
  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL = global)',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '1 = Activo, 0 = Inactivo',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_identifier_tenant` (`identifier`, `tenant_id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE react_sliders (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  identifier VARCHAR(100) NOT NULL,
  engine VARCHAR(20) DEFAULT 'swiper',
  settings TEXT,
  tenant_id INTEGER,
  is_active SMALLINT DEFAULT '1',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (engine IN ('swiper', 'slick', 'keen', 'embla')),
  UNIQUE (identifier, tenant_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX react_sliders_tenant_id ON react_sliders(tenant_id)");
            $pdo->exec("CREATE INDEX react_sliders_is_active ON react_sliders(is_active)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN react_sliders.name IS 'Nombre del slider'");
            $pdo->exec("COMMENT ON COLUMN react_sliders.identifier IS 'Identificador único'");
            $pdo->exec("COMMENT ON COLUMN react_sliders.engine IS 'Motor del slider'");
            $pdo->exec("COMMENT ON COLUMN react_sliders.settings IS 'Configuración JSON'");
            $pdo->exec("COMMENT ON COLUMN react_sliders.tenant_id IS 'ID del tenant (NULL = global)'");
            $pdo->exec("COMMENT ON COLUMN react_sliders.is_active IS '1 = Activo, 0 = Inactivo'");
        }

        echo "✓ Table react_sliders created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `react_sliders`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS react_sliders");
        }

        echo "✓ Table react_sliders dropped\n";
    }
}
