<?php
/**
 * Migration: Create custom_form_submissions table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateCustomFormSubmissionsTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `custom_form_submissions` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` int(11) unsigned NOT NULL,
  `data` longtext NOT NULL COMMENT 'Datos del envío en JSON',
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `referrer_url` varchar(500) DEFAULT NULL,
  `page_url` varchar(500) DEFAULT NULL COMMENT 'URL donde se envió el formulario',
  `user_id` int(11) unsigned DEFAULT NULL COMMENT 'Usuario autenticado si aplica',
  `email_sent` tinyint(1) DEFAULT '0',
  `email_sent_at` datetime DEFAULT NULL,
  `confirmation_sent` tinyint(1) DEFAULT '0',
  `is_read` tinyint(1) DEFAULT '0',
  `is_starred` tinyint(1) DEFAULT '0',
  `is_spam` tinyint(1) DEFAULT '0',
  `notes` text DEFAULT NULL COMMENT 'Notas internas',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_form_id` (`form_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_is_read` (`is_read`),
  KEY `idx_is_starred` (`is_starred`),
  KEY `idx_is_spam` (`is_spam`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE custom_form_submissions (
  id SERIAL PRIMARY KEY,
  form_id INTEGER NOT NULL,
  data TEXT NOT NULL,
  ip_address VARCHAR(45),
  user_agent VARCHAR(500),
  referrer_url VARCHAR(500),
  page_url VARCHAR(500),
  user_id INTEGER,
  email_sent SMALLINT DEFAULT '0',
  email_sent_at TIMESTAMP,
  confirmation_sent SMALLINT DEFAULT '0',
  is_read SMALLINT DEFAULT '0',
  is_starred SMALLINT DEFAULT '0',
  is_spam SMALLINT DEFAULT '0',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX custom_form_submissions_idx_form_id ON custom_form_submissions(form_id)");
            $pdo->exec("CREATE INDEX custom_form_submissions_idx_created_at ON custom_form_submissions(created_at)");
            $pdo->exec("CREATE INDEX custom_form_submissions_idx_is_read ON custom_form_submissions(is_read)");
            $pdo->exec("CREATE INDEX custom_form_submissions_idx_is_starred ON custom_form_submissions(is_starred)");
            $pdo->exec("CREATE INDEX custom_form_submissions_idx_is_spam ON custom_form_submissions(is_spam)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN custom_form_submissions.data IS 'Datos del envío en JSON'");
            $pdo->exec("COMMENT ON COLUMN custom_form_submissions.page_url IS 'URL donde se envió el formulario'");
            $pdo->exec("COMMENT ON COLUMN custom_form_submissions.user_id IS 'Usuario autenticado si aplica'");
            $pdo->exec("COMMENT ON COLUMN custom_form_submissions.notes IS 'Notas internas'");
        }

        echo "✓ Table custom_form_submissions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `custom_form_submissions`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS custom_form_submissions");
        }

        echo "✓ Table custom_form_submissions dropped\n";
    }
}
