<?php
/**
 * Migration: Create admin_menu_customizations table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateAdminMenuCustomizationsTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `admin_menu_customizations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL,
  `admin_menu_id` int(11) NOT NULL,
  `custom_title` varchar(255) DEFAULT NULL,
  `custom_icon` varchar(100) DEFAULT NULL,
  `custom_icon_type` enum('bi','fas','far','fal') DEFAULT NULL,
  `custom_order_position` int(11) DEFAULT NULL,
  `is_hidden` tinyint(1) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_menu` (`tenant_id`, `admin_menu_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_admin_menu_id` (`admin_menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE admin_menu_customizations (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  admin_menu_id INTEGER NOT NULL,
  custom_title VARCHAR(255),
  custom_icon VARCHAR(100),
  custom_icon_type VARCHAR(20),
  custom_order_position INTEGER,
  is_hidden SMALLINT DEFAULT '0',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (custom_icon_type IN ('bi', 'fas', 'far', 'fal')),
  UNIQUE (tenant_id, admin_menu_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX admin_menu_customizations_idx_tenant_id ON admin_menu_customizations(tenant_id)");
            $pdo->exec("CREATE INDEX admin_menu_customizations_idx_admin_menu_id ON admin_menu_customizations(admin_menu_id)");
        }

        echo "✓ Table admin_menu_customizations created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `admin_menu_customizations`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS admin_menu_customizations");
        }

        echo "✓ Table admin_menu_customizations dropped\n";
    }
}
