<?php
/**
 * Migration: Create blog_post_revisions table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogPostRevisionsTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_post_revisions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `post_id` int(11) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_name` varchar(100) DEFAULT NULL COMMENT 'Cache del nombre para auditoría',
  `user_type` enum('user','admin','superadmin') DEFAULT 'admin',
  `revision_type` enum('autosave','manual','published','restored','scheduled','initial') NOT NULL DEFAULT 'manual',
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `content` longtext NOT NULL,
  `excerpt` text DEFAULT NULL,
  `featured_image` varchar(255) DEFAULT NULL,
  `meta_data` longtext DEFAULT NULL COMMENT 'SEO, visibilidad, custom fields, etc.',
  `status` enum('draft','published','scheduled','trash') DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `changes_summary` varchar(255) DEFAULT NULL COMMENT 'Descripción breve de los cambios',
  PRIMARY KEY (`id`),
  KEY `idx_post_id` (`post_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_revision_type` (`revision_type`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_post_revisions (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL,
  tenant_id INTEGER,
  user_id INTEGER,
  user_name VARCHAR(100),
  user_type VARCHAR(20) DEFAULT 'admin',
  revision_type VARCHAR(20) NOT NULL DEFAULT 'manual',
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  content TEXT NOT NULL,
  excerpt TEXT,
  featured_image VARCHAR(255),
  meta_data TEXT,
  status VARCHAR(20),
  created_at TIMESTAMP NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  changes_summary VARCHAR(255),
  CHECK (user_type IN ('user', 'admin', 'superadmin')),
  CHECK (revision_type IN ('autosave', 'manual', 'published', 'restored', 'scheduled', 'initial')),
  CHECK (status IN ('draft', 'published', 'scheduled', 'trash'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX blog_post_revisions_idx_post_id ON blog_post_revisions(post_id)");
            $pdo->exec("CREATE INDEX blog_post_revisions_idx_tenant_id ON blog_post_revisions(tenant_id)");
            $pdo->exec("CREATE INDEX blog_post_revisions_idx_created_at ON blog_post_revisions(created_at)");
            $pdo->exec("CREATE INDEX blog_post_revisions_idx_revision_type ON blog_post_revisions(revision_type)");
            $pdo->exec("CREATE INDEX blog_post_revisions_idx_user_id ON blog_post_revisions(user_id)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_post_revisions.user_name IS 'Cache del nombre para auditoría'");
            $pdo->exec("COMMENT ON COLUMN blog_post_revisions.meta_data IS 'SEO, visibilidad, custom fields, etc.'");
            $pdo->exec("COMMENT ON COLUMN blog_post_revisions.changes_summary IS 'Descripción breve de los cambios'");
        }

        echo "✓ Table blog_post_revisions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_post_revisions`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_post_revisions");
        }

        echo "✓ Table blog_post_revisions dropped\n";
    }
}
