<?php
/**
 * Migration: Create support_ticket_messages table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateSupportTicketMessagesTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `support_ticket_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ticket_id` int(11) NOT NULL COMMENT 'ID del ticket',
  `user_id` int(11) NOT NULL COMMENT 'ID del usuario que escribe',
  `user_type` enum('admin','super_admin') NOT NULL COMMENT 'Tipo de usuario',
  `message` text NOT NULL COMMENT 'Mensaje',
  `is_internal` tinyint(1) DEFAULT '0' COMMENT '1 = Nota interna (solo staff)',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ticket_id` (`ticket_id`),
  KEY `user_type` (`user_type`, `user_id`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE support_ticket_messages (
  id SERIAL PRIMARY KEY,
  ticket_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  user_type VARCHAR(20) NOT NULL,
  message TEXT NOT NULL,
  is_internal SMALLINT DEFAULT '0',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (user_type IN ('admin', 'super_admin'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX support_ticket_messages_ticket_id ON support_ticket_messages(ticket_id)");
            $pdo->exec("CREATE INDEX support_ticket_messages_user_type ON support_ticket_messages(user_type, user_id)");
            $pdo->exec("CREATE INDEX support_ticket_messages_created_at ON support_ticket_messages(created_at)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN support_ticket_messages.ticket_id IS 'ID del ticket'");
            $pdo->exec("COMMENT ON COLUMN support_ticket_messages.user_id IS 'ID del usuario que escribe'");
            $pdo->exec("COMMENT ON COLUMN support_ticket_messages.user_type IS 'Tipo de usuario'");
            $pdo->exec("COMMENT ON COLUMN support_ticket_messages.message IS 'Mensaje'");
            $pdo->exec("COMMENT ON COLUMN support_ticket_messages.is_internal IS '1 = Nota interna (solo staff)'");
        }

        echo "✓ Table support_ticket_messages created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `support_ticket_messages`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS support_ticket_messages");
        }

        echo "✓ Table support_ticket_messages dropped\n";
    }
}
