<?php
/**
 * Migration: Create tenant_admin_menu_visibility table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_093916
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateTenantAdminMenuVisibilityTable_2025_12_11_093916
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `tenant_admin_menu_visibility` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) NOT NULL,
  `admin_menu_id` int(11) NOT NULL,
  `is_visible` tinyint(1) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_menu` (`tenant_id`, `admin_menu_id`),
  KEY `admin_menu_id` (`admin_menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE tenant_admin_menu_visibility (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  admin_menu_id INTEGER NOT NULL,
  is_visible SMALLINT DEFAULT '1',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, admin_menu_id)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX tenant_admin_menu_visibility_admin_menu_id ON tenant_admin_menu_visibility(admin_menu_id)");
        }

        echo "✓ Table tenant_admin_menu_visibility created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `tenant_admin_menu_visibility`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS tenant_admin_menu_visibility");
        }

        echo "✓ Table tenant_admin_menu_visibility dropped\n";
    }
}
