<?php
/**
 * Migration: Create blog_categories table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_091120
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreateBlogCategoriesTable_2025_12_11_091120
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `blog_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL COMMENT 'ID del tenant (NULL para categorías globales)',
  `parent_id` int(10) unsigned DEFAULT NULL COMMENT 'ID de la categoría padre (para jerarquía)',
  `name` varchar(255) NOT NULL COMMENT 'Nombre de la categoría',
  `slug` varchar(300) NOT NULL COMMENT 'URL amigable',
  `description` text DEFAULT NULL COMMENT 'Descripción de la categoría',
  `image` varchar(500) DEFAULT NULL COMMENT 'Imagen de la categoría',
  `color` varchar(7) DEFAULT NULL COMMENT 'Color en formato hexadecimal',
  `order` int(11) NOT NULL DEFAULT '0' COMMENT 'Orden de visualización',
  `post_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Contador de posts',
  `seo_title` varchar(500) DEFAULT NULL COMMENT 'Título para SEO',
  `seo_description` text DEFAULT NULL COMMENT 'Descripción para SEO',
  `seo_keywords` text DEFAULT NULL COMMENT 'Palabras clave',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL COMMENT 'Fecha y hora de eliminación lógica',
  `deleted_by` int(11) DEFAULT NULL COMMENT 'ID del usuario que eliminó el registro',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_tenant_slug` (`tenant_id`, `slug`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_slug` (`slug`),
  KEY `idx_order` (`order`),
  KEY `idx_blog_categories_deleted_at` (`deleted_at`),
  KEY `idx_blog_categories_tenant` (`tenant_id`),
  KEY `idx_blog_categories_slug` (`slug`),
  KEY `idx_blog_categories_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE blog_categories (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER,
  parent_id INTEGER,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(300) NOT NULL,
  description TEXT,
  image VARCHAR(500),
  color VARCHAR(7),
  order INTEGER NOT NULL DEFAULT '0',
  post_count INTEGER NOT NULL DEFAULT '0',
  seo_title VARCHAR(500),
  seo_description TEXT,
  seo_keywords TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  deleted_by INTEGER,
  UNIQUE (tenant_id, slug)
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX idx_tenant_id ON blog_categories(tenant_id)");
            $pdo->exec("CREATE INDEX idx_parent_id ON blog_categories(parent_id)");
            $pdo->exec("CREATE INDEX idx_slug ON blog_categories(slug)");
            $pdo->exec("CREATE INDEX idx_order ON blog_categories(order)");
            $pdo->exec("CREATE INDEX idx_blog_categories_deleted_at ON blog_categories(deleted_at)");
            $pdo->exec("CREATE INDEX idx_blog_categories_tenant ON blog_categories(tenant_id)");
            $pdo->exec("CREATE INDEX idx_blog_categories_slug ON blog_categories(slug)");
            $pdo->exec("CREATE INDEX idx_blog_categories_parent ON blog_categories(parent_id)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN blog_categories.tenant_id IS 'ID del tenant (NULL para categorías globales)'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.parent_id IS 'ID de la categoría padre (para jerarquía)'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.name IS 'Nombre de la categoría'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.slug IS 'URL amigable'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.description IS 'Descripción de la categoría'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.image IS 'Imagen de la categoría'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.color IS 'Color en formato hexadecimal'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.order IS 'Orden de visualización'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.post_count IS 'Contador de posts'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.seo_title IS 'Título para SEO'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.seo_description IS 'Descripción para SEO'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.seo_keywords IS 'Palabras clave'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.deleted_at IS 'Fecha y hora de eliminación lógica'");
            $pdo->exec("COMMENT ON COLUMN blog_categories.deleted_by IS 'ID del usuario que eliminó el registro'");
        }

        echo "✓ Table blog_categories created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `blog_categories`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS blog_categories");
        }

        echo "✓ Table blog_categories dropped\n";
    }
}
