<?php
/**
 * Migration: Create page_revisions table
 * Generated by MuseDock Dual Migration Generator
 * Generated at: 2025_12_11_091120
 * Compatible with: MySQL/MariaDB + PostgreSQL
 */

use Screenart\Musedock\Database;

class CreatePageRevisionsTable_2025_12_11_091120
{
    public function up()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("
                CREATE TABLE `page_revisions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page_id` int(11) NOT NULL,
  `tenant_id` int(11) DEFAULT NULL COMMENT 'NULL para páginas de superadmin',
  `user_id` int(11) DEFAULT NULL,
  `user_name` varchar(100) DEFAULT NULL COMMENT 'Cache del nombre para auditoría',
  `user_type` enum('user','admin','superadmin') DEFAULT 'admin',
  `revision_type` enum('autosave','manual','published','restored','scheduled','initial') NOT NULL DEFAULT 'manual',
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `content` longtext NOT NULL,
  `excerpt` text DEFAULT NULL,
  `slider_image` varchar(255) DEFAULT NULL,
  `meta_data` longtext DEFAULT NULL COMMENT 'SEO, visibilidad, layout, custom fields, etc.',
  `status` enum('draft','published','scheduled','trash') DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `changes_summary` varchar(255) DEFAULT NULL COMMENT 'Descripción breve de los cambios',
  PRIMARY KEY (`id`),
  KEY `idx_page_id` (`page_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_revision_type` (`revision_type`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ");
        } else {
            // PostgreSQL
            $pdo->exec("
                CREATE TABLE page_revisions (
  id SERIAL PRIMARY KEY,
  page_id INTEGER NOT NULL,
  tenant_id INTEGER,
  user_id INTEGER,
  user_name VARCHAR(100),
  user_type VARCHAR(20) DEFAULT 'admin',
  revision_type VARCHAR(20) NOT NULL DEFAULT 'manual',
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  content TEXT NOT NULL,
  excerpt TEXT,
  slider_image VARCHAR(255),
  meta_data TEXT,
  status VARCHAR(20),
  created_at TIMESTAMP NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  changes_summary VARCHAR(255),
  CHECK (user_type IN ('user', 'admin', 'superadmin')),
  CHECK (revision_type IN ('autosave', 'manual', 'published', 'restored', 'scheduled', 'initial')),
  CHECK (status IN ('draft', 'published', 'scheduled', 'trash'))
)
            ");

            // Create indexes
            $pdo->exec("CREATE INDEX idx_page_id ON page_revisions(page_id)");
            $pdo->exec("CREATE INDEX idx_tenant_id ON page_revisions(tenant_id)");
            $pdo->exec("CREATE INDEX idx_created_at ON page_revisions(created_at)");
            $pdo->exec("CREATE INDEX idx_revision_type ON page_revisions(revision_type)");
            $pdo->exec("CREATE INDEX idx_user_id ON page_revisions(user_id)");

            // Add comments
            $pdo->exec("COMMENT ON COLUMN page_revisions.tenant_id IS 'NULL para páginas de superadmin'");
            $pdo->exec("COMMENT ON COLUMN page_revisions.user_name IS 'Cache del nombre para auditoría'");
            $pdo->exec("COMMENT ON COLUMN page_revisions.meta_data IS 'SEO, visibilidad, layout, custom fields, etc.'");
            $pdo->exec("COMMENT ON COLUMN page_revisions.changes_summary IS 'Descripción breve de los cambios'");
        }

        echo "✓ Table page_revisions created\n";
    }

    public function down()
    {
        $pdo = Database::connect();
        $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

        if ($driver === 'mysql') {
            $pdo->exec("DROP TABLE IF EXISTS `page_revisions`");
        } else {
            $pdo->exec("DROP TABLE IF EXISTS page_revisions");
        }

        echo "✓ Table page_revisions dropped\n";
    }
}
